// #102 — ConvertOptions.manifests.
//
// `convert()` threads `manifests` into its underlying `parse()`, so a yarn-family
// source honours its `resolutions`/`overrides` pins on convert (the Bug #99
// override map bridges a pinned, possibly-NON-satisfying descriptor back to its
// node). Without manifests the non-satisfying pin's edge stays dropped, so the
// converted output omits it; with manifests the edge survives the conversion.
//
// DECISION (owner): convert stays a pure parse→stringify — the captured overrides
// are NOT auto-threaded into the stringify `overrides` slot (so the TARGET lock's
// own overrides block is unaffected; only the resolved GRAPH changes).

import { describe, expect, it } from 'vitest'
import { convert, parse, stringify } from '../../main/ts/index.ts'
import type { Manifest } from '../../main/ts/graph.ts'

// root declares csstype `npm:^3.1.3`; the pinned entry key is `csstype@npm:3.0.9`
// (a `resolutions` rewrite). Two csstype entries exist (3.0.9 + 2.6.21) and
// `^3.1.3` is satisfied by NEITHER, so Rung 3 semver has ≥2 candidates and no
// satisfier → DROP. Only the override map (from the manifest) can bridge the
// non-satisfying pin. (A single csstype entry would Rung-3-short-circuit even
// without a manifest, masking the effect — two non-satisfying siblings force the
// drop, exactly the backstage real-world shape.)
const BERRY_LOCK = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10

"csstype@npm:3.0.9":
  version: 3.0.9
  resolution: "csstype@npm:3.0.9"
  checksum: 10/aaaa
  languageName: node
  linkType: hard

"csstype@npm:^2.5.2":
  version: 2.6.21
  resolution: "csstype@npm:2.6.21"
  checksum: 10/bbbb
  languageName: node
  linkType: hard

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    csstype: "npm:^3.1.3"
  languageName: unknown
  linkType: soft
`

const MANIFESTS: Record<string, Manifest> = {
  '': { name: 'root', native: { yarnResolutions: { 'csstype@npm:^3.1.3': '3.0.9' } } },
}

// The importer block (`.:` … up to the next top-level section) is where a root
// dependency surfaces in a pnpm lock. Isolating it avoids matching the orphan
// `packages:` entries (which list every node regardless of reachability, since
// convert is parse→stringify with no optimize).
function importerBlock(out: string): string {
  const start = out.indexOf('importers:')
  const pkgs = out.indexOf('\npackages:', start)
  return out.slice(start, pkgs >= 0 ? pkgs : undefined)
}

describe('#102 — convert() honours a resolutions pin via manifests', () => {
  it('WITHOUT manifests: the non-satisfying pin is dropped → no csstype dependency under the importer', () => {
    const out = convert(BERRY_LOCK, { from: 'yarn-berry-v8', to: 'pnpm-v9' })
    // The root→csstype edge was dropped (no override map, no semver satisfier), so
    // the importer carries no csstype dependency.
    expect(importerBlock(out)).not.toMatch(/csstype/)
  })

  it('WITH manifests: the override map bridges the pin → csstype dependency appears under the importer', () => {
    const out = convert(BERRY_LOCK, { from: 'yarn-berry-v8', to: 'pnpm-v9', manifests: MANIFESTS })
    // The restored edge re-points root onto the pinned csstype 3.0.9 node, so the
    // importer now carries the csstype dependency resolved to 3.0.9.
    const importer = importerBlock(out)
    expect(importer).toMatch(/csstype/)
    expect(importer).toMatch(/3\.0\.9/)
  })

  it('matches the equivalent parse({manifests}) → stringify pipeline (pure parse→stringify)', () => {
    // convert is exactly parse(from, …, { manifests }) → stringify(to, …); no
    // override auto-threading. Prove equality against the manual pipeline.
    const viaConvert = convert(BERRY_LOCK, { from: 'yarn-berry-v8', to: 'pnpm-v9', manifests: MANIFESTS })
    const g = parse('yarn-berry-v8', BERRY_LOCK, { manifests: MANIFESTS })
    const viaPipeline = stringify('pnpm-v9', g)
    expect(viaConvert).toBe(viaPipeline)
  })
})

// A classic yarn.lock encodes NO project root (unlike npm's `""` entry, berry's
// `root@workspace:.`, pnpm importers, bun workspaces). Its root identity can come
// only from `manifests`, so the public `parse`/`convert` must run the
// manifest-driven `enrich` to synthesize the declared root — otherwise a
// top-of-DAG dependency is promoted to the `""` root and its own installable node
// is dropped, producing a lock that fails `npm ci`. Reported externally against
// snapshot.92 (the flagship synp `yarn.lock → package-lock.json` direction).
describe('rootless yarn-classic source is re-rooted from manifests', () => {
  const YARN = `# yarn lockfile v1
chalk@^2.4.2:
  version "2.4.2"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-2.4.2.tgz#cd42541677a54333cf541a49108c1432b44c9424"
  integrity sha512-Mti+
  dependencies:
    ansi-styles "^3.2.1"
ansi-styles@^3.2.1:
  version "3.2.1"
  resolved "https://registry.yarnpkg.com/ansi-styles/-/ansi-styles-3.2.1.tgz#41fbb642"
  integrity sha512-VT0Z
`
  const MAN: Record<string, Manifest> = {
    '': { name: 'app', version: '1.0.0', dependencies: { chalk: '^2.4.2' } },
  }

  it('convert → npm-3 synthesizes the declared root, keeping the dependency as its own node', () => {
    const npm3 = JSON.parse(convert(YARN, { from: 'yarn-classic', to: 'npm-3', manifests: MAN })) as {
      name: string
      packages: Record<string, { name?: string; dependencies?: Record<string, string> }>
    }
    expect(npm3.name).toBe('app')                                  // root is the declared project, not `chalk`
    expect(npm3.packages[''].dependencies).toEqual({ chalk: '^2.4.2' })
    expect('node_modules/chalk' in npm3.packages).toBe(true)      // the promoted dep no longer vanishes
  })

  it('parse().roots() is the synthesized root', () => {
    const g = parse('yarn-classic', YARN, { manifests: MAN })
    expect(Array.from(g.roots())).toEqual(['app@1.0.0'])
  })

  it('the pnpm importer lists the real root dependency (chalk), not a transitive', () => {
    const out = convert(YARN, { from: 'yarn-classic', to: 'pnpm-v9', manifests: MAN })
    const importer = out.slice(out.indexOf('importers:'), out.indexOf('\npackages:'))
    expect(importer).toMatch(/chalk:/)
    expect(importer).not.toMatch(/ansi-styles:/)
  })

  it('synthesis is manifest-gated — without manifests the rootless source is left as-is', () => {
    // No manifests ⇒ no root invention (the pre-existing degenerate behaviour is
    // deliberately unchanged; there is no declared identity to root from).
    const g = parse('yarn-classic', YARN)
    expect(Array.from(g.roots())).not.toContain('app@1.0.0')
  })

  it('warns (not silently) when a multi-member workspace drops member dependencies', () => {
    // KNOWN GAP: enrich synthesizes ROOT edges but not workspace-MEMBER dep edges.
    // A multi-member conversion is incomplete; surface it as a warning rather than
    // emit a silently-broken lock. (Single-root stays warning-free — covered above.)
    const codes: string[] = []
    convert(YARN, {
      from: 'yarn-classic',
      to: 'npm-3',
      manifests: {
        ...MAN,
        'packages/a': { name: '@s/a', version: '0.0.0', dependencies: { lodash: '^4.0.0' } },
      },
      onDiagnostic: d => codes.push(d.code),
    })
    expect(codes).toContain('YARN_CLASSIC_WORKSPACE_MEMBER_DEPS_UNSYNTHESISED')
  })
})
