// #102 — ConvertOptions.manifests.
//
// `convert()` threads `manifests` into its underlying `parse()`, so a yarn-family
// source honours its `resolutions`/`overrides` pins on convert (the Bug #99
// override map bridges a pinned, possibly-NON-satisfying descriptor back to its
// node). Without manifests the non-satisfying pin's edge stays dropped, so the
// converted output omits it; with manifests the edge survives the conversion.
//
// DECISION (owner): convert stays a pure parse→stringify — the captured overrides
// are NOT auto-threaded into the stringify `overrides` slot (so the TARGET lock's
// own overrides block is unaffected; only the resolved GRAPH changes).

import { describe, expect, it } from 'vitest'
import { convert, parse, stringify } from '../../main/ts/index.ts'
import type { Manifest } from '../../main/ts/graph.ts'

// root declares csstype `npm:^3.1.3`; the pinned entry key is `csstype@npm:3.0.9`
// (a `resolutions` rewrite). Two csstype entries exist (3.0.9 + 2.6.21) and
// `^3.1.3` is satisfied by NEITHER, so Rung 3 semver has ≥2 candidates and no
// satisfier → DROP. Only the override map (from the manifest) can bridge the
// non-satisfying pin. (A single csstype entry would Rung-3-short-circuit even
// without a manifest, masking the effect — two non-satisfying siblings force the
// drop, exactly the backstage real-world shape.)
const BERRY_LOCK = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10

"csstype@npm:3.0.9":
  version: 3.0.9
  resolution: "csstype@npm:3.0.9"
  checksum: 10/aaaa
  languageName: node
  linkType: hard

"csstype@npm:^2.5.2":
  version: 2.6.21
  resolution: "csstype@npm:2.6.21"
  checksum: 10/bbbb
  languageName: node
  linkType: hard

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    csstype: "npm:^3.1.3"
  languageName: unknown
  linkType: soft
`

const MANIFESTS: Record<string, Manifest> = {
  '': { name: 'root', native: { yarnResolutions: { 'csstype@npm:^3.1.3': '3.0.9' } } },
}

// The importer block (`.:` … up to the next top-level section) is where a root
// dependency surfaces in a pnpm lock. Isolating it avoids matching the orphan
// `packages:` entries (which list every node regardless of reachability, since
// convert is parse→stringify with no optimize).
function importerBlock(out: string): string {
  const start = out.indexOf('importers:')
  const pkgs = out.indexOf('\npackages:', start)
  return out.slice(start, pkgs >= 0 ? pkgs : undefined)
}

describe('#102 — convert() honours a resolutions pin via manifests', () => {
  it('WITHOUT manifests: the non-satisfying pin is dropped → no csstype dependency under the importer', () => {
    const out = convert(BERRY_LOCK, { from: 'yarn-berry-v8', to: 'pnpm-v9' })
    // The root→csstype edge was dropped (no override map, no semver satisfier), so
    // the importer carries no csstype dependency.
    expect(importerBlock(out)).not.toMatch(/csstype/)
  })

  it('WITH manifests: the override map bridges the pin → csstype dependency appears under the importer', () => {
    const out = convert(BERRY_LOCK, { from: 'yarn-berry-v8', to: 'pnpm-v9', manifests: MANIFESTS })
    // The restored edge re-points root onto the pinned csstype 3.0.9 node, so the
    // importer now carries the csstype dependency resolved to 3.0.9.
    const importer = importerBlock(out)
    expect(importer).toMatch(/csstype/)
    expect(importer).toMatch(/3\.0\.9/)
  })

  it('matches the equivalent parse({manifests}) → stringify pipeline (pure parse→stringify)', () => {
    // convert is exactly parse(from, …, { manifests }) → stringify(to, …); no
    // override auto-threading. Prove equality against the manual pipeline.
    const viaConvert = convert(BERRY_LOCK, { from: 'yarn-berry-v8', to: 'pnpm-v9', manifests: MANIFESTS })
    const g = parse('yarn-berry-v8', BERRY_LOCK, { manifests: MANIFESTS })
    const viaPipeline = stringify('pnpm-v9', g)
    expect(viaConvert).toBe(viaPipeline)
  })
})
