import { describe, expect, it, vi } from 'vitest'
import {
  completenessOf,
  enrich,
  evidenceOf,
  frozenRegistry,
  parse,
  stringify,
  type Manifest,
  type PmConfigEvidence,
} from '../../main/ts/index.ts'
import {
  newBuilder,
  type Graph,
  type OverrideConstraint,
} from '../../main/ts/graph.ts'
import {
  attachEvidence,
  deriveEnrichedEvidence,
  withEvidence,
} from '../../main/ts/completeness/evidence.ts'
import type { Packument, PackumentVersion, RegistryAdapter } from '../../main/ts/registry/types.ts'
import type { TarballSource } from '../../main/ts/enrich/refurbish.ts'

const CLASSIC =
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n' +
  '# yarn lockfile v1\n\n\n' +
  'foo@^1.0.0:\n' +
  '  version "1.0.0"\n' +
  '  resolved "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz"\n' +
  '  dependencies:\n' +
  '    bar "^1.0.0"\n'

const emptyRootManifest: Record<string, Manifest> = {
  '': {
    name: 'root',
    version: '1.0.0',
    dependencies: { foo: '^1.0.0' },
    overrides: [],
  },
}

const override: OverrideConstraint = {
  package: 'bar',
  to: '2.0.0',
  origin: 'yarn',
}

const overrideConfig: PmConfigEvidence = {
  kind: 'pm-config',
  manager: 'yarn',
  version: '1.22.22',
  source: 'package.json#resolutions',
  surface: 'overrides',
  coverage: 'complete',
  overrides: [override],
}

interface RegistryHarness {
  readonly adapter: RegistryAdapter
  readonly packumentCalls: Map<string, number>
  readonly resolveCalls: Map<string, number>
  readonly manifestCalls: Map<string, number>
}

function registryHarness(options: Readonly<{
  manifests?: boolean
  conflictBar?: boolean
  manifestConflict?: boolean
  manifestMetadataConflict?: boolean
}> = {}): RegistryHarness {
  const packumentCalls = new Map<string, number>()
  const resolveCalls = new Map<string, number>()
  const manifestCalls = new Map<string, number>()
  const barOne: PackumentVersion = {
    name: 'bar',
    version: '1.5.0',
    ...(options.conflictBar === true ? {} : { dependencies: undefined }),
    engines: { node: '>=18' },
  }
  const packs: Record<string, Packument> = {
    foo: {
      name: 'foo',
      distTags: { latest: '1.0.0' },
      versions: {
        '1.0.0': { name: 'foo', version: '1.0.0', dependencies: { bar: '^1.0.0' } },
      },
    },
    bar: {
      name: 'bar',
      distTags: { latest: '2.0.0' },
      versions: {
        '1.5.0': barOne,
        '2.0.0': { name: 'bar', version: '2.0.0' },
      },
    },
  }
  const count = (map: Map<string, number>, key: string): void => {
    map.set(key, (map.get(key) ?? 0) + 1)
  }
  const adapter: RegistryAdapter = {
    async packument(name) {
      count(packumentCalls, name)
      return packs[name]
    },
    async resolve(name, range) {
      count(resolveCalls, `${name}@${range}`)
      if (name !== 'bar') return undefined
      if (range === '2.0.0') return { name: 'bar', version: '2.0.0' }
      if (range === '^1.0.0') return { name: 'bar', version: '1.5.0' }
      return undefined
    },
    ...(options.manifests !== true ? {} : {
      async manifest(name: string, version: string): Promise<PackumentVersion | undefined> {
        count(manifestCalls, `${name}@${version}`)
        if (name === 'foo' && version === '1.0.0') {
          return { name, version, dependencies: { bar: '^1.0.0' }, license: 'MIT' }
        }
        if (name === 'bar' && (version === '1.5.0' || version === '2.0.0')) {
          return {
            name,
            version,
            ...(options.manifestConflict === true ? { dependencies: { nested: '1.0.0' } } : {}),
            engines: { node: options.manifestMetadataConflict === true ? '>=20' : '>=18' },
            license: 'Apache-2.0',
          }
        }
        return undefined
      },
    }),
  }
  return { adapter, packumentCalls, resolveCalls, manifestCalls }
}

function plainGraph(): Graph {
  const builder = newBuilder()
  builder.addNode({
    id: 'root@1.0.0',
    name: 'root',
    version: '1.0.0',
    peerContext: [],
    workspacePath: '',
  })
  builder.addNode({ id: 'pkg@1.0.0', name: 'pkg', version: '1.0.0', peerContext: [] })
  builder.addEdge('root@1.0.0', 'pkg@1.0.0', 'dep', { range: '1.0.0' })
  return builder.seal()
}

const npmTarget = { target: { format: 'npm-3' as const }, contract: 'snapshot' as const }

describe('target-aware enrich facade', () => {
  it('does not promote a manifest-blind source to an empty override authority', async () => {
    const registry = registryHarness()
    const input = parse('yarn-classic', CLASSIC)
    const result = await enrich(input, { registry: registry.adapter }, npmTarget)

    expect(result.graph.byName('bar')).toEqual([])
    expect(registry.packumentCalls.size).toBe(0)
    expect(registry.resolveCalls.size).toBe(0)
    expect(result.diagnostics.map(item => item.code)).toContain('ENRICH_OVERRIDE_AUTHORITY_UNKNOWN')
  })

  it('accepts a manifest-proven empty override surface', async () => {
    const registry = registryHarness()
    const result = await enrich(parse('yarn-classic', CLASSIC), {
      manifests: emptyRootManifest,
      registry: registry.adapter,
    }, npmTarget)

    expect(result.graph.getNode('bar@1.5.0')).toBeDefined()
    expect(result.graph.getNode('bar@2.0.0')).toBeUndefined()
    expect(registry.resolveCalls.get('bar@^1.0.0')).toBe(1)
  })

  it('honours the only declared override authority during completion', async () => {
    const withoutConfig = registryHarness()
    const skipped = await enrich(parse('yarn-classic', CLASSIC), {
      registry: withoutConfig.adapter,
    }, npmTarget)
    expect(skipped.graph.byName('bar')).toEqual([])

    const withConfig = registryHarness()
    const completed = await enrich(parse('yarn-classic', CLASSIC), {
      registry: withConfig.adapter,
      config: overrideConfig,
    }, npmTarget)
    expect(completed.graph.getNode('bar@2.0.0')).toBeDefined()
    expect(completed.graph.getNode('bar@1.5.0')).toBeUndefined()
    expect(withConfig.resolveCalls.get('bar@2.0.0')).toBe(1)
  })

  it('rejects a config authority from a different source manager', async () => {
    const registry = registryHarness()
    const result = await enrich(parse('yarn-classic', CLASSIC), {
      registry: registry.adapter,
      config: { ...overrideConfig, manager: 'pnpm' },
    }, npmTarget)

    expect(result.graph.byName('bar')).toEqual([])
    expect(registry.packumentCalls.size).toBe(0)
    expect(result.diagnostics.map(item => item.code)).toContain('ENRICH_OVERRIDE_AUTHORITY_CONFLICT')
  })

  it('hydrates the final completion closure from exact version manifests', async () => {
    const registry = registryHarness({ manifests: true })
    const result = await enrich(parse('yarn-classic', CLASSIC), {
      manifests: emptyRootManifest,
      registry: registry.adapter,
    }, { target: { format: 'npm-3' }, contract: 'project' })

    expect(result.graph.getNode('bar@1.5.0')).toBeDefined()
    expect(result.graph.tarballOf('bar@1.5.0')?.license).toBe('Apache-2.0')
    expect(evidenceOf(result.graph).ledger.refs).toContainEqual({
      kind: 'version-manifest',
      subject: 'bar@1.5.0',
    })
    expect(registry.manifestCalls.get('bar@1.5.0')).toBe(1)
    expect(completenessOf(result.graph).diagnostics.map(item => item.code))
      .not.toContain('COMPLETENESS_EVIDENCE_SCOPE_MISMATCH')
  })

  it('does not promote packument-only completion to package metadata authority', async () => {
    const registry = registryHarness()
    const result = await enrich(parse('yarn-classic', CLASSIC), {
      manifests: emptyRootManifest,
      registry: registry.adapter,
    }, { target: { format: 'npm-3' }, contract: 'project' })

    expect(result.graph.getNode('bar@1.5.0')).toBeDefined()
    expect(evidenceOf(result.graph).ledger.refs.some(ref =>
      ref.kind === 'version-manifest' || ref.kind === 'full-packument')).toBe(false)
    expect(completenessOf(result.graph).profile.packageMetadata).not.toBe('complete')
  })

  it('rolls back registry completion when it conflicts with package evidence', async () => {
    const input = parse('yarn-classic', CLASSIC)
    const authority = withEvidence(evidenceOf(input), {
      kind: 'package-manifests',
      authority: 'version-manifest',
      manifests: {
        'bar@1.5.0': {
          name: 'bar',
          version: '1.5.0',
          dependencies: { nested: '1.0.0' },
        },
      },
    })
    attachEvidence(input, authority)
    const registry = registryHarness({ conflictBar: true })
    const result = await enrich(input, {
      manifests: emptyRootManifest,
      registry: registry.adapter,
    }, npmTarget)

    expect(result.graph.byName('bar')).toEqual([])
    expect(result.diagnostics.map(item => item.code)).toContain('COMPLETENESS_EVIDENCE_CONFLICT')
    expect(result.diagnostics.map(item => item.code)).not.toContain('COMPLETION_NODE_ADDED')
    expect(evidenceOf(result.graph).ledger.diagnostics.map(item => item.code))
      .toContain('COMPLETENESS_EVIDENCE_CONFLICT')
  })

  it('rolls back registry completion when exact and abbreviated registry facts conflict', async () => {
    const registry = registryHarness({ manifests: true, manifestConflict: true })
    const result = await enrich(parse('yarn-classic', CLASSIC), {
      manifests: emptyRootManifest,
      registry: registry.adapter,
    }, { target: { format: 'npm-3' }, contract: 'project' })

    expect(result.graph.byName('bar')).toEqual([])
    expect(result.diagnostics).toContainEqual(expect.objectContaining({
      code: 'COMPLETENESS_EVIDENCE_CONFLICT',
      subject: 'bar@1.5.0',
      data: expect.objectContaining({
        dimension: 'resolvedGraph',
        sources: ['abbreviated-packument', 'version-manifest'],
      }),
    }))
    expect(evidenceOf(result.graph).ledger.diagnostics)
      .toContainEqual(expect.objectContaining({
        code: 'COMPLETENESS_EVIDENCE_CONFLICT',
        subject: 'bar@1.5.0',
      }))
  })

  it('rolls back registry completion when exact and abbreviated metadata conflict', async () => {
    const registry = registryHarness({ manifests: true, manifestMetadataConflict: true })
    const result = await enrich(parse('yarn-classic', CLASSIC), {
      manifests: emptyRootManifest,
      registry: registry.adapter,
    }, { target: { format: 'npm-3' }, contract: 'project' })

    expect(result.graph.byName('bar')).toEqual([])
    expect(result.diagnostics).toContainEqual(expect.objectContaining({
      code: 'COMPLETENESS_EVIDENCE_CONFLICT',
      subject: 'bar@1.5.0',
    }))
  })

  it('rejects an exact registry manifest with a mismatched subject identity', async () => {
    const registry: RegistryAdapter = {
      async packument() { return undefined },
      async resolve() { return undefined },
      async manifest(_name, version) { return { name: 'other', version } },
    }
    const result = await enrich(plainGraph(), { registry }, {
      target: { format: 'npm-3' },
      contract: 'project',
    })

    expect(result.diagnostics).toContainEqual(expect.objectContaining({
      code: 'COMPLETENESS_EVIDENCE_CONFLICT',
      subject: 'pkg@1.0.0',
      data: expect.objectContaining({ sources: ['graph-subject', 'version-manifest'] }),
    }))
    expect(evidenceOf(result.graph).ledger.refs)
      .not.toContainEqual(expect.objectContaining({ kind: 'version-manifest' }))
  })

  it('memoizes every registry operation by key within one call', async () => {
    const registry = registryHarness({ manifests: true })
    await enrich(parse('yarn-classic', CLASSIC), {
      manifests: emptyRootManifest,
      registry: registry.adapter,
    }, { target: { format: 'npm-3' }, contract: 'project' })

    expect([...registry.packumentCalls.values()].every(count => count === 1)).toBe(true)
    expect([...registry.resolveCalls.values()].every(count => count === 1)).toBe(true)
    expect([...registry.manifestCalls.values()].every(count => count === 1)).toBe(true)
  })

  it('is deterministic across repeated runs with a frozen registry', async () => {
    const registryBuilder = newBuilder()
    registryBuilder.addNode({ id: 'foo@1.0.0', name: 'foo', version: '1.0.0', peerContext: [] })
    registryBuilder.addNode({ id: 'bar@1.5.0', name: 'bar', version: '1.5.0', peerContext: [] })
    registryBuilder.addEdge('foo@1.0.0', 'bar@1.5.0', 'dep', { range: '^1.0.0' })
    const registry = frozenRegistry(registryBuilder.seal())
    const input = parse('yarn-classic', CLASSIC)
    const sources = { manifests: emptyRootManifest, registry }

    const first = await enrich(input, sources, npmTarget)
    const second = await enrich(input, sources, npmTarget)

    const pinnedGeneratedAt = '2026-01-01T00:00:00Z'
    const pinGeneratedAt = (output: string): string => output.replace(
      /^generatedAt [^\r\n]+$/m,
      `generatedAt ${pinnedGeneratedAt}`,
    )
    vi.useFakeTimers()
    try {
      vi.setSystemTime(new Date('2026-01-01T00:00:00.999Z'))
      const firstOutput = stringify('lockgraph', first.graph, { strict: false })
      vi.setSystemTime(new Date('2026-01-01T00:00:01.001Z'))
      const secondOutput = stringify('lockgraph', second.graph, { strict: false })

      expect(firstOutput).toContain('generatedAt 2026-01-01T00:00:00Z')
      expect(secondOutput).toContain('generatedAt 2026-01-01T00:00:01Z')
      expect(pinGeneratedAt(secondOutput)).toBe(pinGeneratedAt(firstOutput))
    } finally {
      vi.useRealTimers()
    }
    expect(second.diagnostics).toEqual(first.diagnostics)
  })

  it('returns an evidence-distinct graph without changing the input context', async () => {
    const input = plainGraph()
    const before = evidenceOf(input)
    const result = await enrich(input, {
      manifests: { '': { overrides: [] } },
    }, npmTarget)

    expect(result.graph).not.toBe(input)
    expect(evidenceOf(input)).toBe(before)
    expect(evidenceOf(input).ledger.refs).toEqual([])
    expect(evidenceOf(result.graph).ledger.refs).toContainEqual({
      kind: 'repository-manifest',
      subject: '',
      coverage: 'partial',
    })
  })

  it('preserves graph identity on a true no-op', async () => {
    const input = plainGraph()
    const result = await enrich(input, {}, npmTarget)
    expect(result.graph).toBe(input)
    expect(result.diagnostics).toEqual([])
  })

  it('never infers the Berry 10c0 cache key in the facade', async () => {
    const input = plainGraph()
    let oracleCalls = 0
    const artifacts: TarballSource = {
      async tarball() { return undefined },
      async berryChecksum() {
        oracleCalls++
        return 'a'.repeat(128)
      },
    }
    const deferred = await enrich(input, { artifacts }, {
      target: { format: 'yarn-berry-v8' },
      contract: 'snapshot',
    })
    expect(oracleCalls).toBe(0)
    expect(deferred.diagnostics.map(item => item.code)).toContain('ENRICH_CHECKSUM_DEFERRED')

    const filled = await enrich(input, { artifacts }, {
      target: { format: 'yarn-berry-v8' },
      contract: 'snapshot',
      cacheKey: '10c0',
    })
    expect(oracleCalls).toBe(1)
    expect(filled.graph.tarballOf('pkg@1.0.0')?.integrity?.hashes)
      .toContainEqual(expect.objectContaining({ origin: 'berry-zip', digest: 'a'.repeat(128) }))
  })

  it('keeps lock-v8 conditioned checksum completion independent of target Yarn version', async () => {
    const input = parse('yarn-berry-v8', `__metadata:
  version: 8
  cacheKey: 10c0

"fixture@workspace:.":
  version: 0.0.0-use.local
  resolution: "fixture@workspace:."
  dependencies:
    fsevents: "npm:2.3.3"
  languageName: unknown
  linkType: soft

"fsevents@npm:2.3.3":
  version: 2.3.3
  resolution: "fsevents@npm:2.3.3"
  conditions: os=darwin
  languageName: node
  linkType: hard
`)
    const artifacts: TarballSource = {
      async tarball() { return undefined },
      async berryChecksum() { return 'c'.repeat(128) },
    }

    const olderTarget = await enrich(input, { artifacts }, {
      target: { format: 'yarn-berry-v8', managerVersion: '4.3.1' },
      contract: 'snapshot',
      cacheKey: '10c0',
    })
    const newerTarget = await enrich(input, { artifacts }, {
      target: { format: 'yarn-berry-v8', managerVersion: '4.4.0' },
      contract: 'snapshot',
      cacheKey: '10c0',
    })

    expect(olderTarget.graph.tarballOf('fsevents@2.3.3')?.integrity?.hashes)
      .toContainEqual(expect.objectContaining({ origin: 'berry-zip', digest: 'c'.repeat(128) }))
    expect(newerTarget.graph.tarballOf('fsevents@2.3.3')?.integrity?.hashes)
      .toContainEqual(expect.objectContaining({ origin: 'berry-zip', digest: 'c'.repeat(128) }))
  })

  it('uses one observed Berry cache key and rejects ambiguous observations', async () => {
    const artifacts: TarballSource = {
      async tarball() { return undefined },
      async berryChecksum() { return 'b'.repeat(128) },
    }
    const observed = plainGraph().mutate(mutator => {
      mutator.setTarball({ name: 'pkg', version: '1.0.0' }, { berryChecksumCacheKey: '8' })
    }).graph
    const filled = await enrich(observed, { artifacts }, {
      target: { format: 'yarn-berry-v8' },
      contract: 'snapshot',
    })
    expect(filled.graph.tarballOf('pkg@1.0.0')?.integrity?.hashes)
      .toContainEqual(expect.objectContaining({ origin: 'berry-zip', digest: 'b'.repeat(128) }))
    expect(evidenceOf(filled.graph).ledger.refs).toContainEqual({
      kind: 'inference',
      subject: 'berry-cache-key:8',
      source: 'graph-observation',
    })

    const ambiguousBuilder = newBuilder()
    ambiguousBuilder.addNode({ id: 'left@1.0.0', name: 'left', version: '1.0.0', peerContext: [] })
    ambiguousBuilder.addNode({ id: 'right@1.0.0', name: 'right', version: '1.0.0', peerContext: [] })
    ambiguousBuilder.setTarball({ name: 'left', version: '1.0.0' }, { berryChecksumCacheKey: '8' })
    ambiguousBuilder.setTarball({ name: 'right', version: '1.0.0' }, { berryChecksumCacheKey: '9' })
    const ambiguous = await enrich(ambiguousBuilder.seal(), { artifacts }, {
      target: { format: 'yarn-berry-v8' },
      contract: 'snapshot',
    })
    expect(ambiguous.graph.tarballOf('left@1.0.0')?.integrity).toBeUndefined()
    expect(ambiguous.graph.tarballOf('right@1.0.0')?.integrity).toBeUndefined()
    expect(ambiguous.diagnostics.filter(item => item.code === 'ENRICH_CHECKSUM_DEFERRED'))
      .toHaveLength(2)
  })

  it('rejects uncovered and incomplete derivation receipts', () => {
    const input = plainGraph()
    const after = input.mutate(mutator => {
      mutator.addNode({ id: 'extra@1.0.0', name: 'extra', version: '1.0.0', peerContext: [] })
      mutator.setTarball({ name: 'extra', version: '1.0.0' }, {})
      mutator.addEdge('pkg@1.0.0', 'extra@1.0.0', 'dep', { range: '1.0.0' })
    }).graph

    expect(() => deriveEnrichedEvidence(input, after, evidenceOf(input), []))
      .toThrowError(/final graph contains an uncovered delta/)
    expect(() => deriveEnrichedEvidence(input, after, evidenceOf(input), [{
      kind: 'completion',
      before: input,
      after,
      added: [],
      wired: [],
    }])).toThrowError(/completion node receipt is incomplete/)
  })

  it('includes edge attributes in the canonical derivation boundary', () => {
    const input = plainGraph()
    const after = input.mutate(mutator => {
      mutator.removeEdge('root@1.0.0', 'pkg@1.0.0', 'dep')
      mutator.addEdge('root@1.0.0', 'pkg@1.0.0', 'dep', { range: '^1.0.0' })
    }).graph

    expect(() => deriveEnrichedEvidence(input, after, evidenceOf(input), []))
      .toThrowError(/final graph contains an uncovered delta/)
  })
})
