// yaf lockgraph-message (2026-06-20) — end-to-end regression for the COMPOSED
// fix. yaf's own suite never exercised this: their goldens only bump dep-less
// packages and assert parse-validity offline, never a dependency-CHANGING
// upgrade through the full modify → complete → stringify pipeline. This test
// reproduces the reported scenario (handlebars 4.0.0 → 4.7.9, whose dependency
// SET differs) and pins all three behaviours at once:
//
//   bug 1  — the bumped node sheds the OLD version's outgoing deps (async,
//            optimist) instead of merging them onto the new set.
//   bug 2  — freshly-added dep edges emit with the `npm:` protocol, not a bare
//            range that yarn would read as the (resolver-less) `semver:` proto.
//   reuse  — a new transitive whose range is already met by a version present
//            in the lock (source-map 0.6.1) binds to it, not a registry fetch.

import { describe, expect, it } from 'vitest'
import { parse, stringify } from '../../main/ts/index.ts'
import { replaceVersion } from '../../main/ts/modify/replace-version.ts'
import { completeTransitives } from '../../main/ts/complete/tree-complete.ts'
import { pruneOrphans } from '../../main/ts/optimize/prune.ts'
import type { Packument, RegistryAdapter } from '../../main/ts/registry/types.ts'

const CK = '10c0/d924b57e7312b3b63ad21fc5b3dc0af5e78d61a1fc7cfb5457edaf26326bf62be5307cc87ffb6862ef1c2b33b0233cdb5d4f01c4c958cc0d660948b65a287a48'

// A yarn-berry lock where handlebars@4.0.0 carries its 4.0.0-era deps, and a
// SEPARATE branch (somelib) already pins source-map@0.6.1 — find-up from
// handlebars can't see it, so only project-wide reuse will.
const LOCK = `# This file is generated by running "yarn install" inside your project.
# Manually changing this file will cause non-deterministic behavior.

__metadata:
  version: 8
  cacheKey: 10c0

"app@workspace:.":
  version: 0.0.0-use.local
  resolution: "app@workspace:."
  dependencies:
    handlebars: "npm:4.0.0"
    somelib: "npm:1.0.0"
  languageName: unknown
  linkType: soft

"handlebars@npm:4.0.0":
  version: 4.0.0
  resolution: "handlebars@npm:4.0.0"
  dependencies:
    async: "npm:^1.4.0"
    optimist: "npm:^0.6.1"
  checksum: ${CK}
  languageName: node
  linkType: hard

"async@npm:1.4.2":
  version: 1.4.2
  resolution: "async@npm:1.4.2"
  checksum: ${CK}
  languageName: node
  linkType: hard

"optimist@npm:0.6.1":
  version: 0.6.1
  resolution: "optimist@npm:0.6.1"
  checksum: ${CK}
  languageName: node
  linkType: hard

"somelib@npm:1.0.0":
  version: 1.0.0
  resolution: "somelib@npm:1.0.0"
  dependencies:
    source-map: "npm:^0.6.0"
  checksum: ${CK}
  languageName: node
  linkType: hard

"source-map@npm:0.6.1":
  version: 0.6.1
  resolution: "source-map@npm:0.6.1"
  checksum: ${CK}
  languageName: node
  linkType: hard
`

// handlebars@4.7.9 declares a DIFFERENT dep set than 4.0.0. minimist / neo-async
// / wordwrap are new (registry-fetched); source-map ^0.6.0 is satisfied by the
// 0.6.1 already in the lock (reused). resolve() returns source-map@0.7.0 as a
// tripwire: a reuse miss would surface 0.7.0.
const HANDLEBARS: Packument = {
  name: 'handlebars',
  distTags: { latest: '4.7.9' },
  versions: {
    '4.0.0': { name: 'handlebars', version: '4.0.0', dependencies: { async: '^1.4.0', optimist: '^0.6.1' } },
    '4.7.9': { name: 'handlebars', version: '4.7.9', dependencies: { minimist: '^1.2.5', 'neo-async': '^2.6.2', 'source-map': '^0.6.0', wordwrap: '^1.0.0' }, optionalDependencies: { 'uglify-js': '^3.1.4' } },
  },
}
const NODEPS = (name: string, version: string): Packument => ({
  name, distTags: { latest: version }, versions: { [version]: { name, version } },
})
const PKGS: Record<string, Packument> = {
  handlebars:  HANDLEBARS,
  minimist:    NODEPS('minimist', '1.2.8'),
  'neo-async': NODEPS('neo-async', '2.6.2'),
  wordwrap:    NODEPS('wordwrap', '1.0.0'),
  'uglify-js':  NODEPS('uglify-js', '3.17.4'),
  'source-map': { name: 'source-map', distTags: { latest: '0.7.0' }, versions: { '0.6.1': { name: 'source-map', version: '0.6.1' }, '0.7.0': { name: 'source-map', version: '0.7.0' } } },
}
const registry: RegistryAdapter = {
  async packument(name) { return PKGS[name] },
  async resolve(name, range) {
    if (name === 'handlebars' && range === '4.7.9') return { name, version: '4.7.9' }
    if (name === 'minimist')   return { name, version: '1.2.8' }
    if (name === 'neo-async')  return { name, version: '2.6.2' }
    if (name === 'wordwrap')   return { name, version: '1.0.0' }
    if (name === 'uglify-js')  return { name, version: '3.17.4' }
    if (name === 'source-map') return { name, version: '0.7.0' }  // tripwire — reuse must beat this
    return undefined
  },
}

describe('lockgraph-message e2e — dependency-changing berry upgrade', () => {
  it('bump + complete yields a node with the NEW dep set, npm: protocol, and reuse', async () => {
    const g0 = parse('yarn-berry-v8', LOCK)
    expect(g0.getNode('handlebars@4.0.0')).toBeDefined()

    const bumped = await replaceVersion(
      g0, { name: 'handlebars', fromRange: '4.0.0' }, '4.7.9', { registry },
    )
    expect(bumped.replaced).toEqual([{ from: 'handlebars@4.0.0', to: 'handlebars@4.7.9' }])
    // bug 1 — straight after the bump the node carries NO stale out-deps.
    expect([...bumped.graph.out('handlebars@4.7.9')].filter(e => e.kind === 'dep')).toEqual([])

    const completed = await completeTransitives(bumped.graph, registry, {
      seed: { recentlyAdded: bumped.recentlyAdded, recentlyOrphaned: bumped.recentlyOrphaned },
    })

    // The completed node's dep targets == handlebars@4.7.9's declared set.
    const deps = [...completed.graph.out('handlebars@4.7.9')]
      .filter(e => e.kind === 'dep')
      .map(e => e.dst)
      .sort()
    expect(deps).toEqual([
      'minimist@1.2.8', 'neo-async@2.6.2', 'source-map@0.6.1', 'wordwrap@1.0.0',
    ])
    // reuse — the existing 0.6.1 served ^0.6.0; the 0.7.0 tripwire never fired.
    expect(completed.graph.getNode('source-map@0.6.1')).toBeDefined()
    expect(completed.graph.getNode('source-map@0.7.0')).toBeUndefined()
    // bug 1 — async / optimist no longer hang off handlebars.
    expect(deps).not.toContain('async@1.4.2')
    expect(deps).not.toContain('optimist@0.6.1')

    // bug 2 — emit: every fresh edge carries npm:, never the bare semver: form.
    const out = stringify('yarn-berry-v8', completed.graph)
    expect(out).toContain('minimist: "npm:^1.2.5"')
    expect(out).toContain('neo-async: "npm:^2.6.2"')
    expect(out).toContain('wordwrap: "npm:^1.0.0"')
    expect(out).not.toMatch(/minimist: \^1\.2\.5/)   // not the bare (semver:) form
    expect(out).not.toMatch(/wordwrap: \^1\.0\.0/)
  })

  it('.69 flow — optional dep folds into dependencies + dependenciesMeta; prune retires the stranded closure', async () => {
    const g0 = parse('yarn-berry-v8', LOCK)
    const bumped = await replaceVersion(
      g0, { name: 'handlebars', fromRange: '4.0.0' }, '4.7.9', { registry },
    )
    const completed = await completeTransitives(bumped.graph, registry, {
      seed: { recentlyAdded: bumped.recentlyAdded, recentlyOrphaned: bumped.recentlyOrphaned },
    })

    // .69 issue 1 (model) — handlebars' optionalDependency wires as an OPTIONAL edge.
    const optTargets = [...completed.graph.out('handlebars@4.7.9')]
      .filter(e => e.kind === 'optional').map(e => e.dst)
    expect(optTargets).toEqual(['uglify-js@3.17.4'])

    // .69 issue 2 — the bump is a REBIND (removes no node), so the stranded 4.0.0
    // closure (async / optimist) surfaces via recentlyOrphaned, NOT res.removed.
    expect([...bumped.recentlyOrphaned].sort()).toEqual(['async@1.4.2', 'optimist@0.6.1'])
    // additive completion leaves them in place; a SEEDED pruneOrphans (yaf's real
    // flow) retires exactly that delta and nothing else.
    expect(completed.graph.getNode('async@1.4.2')).toBeDefined()
    expect(completed.graph.getNode('optimist@0.6.1')).toBeDefined()
    const pruned = pruneOrphans(completed.graph, { seed: bumped.recentlyOrphaned })
    expect([...pruned.removed].sort()).toEqual(['async@1.4.2', 'optimist@0.6.1'])
    expect(pruned.graph.getNode('handlebars@4.7.9')).toBeDefined()    // live node kept
    expect(pruned.graph.getNode('uglify-js@3.17.4')).toBeDefined()    // optional dep kept

    // .69 issue 1 (emit) — optional folds into `dependencies` + dependenciesMeta,
    // never a separate optionalDependencies block (yarn rejects one, YN0028).
    const out = stringify('yarn-berry-v8', pruned.graph)
    expect(out).not.toContain('optionalDependencies:')
    expect(out).toContain('uglify-js: "npm:^3.1.4"')
    expect(out).toMatch(/dependenciesMeta:\n\s+uglify-js:\n\s+optional: true/)
  })
})
