import { describe, expect, it } from 'vitest'
import { parse, stringify } from '../../main/ts/index.ts'

// Regression for Bug #76 — a `file:` local-tarball alias and a registry entry
// at the SAME name@version must NOT collapse onto one NodeId. Yarn records a
// `locator=<consumer>` qualifier on the `file:` resolution's `::`-param block
// (the entry key uses the bare `::locator=` form). That qualifier carries a
// consumer-ownership discriminator, so the entry takes the same sentinel-patch
// slot (`+patch=unresolved-…`) as `link:` / `portal:` and stays distinct from
// the sibling `demo@npm:1.0.0`. They are genuinely different artefacts here:
// different checksums and different `left-pad` dep ranges (`^1.0.0` vs `^2.0.0`).

// Yarn-berry `checksum` bodies are 128-hex sha512 of the zip cache. Build them
// from repeated nibbles so they are guaranteed-valid (HEX128_RE) yet visibly
// distinct between the two same-version entries.
const SUM = (nibble: string): string => `10c0/${nibble.repeat(128)}`

const LOCK = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"demo@file:.lib/demo.tgz::locator=root%40workspace%3A.":
  version: 1.0.0
  resolution: "demo@file:.lib/demo.tgz#.lib/demo.tgz::hash=abc123&locator=root%40workspace%3A."
  dependencies:
    left-pad: "npm:^1.0.0"
  checksum: ${SUM('a')}
  languageName: node
  linkType: hard

"demo@npm:^1.0.0":
  version: 1.0.0
  resolution: "demo@npm:1.0.0"
  dependencies:
    left-pad: "npm:^2.0.0"
  checksum: ${SUM('b')}
  languageName: node
  linkType: hard

"left-pad@npm:^1.0.0, left-pad@npm:^2.0.0":
  version: 2.1.0
  resolution: "left-pad@npm:2.1.0"
  checksum: ${SUM('c')}
  languageName: node
  linkType: hard
`

describe('yarn-berry file: local-tarball alias disambiguation (Bug #76)', () => {
  it('keeps a `file:` alias distinct from a same-version `npm:` entry', () => {
    const g = parse('yarn-berry-v8', LOCK)
    const demos = Array.from(g.nodes()).filter(n => n.name === 'demo' && n.version === '1.0.0')
    expect(demos.length).toBe(2)

    const patched = demos.filter(n => n.patch?.startsWith('unresolved-'))
    const unpatched = demos.filter(n => n.patch === undefined)
    expect(patched.length).toBe(1)
    expect(unpatched.length).toBe(1)

    // The `file:` alias round-trips its verbatim locator (incl. `locator=`);
    // the registry entry keeps a plain `npm:` resolution.
    expect(g.tarballOf(patched[0]!.id)?.nativeResolution).toBe(
      'demo@file:.lib/demo.tgz#.lib/demo.tgz::hash=abc123&locator=root%40workspace%3A.')
    expect(g.tarballOf(unpatched[0]!.id)?.nativeResolution).toBe('demo@npm:1.0.0')

    // Distinct TarballKeys: the two checksums land on separate payloads keyed
    // off the sentinel patch, so the differing integrity no longer fights over
    // a shared key (the IRREDUCIBLE_LOSS that Bug #76 threw).
    const aliasInt = g.tarballOf(patched[0]!.id)?.integrity
    const npmInt = g.tarballOf(unpatched[0]!.id)?.integrity
    expect(aliasInt?.hashes[0]?.digest).toBe('a'.repeat(128))
    expect(npmInt?.hashes[0]?.digest).toBe('b'.repeat(128))
  })

  it('round-trips: stringify → reparse yields the same two distinct nodes', () => {
    const g = parse('yarn-berry-v8', LOCK)
    const out = stringify('yarn-berry-v8', g)
    const g2 = parse('yarn-berry-v8', out)
    const demos = Array.from(g2.nodes()).filter(n => n.name === 'demo' && n.version === '1.0.0')
    expect(demos.length).toBe(2)
    expect(demos.filter(n => n.patch?.startsWith('unresolved-')).length).toBe(1)
    expect(demos.filter(n => n.patch === undefined).length).toBe(1)
    // The `file:` locator survived the round-trip byte-faithfully.
    const reAlias = demos.find(n => n.patch?.startsWith('unresolved-'))
    expect(g2.tarballOf(reAlias!.id)?.nativeResolution).toBe(
      'demo@file:.lib/demo.tgz#.lib/demo.tgz::hash=abc123&locator=root%40workspace%3A.')
  })

  it('does NOT patch a plain `file:` directory link (no consumer `locator=`)', () => {
    // A bare `file:../pkg` directory link with no `locator=` qualifier is
    // already a unique node — it must stay unpatched (the gate is the
    // consumer-ownership qualifier, not the `file:` protocol alone).
    const PLAIN = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"plain@file:../plain::locator=root%40workspace%3A.":
  version: 1.0.0
  resolution: "plain@file:../plain"
  languageName: node
  linkType: soft
`
    const g = parse('yarn-berry-v8', PLAIN)
    const node = Array.from(g.nodes()).find(n => n.name === 'plain')
    expect(node).toBeDefined()
    expect(node!.patch).toBeUndefined()
    expect(g.tarballOf(node!.id)?.nativeResolution).toBe('plain@file:../plain')
  })
})
