import { describe, expect, it } from 'vitest'
import { detect, parse, stringify } from '../../main/ts/index.ts'
import { LockfileError } from '../../main/ts/errors.ts'

// Robustness gaps from the yarn-audit-fix real-world sweep (snapshot.49).
// Minimal repros only — no external fixtures.

const ANSI_SRI = 'sha512-zbB9rCJAt1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg=='

describe('yarn-classic robustness — git-protocol resolved URLs', () => {
  it('a git+ssh resolved URL parses (modelled as a git resolution), not a whole-file abort', () => {
    const lf =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      'from-git@git+ssh://git@github.com/example/from-git.git:\n' +
      '  version "0.0.0"\n' +
      '  resolved "git+ssh://git@github.com/example/from-git.git#0123456789abcdef0123456789abcdef01234567"\n'
    const g = parse('yarn-classic', lf)
    expect(g.getNode('from-git@0.0.0')).toBeDefined()
    expect(g.getNode('from-git@0.0.0')?.resolution).toBe('git+ssh://git@github.com/example/from-git.git#0123456789abcdef0123456789abcdef01234567')
    expect(g.tarballOf('from-git@0.0.0')?.resolution?.type).toBe('git')
  })

  it('git:// and scp-like git@ forms also parse', () => {
    const lf =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      '"ws@git://github.com/frozeman/WebSocket-Node.git":\n' +
      '  version "1.0.0"\n' +
      '  resolved "git://github.com/frozeman/WebSocket-Node.git#deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"\n'
    const g = parse('yarn-classic', lf)
    expect(g.getNode('ws@1.0.0')?.resolution).toMatch(/^git:\/\//)
    expect(g.tarballOf('ws@1.0.0')?.resolution?.type).toBe('git')
  })

  // F2 (snapshot.50 round-trip sweep): the git `resolved` line must SURVIVE
  // emit. snapshot.50 made git deps parse, but stringify re-emitted the entry
  // WITHOUT its `resolved "git+ssh://…#sha"` line — a lockfile `yarn install
  // --immutable` rejects. `formatResolution` now round-trips any URL shape
  // `parseResolution` accepts (the verbatim Node.resolution path).
  it('a git+ssh resolved line round-trips on emit (F2)', () => {
    const lf =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      'from-git@git+ssh://git@github.com/example/from-git.git:\n' +
      '  version "0.0.0"\n' +
      '  resolved "git+ssh://git@github.com/example/from-git.git#abc123"\n'
    const out = stringify('yarn-classic', parse('yarn-classic', lf))
    expect(out).toContain('resolved "git+ssh://git@github.com/example/from-git.git#abc123"')
  })

  it('a git+ssh resolved line with a 40-hex sha round-trips on emit (F2)', () => {
    const lf =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      'from-git@git+ssh://git@github.com/example/from-git.git:\n' +
      '  version "0.0.0"\n' +
      '  resolved "git+ssh://git@github.com/example/from-git.git#0123456789abcdef0123456789abcdef01234567"\n'
    const out = stringify('yarn-classic', parse('yarn-classic', lf))
    expect(out).toContain('resolved "git+ssh://git@github.com/example/from-git.git#0123456789abcdef0123456789abcdef01234567"')
  })

  it('git:// and scp-like git@ resolved lines also round-trip on emit (F2)', () => {
    const gitProto =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      '"ws@git://github.com/frozeman/WebSocket-Node.git":\n' +
      '  version "1.0.0"\n' +
      '  resolved "git://github.com/frozeman/WebSocket-Node.git#deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"\n'
    expect(stringify('yarn-classic', parse('yarn-classic', gitProto)))
      .toContain('resolved "git://github.com/frozeman/WebSocket-Node.git#deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"')

    const scp =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      '"from-git@git@github.com:example/from-git.git":\n' +
      '  version "0.0.0"\n' +
      '  resolved "git@github.com:example/from-git.git#0123456789abcdef0123456789abcdef01234567"\n'
    expect(stringify('yarn-classic', parse('yarn-classic', scp)))
      .toContain('resolved "git@github.com:example/from-git.git#0123456789abcdef0123456789abcdef01234567"')
  })
})

describe('yarn-classic robustness — duplicate descriptors that should merge', () => {
  const dupBlocks = (resolvedA: string, resolvedB: string, integA = ANSI_SRI, integB = ANSI_SRI): string =>
    '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
    'ansi-styles@^4.0.0:\n' +
    '  version "4.3.0"\n' +
    `  resolved "${resolvedA}"\n` +
    `  integrity ${integA}\n\n` +
    'ansi-styles@^4.1.0:\n' +
    '  version "4.3.0"\n' +
    `  resolved "${resolvedB}"\n` +
    `  integrity ${integB}\n`

  const REG = 'https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz'

  it('two blocks resolving to the same name@version with identical resolution merge into one node', () => {
    const g = parse('yarn-classic', dupBlocks(REG, REG))
    expect(g.byName('ansi-styles')).toHaveLength(1)
    expect(g.getNode('ansi-styles@4.3.0')).toBeDefined()
  })

  it('the merged node re-emits BOTH descriptor keys on one entry', () => {
    const out = stringify('yarn-classic', parse('yarn-classic', dupBlocks(REG, REG)))
    expect(out).toContain('ansi-styles@^4.0.0')
    expect(out).toContain('ansi-styles@^4.1.0')
    // one entry block, not two: the version line appears once.
    expect(out.match(/version "4\.3\.0"/g)).toHaveLength(1)
  })

  it('a GENUINE conflict (same name@version, differing resolution) still throws IRREDUCIBLE_LOSS', () => {
    const conflict = dupBlocks(REG, 'https://example.com/other-ansi-styles-4.3.0.tgz')
    expect(() => parse('yarn-classic', conflict)).toThrow(/collapse onto NodeId ansi-styles@4\.3\.0/)
  })
})

describe('yarn-classic robustness — entry immediately after the header', () => {
  it('an entry on the line right after `# yarn lockfile v1` parses (old yarn / lodash)', () => {
    const lf =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n' +
      '# yarn lockfile v1\n' +
      'abbrev@1, abbrev@1.0.x:\n' +
      '  version "1.0.9"\n' +
      '  resolved "https://registry.yarnpkg.com/abbrev/-/abbrev-1.0.9.tgz#91b4792588a7738c25f35dd6f63752a2f8776135"\n'
    const g = parse('yarn-classic', lf)
    expect(g.getNode('abbrev@1.0.9')).toBeDefined()
  })
})

const H =
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n'

// #83 finding 1 — relative file:/link:/portal: in `resolved`. GENUINE: yarn 1
// writes `resolved: remote.resolved` verbatim for copy/link references, so a
// local dep's `resolved` is the bare specifier (no `://`). The scheme-only
// resolvable-URL predicate rejected it → whole-file parse abort. Now accepted,
// canonicalised to a `directory` resolution, and re-emitted verbatim (the
// link/portal/file distinction survives the round-trip — a `directory`
// canonical alone would flatten all three to `file:`).
describe('yarn-classic robustness — relative file:/link:/portal: resolved', () => {
  const localBlock = (protocol: 'file' | 'link' | 'portal', spec: string, version = '0.0.0'): string =>
    H +
    `"my-lib@${protocol}:${spec}":\n` +
    `  version "${version}"\n` +
    `  resolved "${protocol}:${spec}"\n`

  for (const protocol of ['file', 'link', 'portal'] as const) {
    it(`${protocol}: relative resolved parses (directory canonical), does not abort`, () => {
      const g = parse('yarn-classic', localBlock(protocol, '../my-lib'))
      const node = g.getNode('my-lib@0.0.0')
      expect(node).toBeDefined()
      expect(node?.resolution).toBe(`${protocol}:../my-lib`)
      expect(g.tarballOf('my-lib@0.0.0')?.resolution).toEqual({ type: 'directory', path: '../my-lib' })
      // A recognised local specifier is NOT an unknown resolution.
      expect(g.diagnostics().some(d => d.code === 'RECIPE_RESOLUTION_UNKNOWN')).toBe(false)
    })

    it(`${protocol}: relative resolved round-trips verbatim`, () => {
      const out = stringify('yarn-classic', parse('yarn-classic', localBlock(protocol, '../my-lib')))
      expect(out).toContain(`resolved "${protocol}:../my-lib"`)
      // Idempotent.
      expect(stringify('yarn-classic', parse('yarn-classic', out))).toBe(out)
    })
  }

  it('a file: dep with a dependencies block + version round-trips', () => {
    const lf =
      H +
      '"@scope/local@file:./packages/local":\n' +
      '  version "2.3.4"\n' +
      '  resolved "file:./packages/local"\n' +
      '  dependencies:\n' +
      '    lodash "^4.17.21"\n\n' +
      'lodash@^4.17.21:\n' +
      '  version "4.17.21"\n' +
      '  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffaae8454cf0b3df370c3d6911c"\n'
    const g = parse('yarn-classic', lf)
    expect(g.getNode('@scope/local@2.3.4')?.resolution).toBe('file:./packages/local')
    // the file: dep's dependency edge resolves to the registry lodash node.
    expect(g.out('@scope/local@2.3.4').map(e => e.dst)).toContain('lodash@4.17.21')
    const out = stringify('yarn-classic', g)
    expect(stringify('yarn-classic', parse('yarn-classic', out))).toBe(out)
  })

  it('a degenerate `file:` / `link:` with no body is still rejected (not a usable specifier)', () => {
    const lf = H + '"x@file:":\n  version "0.0.0"\n  resolved "file:"\n'
    expect(() => parse('yarn-classic', lf)).toThrow(/unsupported resolved URL/)
  })
})

// #83 finding 2 — a bare package-name entry key (`foo:` with no `@range`).
// VERDICT: MALFORMED. yarn 1's lockfile writer always keys entries by
// `<name>@<range>` descriptors; a bare name is never emitted. The parser
// rejects cleanly with a typed LockfileError that names the missing `@<range>`
// — a clear diagnostic, not an uncaught crash and not a contorted attempt to
// swallow the malformed key.
describe('yarn-classic robustness — bare package-name entry key (malformed)', () => {
  it('rejects a bare-name key with a clear PARSE_FAILED diagnostic', () => {
    const lf = H + 'foo:\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz#aaa"\n'
    expect(() => parse('yarn-classic', lf)).toThrow(LockfileError)
    expect(() => parse('yarn-classic', lf)).toThrow(/bare package name with no '@<range>'/)
  })

  it('a normal `name@range` key still parses (no regression)', () => {
    const lf = H + 'foo@^1.0.0:\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz#aaa"\n'
    expect(parse('yarn-classic', lf).getNode('foo@1.0.0')).toBeDefined()
  })
})

// #83 finding 3 — quoted field-keys. VERDICT: GARBAGE (not a yarn.lock). yarn 1
// quotes string VALUES but never field KEYS (`version` / `resolved` /
// `integrity` are emitted bare). A quoted key at field position is the
// signature of a yarn-error.log "Lockfile:" dump (yarn's reporter re-indents
// the lockfile under that heading) or an otherwise mangled file. The parser
// rejects cleanly rather than bending to accept non-lockfiles.
describe('yarn-classic robustness — quoted field-keys (error-log dump / garbage)', () => {
  it('rejects quoted `"version"` / `"resolved"` field-keys with a clear diagnostic', () => {
    const lf = H + 'foo@^1.0.0:\n  "version" "1.0.0"\n  "resolved" "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz#aaa"\n'
    expect(() => parse('yarn-classic', lf)).toThrow(LockfileError)
    expect(() => parse('yarn-classic', lf)).toThrow(/quoted field-key.*not valid yarn-classic/)
  })

  it('a full yarn-error.log (no v1 header) is rejected as FORMAT_MISMATCH, not a crash', () => {
    const errlog =
      'Arguments: \n  /usr/bin/node /usr/bin/yarn install\n\n' +
      'PATH: \n  /usr/local/bin:/usr/bin\n\n' +
      'Yarn version: \n  1.22.19\n\n' +
      'Lockfile: \n' +
      '  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n' +
      '  # yarn lockfile v1\n'
    expect(detect(errlog)).toBeUndefined()
    expect(() => parse('yarn-classic', errlog)).toThrow(/expected yarn-classic lockfile v1 header/)
  })
})
