import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse, stringify, enrich } from '../../main/ts/formats/yarn-berry-v8.ts'

// Task #89 — `format(parse(x))` must preserve THREE structured fields that a
// field-level round-trip sweep proved were silently dropped on 100% of real
// berry locks (a value-only sweep missed them):
//   - `conditions:`         — a SCALAR gate (`os=darwin & cpu=arm64`), was
//                             coerced as a SymlMap → undefined for a scalar.
//   - `dependenciesMeta:`   — `{ pkg: { optional|built|… } }`, never captured.
//   - `peerDependenciesMeta:` — `{ peer: { optional: true } }`, never captured.
//
// `conditions` is emitted bare (yarn never quotes it, even with spaces/`&`/`|`);
// `dependenciesMeta` round-trips via a verbatim per-node sidecar; and
// `peerDependenciesMeta` is re-emitted through the SAME `peerDependenciesMetaOfNode`
// machinery as the #86 pnpm→berry edge-`optional` path (no parallel emit).

const here = dirname(fileURLToPath(import.meta.url))
const realFixture = (rel: string): string =>
  readFileSync(resolve(here, '../resources/fixtures/real-world', rel), 'utf8')

const MIN = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"@esbuild/darwin-arm64@npm:0.17.19":
  version: 0.17.19
  resolution: "@esbuild/darwin-arm64@npm:0.17.19"
  conditions: os=darwin & cpu=arm64
  languageName: node
  linkType: hard

"some-pkg@npm:1.0.0":
  version: 1.0.0
  resolution: "some-pkg@npm:1.0.0"
  dependencies:
    fsevents: "npm:2.3.3"
  dependenciesMeta:
    fsevents:
      optional: true
  peerDependencies:
    react: "*"
  peerDependenciesMeta:
    react:
      optional: true
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"fsevents@npm:2.3.3":
  version: 2.3.3
  resolution: "fsevents@npm:2.3.3"
  checksum: 10c0/fff
  languageName: node
  linkType: hard

"react@npm:18.2.0":
  version: 18.2.0
  resolution: "react@npm:18.2.0"
  checksum: 10c0/ddd
  languageName: node
  linkType: hard
`

describe('yarn-berry structured-field round-trip (task #89)', () => {
  it('preserves conditions / dependenciesMeta / peerDependenciesMeta on parse→stringify', () => {
    const out = stringify(parse(MIN))

    // conditions: SCALAR, emitted bare (no quotes) exactly as yarn writes it.
    expect(out).toContain('  conditions: os=darwin & cpu=arm64\n')
    expect(out).not.toContain('conditions: "os=darwin')

    // dependenciesMeta: verbatim block.
    expect(out).toContain('  dependenciesMeta:\n    fsevents:\n      optional: "true"\n')

    // peerDependenciesMeta: verbatim block.
    expect(out).toContain('  peerDependenciesMeta:\n    react:\n      optional: "true"\n')
  })

  it('is byte-idempotent (parse→stringify→parse→stringify)', () => {
    const once = stringify(parse(MIN))
    const twice = stringify(parse(once))
    expect(twice).toBe(once)
  })

  it('emits dependenciesMeta BEFORE peerDependenciesMeta (canonical yarn order)', () => {
    const out = stringify(parse(MIN))
    const block = out.slice(out.indexOf('"some-pkg@npm:1.0.0"'))
    expect(block.indexOf('dependenciesMeta:')).toBeGreaterThan(-1)
    expect(block.indexOf('dependenciesMeta:')).toBeLessThan(block.indexOf('peerDependenciesMeta:'))
  })

  it('preserves a conditions scalar with `( | )` groups and spaces verbatim', () => {
    const src = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"systeminformation@npm:5.23.8":
  version: 5.23.8
  resolution: "systeminformation@npm:5.23.8"
  bin:
    systeminformation: lib/cli.js
  checksum: 10c0/${'d'.repeat(128)}
  conditions: (os=darwin | os=linux | os=win32 | os=freebsd)
  languageName: node
  linkType: hard
`
    const out = stringify(parse(src))
    expect(out).toContain('  conditions: (os=darwin | os=linux | os=win32 | os=freebsd)\n')
    // `bin` precedes `conditions` in the emit schedule; both survive. (NB: this
    // adapter emits checksum/conditions after languageName/linkType — a
    // pre-existing intra-emitter schedule that differs from yarn's native field
    // order but round-trips losslessly and idempotently; see the format spec.)
    expect(out.indexOf('bin:')).toBeLessThan(out.indexOf('conditions:'))
    expect(stringify(parse(out))).toBe(out)
  })

  it('preserves a non-optional dependenciesMeta key (built: false)', () => {
    const src = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    esbuild: "npm:0.17.19"
  dependenciesMeta:
    esbuild:
      built: false
  languageName: unknown
  linkType: soft

"esbuild@npm:0.17.19":
  version: 0.17.19
  resolution: "esbuild@npm:0.17.19"
  checksum: 10c0/aaa
  languageName: node
  linkType: hard
`
    const out = stringify(parse(src))
    expect(out).toContain('  dependenciesMeta:\n    esbuild:\n      built: "false"\n')
    expect(stringify(parse(out))).toBe(out)
  })

  it('peerDependenciesMeta routes through peerDependenciesMetaOfNode with NO double-emit', () => {
    // The peer is optional in BOTH the on-lock meta AND (after enrich) the derived
    // peer edge. The emitter must union them into ONE block entry, not two. After
    // enrich, some-pkg gains a peerContext so its entry KEY changes — locate its
    // block by the stable `resolution: "some-pkg@npm:1.0.0"` line instead.
    const g0 = parse(MIN)
    const { graph: g } = enrich(g0) // derives the react peer edge + folds optional
    const out = stringify(g)

    // Confirm enrich actually materialised the optional peer edge (rung-0 from
    // the on-lock peerDependenciesMeta), so this is a genuine union, not a no-op.
    const some = Array.from(g.nodes()).find(n => n.name === 'some-pkg')!
    const peerEdges = g.out(some.id, 'peer')
    expect(peerEdges.length).toBe(1)
    expect(peerEdges[0]!.attrs?.optional).toBe(true)

    // Whole-output: exactly one peerDependenciesMeta block, and `react` is emitted
    // exactly once under a meta context (no duplicate from the edge + the hint).
    expect((out.match(/peerDependenciesMeta:/g) ?? []).length).toBe(1)
    const metaStart = out.indexOf('peerDependenciesMeta:')
    const metaBlock = out.slice(metaStart, metaStart + 80)
    expect((metaBlock.match(/react:\n      optional: "true"/g) ?? []).length).toBe(1)

    // Idempotent through enrich-shaped output too.
    expect(stringify(parse(out))).toBe(out)
  })

  it('handles the same package name in BOTH dependenciesMeta and peerDependenciesMeta', () => {
    // `react` is listed as a dep (with dependenciesMeta.optional) AND a peer (with
    // peerDependenciesMeta.optional) of the same parent — the two blocks are
    // independent and must both survive without cross-contamination.
    const src = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"dual@npm:1.0.0":
  version: 1.0.0
  resolution: "dual@npm:1.0.0"
  dependencies:
    react: "npm:18.2.0"
  dependenciesMeta:
    react:
      optional: true
  peerDependencies:
    react: "*"
  peerDependenciesMeta:
    react:
      optional: true
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"react@npm:18.2.0":
  version: 18.2.0
  resolution: "react@npm:18.2.0"
  checksum: 10c0/ddd
  languageName: node
  linkType: hard
`
    const out = stringify(parse(src))
    expect(out).toContain('  dependenciesMeta:\n    react:\n      optional: "true"\n')
    expect(out).toContain('  peerDependenciesMeta:\n    react:\n      optional: "true"\n')
    expect(stringify(parse(out))).toBe(out)
  })

  it('real berry fixture (highlight): conditions/dependenciesMeta/peerDependenciesMeta counts survive round-trip', () => {
    const raw = realFixture('highlight-highlight-main-7a297b5/yarn.lock')
    const count = (s: string, re: RegExp): number => (s.match(re) ?? []).length
    const condRe = /^\s*conditions:/gm
    const depMetaRe = /^\s*dependenciesMeta:/gm
    const peerMetaRe = /^\s*peerDependenciesMeta:/gm

    const out = stringify(parse(raw))

    expect(count(out, condRe)).toBe(count(raw, condRe))       // 433 → 433 (was → 0)
    expect(count(out, depMetaRe)).toBe(count(raw, depMetaRe)) // 97  → 97
    expect(count(out, peerMetaRe)).toBe(count(raw, peerMetaRe)) // 209 → 209

    // And the conditions values themselves are bare (a spot check on a known token).
    expect(out).toContain('conditions: os=darwin & cpu=arm64')
  })
})
