import { describe, expect, it } from 'vitest'
import { check, parse, stringify } from '../../main/ts/formats/yarn-classic.ts'
import { detect } from '../../main/ts/index.ts'

// yarn-classic parse edge cases: bare/unquoted dependency values, UTF-8 BOM
// detection, header-only (empty) lockfiles, legacy unknown entry fields.

const H =
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n' +
  '# yarn lockfile v1\n\n\n'
const BOM = String.fromCharCode(0xfeff) // U+FEFF, no raw BOM glyph in source

describe('yarn-classic — parse edge cases', () => {
  // Bare (unquoted) dependency value: dist-tag, v-prefixed version. yarn 1
  // emits these forms unquoted.
  it('parses bare dist-tag + v-prefixed dependency values', () => {
    const lock =
      H +
      'foo@^1.0.0:\n' +
      '  version "1.0.0"\n' +
      '  resolved "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz#aaa"\n' +
      '  dependencies:\n' +
      '    bar latest\n' +
      '    baz v0.5.0\n' +
      '\n' +
      'bar@latest:\n' +
      '  version "2.0.0"\n' +
      '  resolved "https://registry.yarnpkg.com/bar/-/bar-2.0.0.tgz#bbb"\n' +
      '\n' +
      'baz@v0.5.0:\n' +
      '  version "0.5.0"\n' +
      '  resolved "https://registry.yarnpkg.com/baz/-/baz-0.5.0.tgz#ccc"\n'
    expect(() => parse(lock)).not.toThrow()
    const g = parse(lock)
    const foo = g.getNode('foo@1.0.0')
    expect(foo).toBeDefined()
    const deps = g.out(foo!.id).map(e => e.dst).sort()
    expect(deps).toContain('bar@2.0.0')
    expect(deps).toContain('baz@0.5.0')
  })

  // yarn-1 legacy `uid` field on link:/file: entries. The parser threw
  // `unsupported entry field`; now it is TOLERATED + round-tripped verbatim
  // (forward-compat for any unmodelled scalar entry field).
  it('tolerates + round-trips the legacy `uid` field (link: entry)', () => {
    const lock =
      H +
      '"my-internal-rules@link:./scripts/eslint-rules":\n' +
      '  version "0.0.0"\n' +
      '  uid ""\n'
    expect(() => parse(lock)).not.toThrow()
    const g = parse(lock)
    expect(g.getNode('my-internal-rules@0.0.0')).toBeDefined()
    // uid round-trips verbatim
    const out = stringify(g)
    expect(out).toContain('  uid ""')
    // re-parse is stable (idempotent) and still carries uid
    expect(stringify(parse(out))).toBe(out)
  })

  // A leading UTF-8 BOM must not defeat detect (was asymmetric: berry detected,
  // classic did not).
  it('detects + parses a v1 lockfile with a leading UTF-8 BOM', () => {
    const lock = BOM + H + 'foo@^1.0.0:\n  version "1.0.0"\n  resolved "https://r/foo#a"\n'
    expect(check(lock)).toBe(true)
    expect(detect(lock)).toBe('yarn-classic')
    expect(() => parse(lock)).not.toThrow()
    expect(parse(lock).getNode('foo@1.0.0')).toBeDefined()
  })

  // Header-only (fresh-init, empty) v1 lockfile: detect + empty graph (was
  // asymmetric: berry → empty graph, classic → no detect).
  it('detects + parses a header-only v1 lockfile as an empty graph', () => {
    const headerOnly = '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n'
    expect(check(headerOnly)).toBe(true)
    expect(detect(headerOnly)).toBe('yarn-classic')
    expect(Array.from(parse(headerOnly).nodes())).toEqual([])
  })
})
