import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse, stringify, enrich } from '../../main/ts/formats/yarn-berry-v8.ts'

// Task #89 — `format(parse(x))` must preserve THREE structured fields that a
// field-level round-trip sweep proved were silently dropped on 100% of real
// berry locks (a value-only sweep missed them):
//   - `conditions:`         — a SCALAR gate (`os=darwin & cpu=arm64`), was
//                             coerced as a SymlMap → undefined for a scalar.
//   - `dependenciesMeta:`   — `{ pkg: { optional|built|… } }`, never captured.
//   - `peerDependenciesMeta:` — `{ peer: { optional: true } }`, never captured.
//
// `conditions` is emitted bare (yarn never quotes it, even with spaces/`&`/`|`);
// `dependenciesMeta` round-trips via a verbatim per-node sidecar; and
// `peerDependenciesMeta` is re-emitted through the SAME `peerDependenciesMetaOfNode`
// machinery as the #86 pnpm→berry edge-`optional` path (no parallel emit).

const here = dirname(fileURLToPath(import.meta.url))
const realFixture = (rel: string): string =>
  readFileSync(resolve(here, '../resources/fixtures/real-world', rel), 'utf8')

const MIN = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"@esbuild/darwin-arm64@npm:0.17.19":
  version: 0.17.19
  resolution: "@esbuild/darwin-arm64@npm:0.17.19"
  conditions: os=darwin & cpu=arm64
  languageName: node
  linkType: hard

"some-pkg@npm:1.0.0":
  version: 1.0.0
  resolution: "some-pkg@npm:1.0.0"
  dependencies:
    fsevents: "npm:2.3.3"
  dependenciesMeta:
    fsevents:
      optional: true
  peerDependencies:
    react: "*"
  peerDependenciesMeta:
    react:
      optional: true
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"fsevents@npm:2.3.3":
  version: 2.3.3
  resolution: "fsevents@npm:2.3.3"
  checksum: 10c0/fff
  languageName: node
  linkType: hard

"react@npm:18.2.0":
  version: 18.2.0
  resolution: "react@npm:18.2.0"
  checksum: 10c0/ddd
  languageName: node
  linkType: hard
`

describe('yarn-berry structured-field round-trip (task #89)', () => {
  it('preserves conditions / dependenciesMeta / peerDependenciesMeta on parse→stringify', () => {
    const out = stringify(parse(MIN))

    // conditions: SCALAR, emitted bare (no quotes) exactly as yarn writes it.
    expect(out).toContain('  conditions: os=darwin & cpu=arm64\n')
    expect(out).not.toContain('conditions: "os=darwin')

    // dependenciesMeta: verbatim block — boolean value emitted BARE (like yarn).
    expect(out).toContain('  dependenciesMeta:\n    fsevents:\n      optional: true\n')

    // peerDependenciesMeta: verbatim block — boolean value emitted BARE.
    expect(out).toContain('  peerDependenciesMeta:\n    react:\n      optional: true\n')

    // And NEVER the quoted form (the #89 regression: `optional: "true"`).
    expect(out).not.toContain('optional: "true"')
  })

  it('is byte-idempotent (parse→stringify→parse→stringify)', () => {
    const once = stringify(parse(MIN))
    const twice = stringify(parse(once))
    expect(twice).toBe(once)
  })

  it('emits dependenciesMeta BEFORE peerDependenciesMeta (canonical yarn order)', () => {
    const out = stringify(parse(MIN))
    const block = out.slice(out.indexOf('"some-pkg@npm:1.0.0"'))
    expect(block.indexOf('dependenciesMeta:')).toBeGreaterThan(-1)
    expect(block.indexOf('dependenciesMeta:')).toBeLessThan(block.indexOf('peerDependenciesMeta:'))
  })

  it('preserves a conditions scalar with `( | )` groups and spaces verbatim', () => {
    const src = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"systeminformation@npm:5.23.8":
  version: 5.23.8
  resolution: "systeminformation@npm:5.23.8"
  bin:
    systeminformation: lib/cli.js
  checksum: 10c0/${'d'.repeat(128)}
  conditions: (os=darwin | os=linux | os=win32 | os=freebsd)
  languageName: node
  linkType: hard
`
    const out = stringify(parse(src))
    expect(out).toContain('  conditions: (os=darwin | os=linux | os=win32 | os=freebsd)\n')
    // `bin` precedes `conditions` in the emit schedule; both survive. (NB: this
    // adapter emits checksum/conditions after languageName/linkType — a
    // pre-existing intra-emitter schedule that differs from yarn's native field
    // order but round-trips losslessly and idempotently; see the format spec.)
    expect(out.indexOf('bin:')).toBeLessThan(out.indexOf('conditions:'))
    expect(stringify(parse(out))).toBe(out)
  })

  it('preserves a non-optional dependenciesMeta key (built: false)', () => {
    const src = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    esbuild: "npm:0.17.19"
  dependenciesMeta:
    esbuild:
      built: false
  languageName: unknown
  linkType: soft

"esbuild@npm:0.17.19":
  version: 0.17.19
  resolution: "esbuild@npm:0.17.19"
  checksum: 10c0/aaa
  languageName: node
  linkType: hard
`
    const out = stringify(parse(src))
    // `built: false` emits BARE. The quoted form `built: "false"` would be a
    // non-empty (TRUTHY) string → yarn's `if (meta.built)` flips to true and may
    // run a postinstall the lock meant to suppress. Bare is correctness here.
    expect(out).toContain('  dependenciesMeta:\n    esbuild:\n      built: false\n')
    expect(out).not.toContain('built: "false"')
    expect(stringify(parse(out))).toBe(out)
  })

  it('peerDependenciesMeta routes through peerDependenciesMetaOfNode with NO double-emit', () => {
    // The peer is optional in BOTH the on-lock meta AND (after enrich) the derived
    // peer edge. The emitter must union them into ONE block entry, not two. After
    // enrich, some-pkg gains a peerContext so its entry KEY changes — locate its
    // block by the stable `resolution: "some-pkg@npm:1.0.0"` line instead.
    const g0 = parse(MIN)
    const { graph: g } = enrich(g0) // derives the react peer edge + folds optional
    const out = stringify(g)

    // Confirm enrich actually materialised the optional peer edge (rung-0 from
    // the on-lock peerDependenciesMeta), so this is a genuine union, not a no-op.
    const some = Array.from(g.nodes()).find(n => n.name === 'some-pkg')!
    const peerEdges = g.out(some.id, 'peer')
    expect(peerEdges.length).toBe(1)
    expect(peerEdges[0]!.attrs?.optional).toBe(true)

    // Whole-output: exactly one peerDependenciesMeta block, and `react` is emitted
    // exactly once under a meta context (no duplicate from the edge + the hint).
    expect((out.match(/peerDependenciesMeta:/g) ?? []).length).toBe(1)
    const metaStart = out.indexOf('peerDependenciesMeta:')
    const metaBlock = out.slice(metaStart, metaStart + 80)
    expect((metaBlock.match(/react:\n      optional: true\n/g) ?? []).length).toBe(1)

    // Idempotent through enrich-shaped output too.
    expect(stringify(parse(out))).toBe(out)
  })

  it('handles the same package name in BOTH dependenciesMeta and peerDependenciesMeta', () => {
    // `react` is listed as a dep (with dependenciesMeta.optional) AND a peer (with
    // peerDependenciesMeta.optional) of the same parent — the two blocks are
    // independent and must both survive without cross-contamination.
    const src = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"dual@npm:1.0.0":
  version: 1.0.0
  resolution: "dual@npm:1.0.0"
  dependencies:
    react: "npm:18.2.0"
  dependenciesMeta:
    react:
      optional: true
  peerDependencies:
    react: "*"
  peerDependenciesMeta:
    react:
      optional: true
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"react@npm:18.2.0":
  version: 18.2.0
  resolution: "react@npm:18.2.0"
  checksum: 10c0/ddd
  languageName: node
  linkType: hard
`
    const out = stringify(parse(src))
    expect(out).toContain('  dependenciesMeta:\n    react:\n      optional: true\n')
    expect(out).toContain('  peerDependenciesMeta:\n    react:\n      optional: true\n')
    expect(out).not.toContain('optional: "true"')
    expect(stringify(parse(out))).toBe(out)
  })

  it('real berry fixture (highlight): conditions/dependenciesMeta/peerDependenciesMeta counts survive round-trip', () => {
    const raw = realFixture('highlight-highlight-main-7a297b5/yarn.lock')
    const count = (s: string, re: RegExp): number => (s.match(re) ?? []).length
    const condRe = /^\s*conditions:/gm
    const depMetaRe = /^\s*dependenciesMeta:/gm
    const peerMetaRe = /^\s*peerDependenciesMeta:/gm

    const out = stringify(parse(raw))

    expect(count(out, condRe)).toBe(count(raw, condRe))       // 433 → 433 (was → 0)
    expect(count(out, depMetaRe)).toBe(count(raw, depMetaRe)) // 97  → 97
    expect(count(out, peerMetaRe)).toBe(count(raw, peerMetaRe)) // 209 → 209

    // And the conditions values themselves are bare (a spot check on a known token).
    expect(out).toContain('conditions: os=darwin & cpu=arm64')

    // Meta-block booleans round-trip BARE, exactly as yarn wrote them (the #89
    // regression quoted them). The raw fixture has NO quoted 6-space meta boolean;
    // neither may the emit. The per-key bare counts must also match the raw.
    const quotedMetaBool = /^      (?:optional|built|unplugged): "(?:true|false)"$/gm
    expect(count(raw, quotedMetaBool)).toBe(0)  // yarn never quotes them
    expect(count(out, quotedMetaBool)).toBe(0)  // and neither do we
    const bareOptional = /^      optional: (?:true|false)$/gm
    const bareBuilt = /^      built: (?:true|false)$/gm
    expect(count(out, bareOptional)).toBe(count(raw, bareOptional))
    expect(count(out, bareBuilt)).toBe(count(raw, bareBuilt))
  })
})

// #89 regression — the meta-block booleans inside `dependenciesMeta:` /
// `peerDependenciesMeta:` were emitted QUOTED (`optional: "true"`, `built:
// "false"`). yarn writes them BARE; `built: "false"` is moreover a TRUTHY
// non-empty string, inverting "do not build" → potential postinstall execution.
describe('yarn-berry meta-block booleans emit bare (#89 regression)', () => {
  const REPRO = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"some-pkg@npm:1.0.0":
  version: 1.0.0
  resolution: "some-pkg@npm:1.0.0"
  dependencies:
    esbuild: "npm:0.17.19"
    fsevents: "npm:2.3.3"
  dependenciesMeta:
    esbuild:
      built: false
    fsevents:
      optional: true
  peerDependencies:
    react: "*"
  peerDependenciesMeta:
    react:
      optional: true
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"esbuild@npm:0.17.19":
  version: 0.17.19
  resolution: "esbuild@npm:0.17.19"
  checksum: 10c0/aaa
  languageName: node
  linkType: hard

"fsevents@npm:2.3.3":
  version: 2.3.3
  resolution: "fsevents@npm:2.3.3"
  checksum: 10c0/fff
  languageName: node
  linkType: hard

"react@npm:18.2.0":
  version: 18.2.0
  resolution: "react@npm:18.2.0"
  checksum: 10c0/ddd
  languageName: node
  linkType: hard
`

  it('emits optional/built bare, never quoted', () => {
    const out = stringify(parse(REPRO))

    // BARE, as yarn writes them.
    expect(out).toContain('  dependenciesMeta:\n    esbuild:\n      built: false\n')
    expect(out).toContain('    fsevents:\n      optional: true\n')
    expect(out).toContain('  peerDependenciesMeta:\n    react:\n      optional: true\n')

    // NEVER the quoted (regressed) form for any meta boolean.
    expect(out).not.toContain('optional: "true"')
    expect(out).not.toContain('built: "false"')
    expect(out).not.toMatch(/^      (?:optional|built|unplugged): "(?:true|false)"$/m)
  })

  it('round-trips the meta booleans (bare → reparse → bare)', () => {
    const out = stringify(parse(REPRO))
    // The booleans survive a reparse (the unquoted bare scalar reads back as the
    // same `'true'`/`'false'` string and re-emits bare).
    expect(stringify(parse(out))).toContain('      built: false\n')
    expect(stringify(parse(out))).toContain('      optional: true\n')
  })

  it('is byte-stable across a double round-trip', () => {
    const once = stringify(parse(REPRO))
    const twice = stringify(parse(once))
    const thrice = stringify(parse(twice))
    expect(twice).toBe(once)
    expect(thrice).toBe(twice)
  })

  it('emits a `true`/`false` bin value BARE, like yarn, and round-trips byte-stably', () => {
    // yarn's SYML writer applies one uniform quoting rule (`simpleStringPattern`)
    // to EVERY scalar at every depth — no special-casing by key/nesting. A `bin`
    // target whose value is the token `true`/`false` therefore emits BARE, exactly
    // as yarn does (verified against the upstream yarnpkg-parsers writer). Our
    // parser reads every SYML scalar as a string, so the bare token reads back as
    // `'true'`/`'false'` and the lock stays byte-stable across reparses.
    const src = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"weird@npm:1.0.0":
  version: 1.0.0
  resolution: "weird@npm:1.0.0"
  bin:
    built: false
    optional: true
  checksum: 10c0/abc
  languageName: node
  linkType: hard
`
    const out = stringify(parse(src))
    // Bare in, bare out — matches yarn's uniform `simpleStringPattern` rule.
    expect(out).toContain('  bin:\n    built: false\n    optional: true\n')
    expect(out).not.toContain('built: "false"')
    expect(out).not.toContain('optional: "true"')
    // Byte-stable: the bare tokens survive reparse + re-emit unchanged.
    expect(stringify(parse(out))).toBe(out)
  })
})
