import { describe, expect, it } from 'vitest'
import { parse, stringify } from '../../main/ts/index.ts'

// Robustness gaps from the yarn-audit-fix real-world sweep (snapshot.49).
// Minimal repros only — no external fixtures.

const ANSI_SRI = 'sha512-zbB9rCJAt1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg=='

describe('yarn-classic robustness — git-protocol resolved URLs', () => {
  it('a git+ssh resolved URL parses (modelled as a git resolution), not a whole-file abort', () => {
    const lf =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      'from-git@git+ssh://git@github.com/example/from-git.git:\n' +
      '  version "0.0.0"\n' +
      '  resolved "git+ssh://git@github.com/example/from-git.git#0123456789abcdef0123456789abcdef01234567"\n'
    const g = parse('yarn-classic', lf)
    expect(g.getNode('from-git@0.0.0')).toBeDefined()
    expect(g.getNode('from-git@0.0.0')?.resolution).toBe('git+ssh://git@github.com/example/from-git.git#0123456789abcdef0123456789abcdef01234567')
    expect(g.tarballOf('from-git@0.0.0')?.resolution?.type).toBe('git')
  })

  it('git:// and scp-like git@ forms also parse', () => {
    const lf =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
      '"ws@git://github.com/frozeman/WebSocket-Node.git":\n' +
      '  version "1.0.0"\n' +
      '  resolved "git://github.com/frozeman/WebSocket-Node.git#deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"\n'
    const g = parse('yarn-classic', lf)
    expect(g.getNode('ws@1.0.0')?.resolution).toMatch(/^git:\/\//)
    expect(g.tarballOf('ws@1.0.0')?.resolution?.type).toBe('git')
  })
})

describe('yarn-classic robustness — duplicate descriptors that should merge', () => {
  const dupBlocks = (resolvedA: string, resolvedB: string, integA = ANSI_SRI, integB = ANSI_SRI): string =>
    '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n' +
    'ansi-styles@^4.0.0:\n' +
    '  version "4.3.0"\n' +
    `  resolved "${resolvedA}"\n` +
    `  integrity ${integA}\n\n` +
    'ansi-styles@^4.1.0:\n' +
    '  version "4.3.0"\n' +
    `  resolved "${resolvedB}"\n` +
    `  integrity ${integB}\n`

  const REG = 'https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz'

  it('two blocks resolving to the same name@version with identical resolution merge into one node', () => {
    const g = parse('yarn-classic', dupBlocks(REG, REG))
    expect(g.byName('ansi-styles')).toHaveLength(1)
    expect(g.getNode('ansi-styles@4.3.0')).toBeDefined()
  })

  it('the merged node re-emits BOTH descriptor keys on one entry', () => {
    const out = stringify('yarn-classic', parse('yarn-classic', dupBlocks(REG, REG)))
    expect(out).toContain('ansi-styles@^4.0.0')
    expect(out).toContain('ansi-styles@^4.1.0')
    // one entry block, not two: the version line appears once.
    expect(out.match(/version "4\.3\.0"/g)).toHaveLength(1)
  })

  it('a GENUINE conflict (same name@version, differing resolution) still throws IRREDUCIBLE_LOSS', () => {
    const conflict = dupBlocks(REG, 'https://example.com/other-ansi-styles-4.3.0.tgz')
    expect(() => parse('yarn-classic', conflict)).toThrow(/collapse onto NodeId ansi-styles@4\.3\.0/)
  })
})
