import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse, stringify, enrich } from '../../main/ts/formats/yarn-berry-v8.ts'
import { parse as parseV4, stringify as stringifyV4 } from '../../main/ts/formats/yarn-berry-v4.ts'
import { stringify as npm3Stringify } from '../../main/ts/formats/npm-3.ts'

// Task #89 — `format(parse(x))` must preserve THREE structured fields that a
// field-level round-trip sweep proved were silently dropped on 100% of real
// berry locks (a value-only sweep missed them):
//   - `conditions:`         — a SCALAR gate (`os=darwin & cpu=arm64`), was
//                             coerced as a SymlMap → undefined for a scalar.
//   - `dependenciesMeta:`   — `{ pkg: { optional|built|… } }`, never captured.
//   - `peerDependenciesMeta:` — `{ peer: { optional: true } }`, never captured.
//
// `conditions` is emitted bare (yarn never quotes it, even with spaces/`&`/`|`);
// `dependenciesMeta` round-trips via a verbatim per-node sidecar; and
// `peerDependenciesMeta` is re-emitted through the SAME `peerDependenciesMetaOfNode`
// machinery as the #86 pnpm→berry edge-`optional` path (no parallel emit).

const here = dirname(fileURLToPath(import.meta.url))
const realFixture = (rel: string): string =>
  readFileSync(resolve(here, '../resources/fixtures/real-world', rel), 'utf8')

const MIN = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"@esbuild/darwin-arm64@npm:0.17.19":
  version: 0.17.19
  resolution: "@esbuild/darwin-arm64@npm:0.17.19"
  conditions: os=darwin & cpu=arm64
  languageName: node
  linkType: hard

"some-pkg@npm:1.0.0":
  version: 1.0.0
  resolution: "some-pkg@npm:1.0.0"
  dependencies:
    fsevents: "npm:2.3.3"
  dependenciesMeta:
    fsevents:
      optional: true
  peerDependencies:
    react: "*"
  peerDependenciesMeta:
    react:
      optional: true
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"fsevents@npm:2.3.3":
  version: 2.3.3
  resolution: "fsevents@npm:2.3.3"
  checksum: 10c0/fff
  languageName: node
  linkType: hard

"react@npm:18.2.0":
  version: 18.2.0
  resolution: "react@npm:18.2.0"
  checksum: 10c0/ddd
  languageName: node
  linkType: hard
`

describe('yarn-berry structured-field round-trip (task #89)', () => {
  it('preserves conditions / dependenciesMeta / peerDependenciesMeta on parse→stringify', () => {
    const out = stringify(parse(MIN))

    // conditions: SCALAR, emitted bare (no quotes) exactly as yarn writes it.
    expect(out).toContain('  conditions: os=darwin & cpu=arm64\n')
    expect(out).not.toContain('conditions: "os=darwin')

    // dependenciesMeta: verbatim block — boolean value emitted BARE (like yarn).
    expect(out).toContain('  dependenciesMeta:\n    fsevents:\n      optional: true\n')

    // peerDependenciesMeta: verbatim block — boolean value emitted BARE.
    expect(out).toContain('  peerDependenciesMeta:\n    react:\n      optional: true\n')

    // And NEVER the quoted form (the #89 regression: `optional: "true"`).
    expect(out).not.toContain('optional: "true"')
  })

  it('is byte-idempotent (parse→stringify→parse→stringify)', () => {
    const once = stringify(parse(MIN))
    const twice = stringify(parse(once))
    expect(twice).toBe(once)
  })

  it('emits dependenciesMeta BEFORE peerDependenciesMeta (canonical yarn order)', () => {
    const out = stringify(parse(MIN))
    const block = out.slice(out.indexOf('"some-pkg@npm:1.0.0"'))
    expect(block.indexOf('dependenciesMeta:')).toBeGreaterThan(-1)
    expect(block.indexOf('dependenciesMeta:')).toBeLessThan(block.indexOf('peerDependenciesMeta:'))
  })

  it('preserves a conditions scalar with `( | )` groups and spaces verbatim', () => {
    const src = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"systeminformation@npm:5.23.8":
  version: 5.23.8
  resolution: "systeminformation@npm:5.23.8"
  bin:
    systeminformation: lib/cli.js
  checksum: 10c0/${'d'.repeat(128)}
  conditions: (os=darwin | os=linux | os=win32 | os=freebsd)
  languageName: node
  linkType: hard
`
    const out = stringify(parse(src))
    expect(out).toContain('  conditions: (os=darwin | os=linux | os=win32 | os=freebsd)\n')
    // `bin` precedes `conditions` in the emit schedule; both survive. (NB: this
    // adapter emits checksum/conditions after languageName/linkType — a
    // pre-existing intra-emitter schedule that differs from yarn's native field
    // order but round-trips losslessly and idempotently; see the format spec.)
    expect(out.indexOf('bin:')).toBeLessThan(out.indexOf('conditions:'))
    expect(stringify(parse(out))).toBe(out)
  })

  it('preserves a non-optional dependenciesMeta key (built: false)', () => {
    const src = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    esbuild: "npm:0.17.19"
  dependenciesMeta:
    esbuild:
      built: false
  languageName: unknown
  linkType: soft

"esbuild@npm:0.17.19":
  version: 0.17.19
  resolution: "esbuild@npm:0.17.19"
  checksum: 10c0/aaa
  languageName: node
  linkType: hard
`
    const out = stringify(parse(src))
    // `built: false` emits BARE. The quoted form `built: "false"` would be a
    // non-empty (TRUTHY) string → yarn's `if (meta.built)` flips to true and may
    // run a postinstall the lock meant to suppress. Bare is correctness here.
    expect(out).toContain('  dependenciesMeta:\n    esbuild:\n      built: false\n')
    expect(out).not.toContain('built: "false"')
    expect(stringify(parse(out))).toBe(out)
  })

  it('peerDependenciesMeta routes through peerDependenciesMetaOfNode with NO double-emit', () => {
    // The peer is optional in BOTH the on-lock meta AND (after enrich) the derived
    // peer edge. The emitter must union them into ONE block entry, not two. After
    // enrich, some-pkg gains a peerContext so its entry KEY changes — locate its
    // block by the stable `resolution: "some-pkg@npm:1.0.0"` line instead.
    const g0 = parse(MIN)
    const { graph: g } = enrich(g0) // derives the react peer edge + folds optional
    const out = stringify(g)

    // Confirm enrich actually materialised the optional peer edge (rung-0 from
    // the on-lock peerDependenciesMeta), so this is a genuine union, not a no-op.
    const some = Array.from(g.nodes()).find(n => n.name === 'some-pkg')!
    const peerEdges = g.out(some.id, 'peer')
    expect(peerEdges.length).toBe(1)
    expect(peerEdges[0]!.attrs?.optional).toBe(true)

    // Whole-output: exactly one peerDependenciesMeta block, and `react` is emitted
    // exactly once under a meta context (no duplicate from the edge + the hint).
    expect((out.match(/peerDependenciesMeta:/g) ?? []).length).toBe(1)
    const metaStart = out.indexOf('peerDependenciesMeta:')
    const metaBlock = out.slice(metaStart, metaStart + 80)
    expect((metaBlock.match(/react:\n      optional: true\n/g) ?? []).length).toBe(1)

    // Idempotent through enrich-shaped output too.
    expect(stringify(parse(out))).toBe(out)
  })

  it('handles the same package name in BOTH dependenciesMeta and peerDependenciesMeta', () => {
    // `react` is listed as a dep (with dependenciesMeta.optional) AND a peer (with
    // peerDependenciesMeta.optional) of the same parent — the two blocks are
    // independent and must both survive without cross-contamination.
    const src = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"dual@npm:1.0.0":
  version: 1.0.0
  resolution: "dual@npm:1.0.0"
  dependencies:
    react: "npm:18.2.0"
  dependenciesMeta:
    react:
      optional: true
  peerDependencies:
    react: "*"
  peerDependenciesMeta:
    react:
      optional: true
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"react@npm:18.2.0":
  version: 18.2.0
  resolution: "react@npm:18.2.0"
  checksum: 10c0/ddd
  languageName: node
  linkType: hard
`
    const out = stringify(parse(src))
    expect(out).toContain('  dependenciesMeta:\n    react:\n      optional: true\n')
    expect(out).toContain('  peerDependenciesMeta:\n    react:\n      optional: true\n')
    expect(out).not.toContain('optional: "true"')
    expect(stringify(parse(out))).toBe(out)
  })

  it('real berry fixture (highlight): conditions/dependenciesMeta/peerDependenciesMeta counts survive round-trip', () => {
    const raw = realFixture('highlight-highlight-main-7a297b5/yarn.lock')
    const count = (s: string, re: RegExp): number => (s.match(re) ?? []).length
    const condRe = /^\s*conditions:/gm
    const depMetaRe = /^\s*dependenciesMeta:/gm
    const peerMetaRe = /^\s*peerDependenciesMeta:/gm

    const out = stringify(parse(raw))

    expect(count(out, condRe)).toBe(count(raw, condRe))       // 433 → 433 (was → 0)
    expect(count(out, depMetaRe)).toBe(count(raw, depMetaRe)) // 97  → 97
    expect(count(out, peerMetaRe)).toBe(count(raw, peerMetaRe)) // 209 → 209

    // And the conditions values themselves are bare (a spot check on a known token).
    expect(out).toContain('conditions: os=darwin & cpu=arm64')

    // Meta-block booleans round-trip BARE, exactly as yarn wrote them (the #89
    // regression quoted them). The raw fixture has NO quoted 6-space meta boolean;
    // neither may the emit. The per-key bare counts must also match the raw.
    const quotedMetaBool = /^      (?:optional|built|unplugged): "(?:true|false)"$/gm
    expect(count(raw, quotedMetaBool)).toBe(0)  // yarn never quotes them
    expect(count(out, quotedMetaBool)).toBe(0)  // and neither do we
    const bareOptional = /^      optional: (?:true|false)$/gm
    const bareBuilt = /^      built: (?:true|false)$/gm
    expect(count(out, bareOptional)).toBe(count(raw, bareOptional))
    expect(count(out, bareBuilt)).toBe(count(raw, bareBuilt))
  })
})

// F8/#103 — a dependency reference whose target package is ABSENT from the lock
// (no `resolution:` entry block, and the descriptor→node ladder's Rung 4 cannot
// bind it) was DROPPED on `format(parse(x))`: parse dropped the unbindable edge,
// and stringify rebuilds the `dependencies:` block from LIVE edges only, so the
// ref vanished. These are NOT canonical graph edges (there is no target node) —
// they are FORMAT-FIDELITY only, captured in a verbatim PM-native per-node
// sidecar (the `Node.resolution` / `conditions` / `dependenciesMeta` precedent,
// ADR-0013) and re-emitted into the correct inner-block, so same-format
// round-trip is byte-faithful. Preservation must NOT silence the existing
// MISSING-ENTRY (`YARN_BERRY_UNRESOLVED_DEP`) diagnostic — we keep informing AND
// keep the bytes. Sibling repro: mui/material-ui@9291574.
describe('yarn-berry unresolvable dep refs round-trip verbatim (F8/#103)', () => {
  // `host` declares `dependencies:` refs to `ghost@npm:^1.0.0` and (flagged
  // optional via `dependenciesMeta`) `phantom@npm:^2.0.0`, plus a peerDependencies
  // ref to `spectre@*` — NONE of which have an entry block in the lock. (A
  // resolvable sibling `present` keeps the dep block non-trivial.) berry has NO
  // `optionalDependencies:` block — an optional dep lives in `dependencies` +
  // `dependenciesMeta.<name>.optional` (§1.4), so the unresolvable optional ref
  // is exercised in that real shape. Written in this adapter's CANONICAL emit
  // order so a byte-for-byte `toBe` round-trip holds.
  const A128 = 'a'.repeat(128)
  const F128 = 'f'.repeat(128)
  // NB: the canonical preamble carries a BLANK line before `__metadata:` (the
  // emitter writes `PREAMBLE + '\n\n'`), so this source is in emitted-canonical
  // form for the byte-for-byte `toBe` assertion.
  const REPRO = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"host@npm:1.0.0":
  version: 1.0.0
  resolution: "host@npm:1.0.0"
  dependencies:
    ghost: "npm:^1.0.0"
    phantom: "npm:^2.0.0"
    present: "npm:1.2.3"
  peerDependencies:
    spectre: "*"
  dependenciesMeta:
    phantom:
      optional: true
  checksum: 10c0/${A128}
  languageName: node
  linkType: hard

"present@npm:1.2.3":
  version: 1.2.3
  resolution: "present@npm:1.2.3"
  checksum: 10c0/${F128}
  languageName: node
  linkType: hard
`

  it('round-trips an unresolvable dependencies-block ref byte-for-byte', () => {
    const out = stringify(parse(REPRO))
    // Both dropped refs reappear verbatim in the host's dependencies block
    // (ghost + phantom unresolvable, present resolvable), name-sorted.
    expect(out).toContain('  dependencies:\n    ghost: "npm:^1.0.0"\n    phantom: "npm:^2.0.0"\n    present: "npm:1.2.3"\n')
    // The optional flag survives as dependenciesMeta — never a separate block.
    expect(out).toContain('  dependenciesMeta:\n    phantom:\n      optional: true\n')
    expect(out).not.toContain('optionalDependencies:')
    // Full byte-for-byte: the emitted lock equals the source.
    expect(out).toBe(REPRO)
  })

  it('still emits the MISSING-ENTRY diagnostic for every unresolvable ref (preservation ≠ silencing)', () => {
    const g = parse(REPRO)
    const codes = g.diagnostics().filter(d => d.code === 'YARN_BERRY_UNRESOLVED_DEP')
    // ghost + phantom (both dependencies refs), spectre (peer) all miss the
    // ladder. The two dep refs go through addEdgesFromBlock and must each
    // diagnose; the peer ref is reconstructed at enrich, so the count is ≥2.
    const subjects = codes.map(d => d.message)
    expect(subjects.some(m => m.includes('ghost'))).toBe(true)
    expect(subjects.some(m => m.includes('phantom'))).toBe(true)
  })

  it('is byte-idempotent across a double round-trip', () => {
    const once = stringify(parse(REPRO))
    const twice = stringify(parse(once))
    expect(twice).toBe(once)
  })

  it('does NOT mint a phantom node or edge for the unresolvable ref', () => {
    const g = parse(REPRO)
    // No `ghost`/`phantom`/`spectre` node was invented (NodeId identity is clean).
    expect(Array.from(g.nodes()).some(n => n.name === 'ghost')).toBe(false)
    expect(Array.from(g.nodes()).some(n => n.name === 'phantom')).toBe(false)
    const host = Array.from(g.nodes()).find(n => n.name === 'host')!
    // The only live dep edge is the resolvable `present`; ghost has no edge.
    const depTargets = g.out(host.id, 'dep').map(e => g.getNode(e.dst)?.name)
    expect(depTargets).toEqual(['present'])
  })

  it('a cross-PM convert (berry → npm) does NOT carry the berry-native unresolved refs', () => {
    // The refs are a berry-format sidecar (per-graph WeakMap in the berry
    // adapter); they are NOT graph edges, so a foreign adapter never sees them.
    // Convert to npm-3 and confirm neither ghost nor phantom leaks across.
    const out = npm3Stringify(parse(REPRO))
    expect(out).not.toContain('ghost')
    expect(out).not.toContain('phantom')
  })

  it('survives an enrich() node-id remap (re-emits verbatim afterwards)', () => {
    // `host` declares a peer (spectre@*) → enrich would normally rewrite ids when
    // a peerContext changes. Even without a materialised peer here, the sidecar
    // must propagate through enrich's rebuild and still round-trip byte-for-byte.
    const { graph } = enrich(parse(REPRO))
    expect(stringify(graph)).toBe(REPRO)
  })

  it('preserves a BARE-config (v4) unresolvable ref verbatim — no npm: prefix added', () => {
    // v4 emits inner ranges BARE (`ghost: ^1.0.0`, not `"npm:^1.0.0"`). Because
    // the preserved range is the EXACT on-disk string (not the ladder's
    // normalized `npm:`-prefixed form), the bare shape round-trips byte-for-byte
    // — the distinct bare-emit path (rangeEmit: 'bare') must not re-prefix it.
    const H = 'a'.repeat(128)
    const F = 'f'.repeat(128)
    const SRC = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 4

"host@npm:1.0.0":
  version: 1.0.0
  resolution: "host@npm:1.0.0"
  dependencies:
    ghost: ^1.0.0
    present: 1.2.3
  checksum: ${H}
  languageName: node
  linkType: hard

"present@npm:1.2.3":
  version: 1.2.3
  resolution: "present@npm:1.2.3"
  checksum: ${F}
  languageName: node
  linkType: hard
`
    const out = stringifyV4(parseV4(SRC))
    expect(out).toContain('    ghost: ^1.0.0\n')
    expect(out).not.toContain('ghost: "npm:^1.0.0"')
    expect(out).toBe(SRC)
    // Diagnostic still fires on the bare-config path too.
    expect(parseV4(SRC).diagnostics().some(d => d.code === 'YARN_BERRY_UNRESOLVED_DEP' && d.message.includes('ghost'))).toBe(true)
  })
})

// #89 regression — the meta-block booleans inside `dependenciesMeta:` /
// `peerDependenciesMeta:` were emitted QUOTED (`optional: "true"`, `built:
// "false"`). yarn writes them BARE; `built: "false"` is moreover a TRUTHY
// non-empty string, inverting "do not build" → potential postinstall execution.
describe('yarn-berry meta-block booleans emit bare (#89 regression)', () => {
  const REPRO = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"some-pkg@npm:1.0.0":
  version: 1.0.0
  resolution: "some-pkg@npm:1.0.0"
  dependencies:
    esbuild: "npm:0.17.19"
    fsevents: "npm:2.3.3"
  dependenciesMeta:
    esbuild:
      built: false
    fsevents:
      optional: true
  peerDependencies:
    react: "*"
  peerDependenciesMeta:
    react:
      optional: true
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"esbuild@npm:0.17.19":
  version: 0.17.19
  resolution: "esbuild@npm:0.17.19"
  checksum: 10c0/aaa
  languageName: node
  linkType: hard

"fsevents@npm:2.3.3":
  version: 2.3.3
  resolution: "fsevents@npm:2.3.3"
  checksum: 10c0/fff
  languageName: node
  linkType: hard

"react@npm:18.2.0":
  version: 18.2.0
  resolution: "react@npm:18.2.0"
  checksum: 10c0/ddd
  languageName: node
  linkType: hard
`

  it('emits optional/built bare, never quoted', () => {
    const out = stringify(parse(REPRO))

    // BARE, as yarn writes them.
    expect(out).toContain('  dependenciesMeta:\n    esbuild:\n      built: false\n')
    expect(out).toContain('    fsevents:\n      optional: true\n')
    expect(out).toContain('  peerDependenciesMeta:\n    react:\n      optional: true\n')

    // NEVER the quoted (regressed) form for any meta boolean.
    expect(out).not.toContain('optional: "true"')
    expect(out).not.toContain('built: "false"')
    expect(out).not.toMatch(/^      (?:optional|built|unplugged): "(?:true|false)"$/m)
  })

  it('round-trips the meta booleans (bare → reparse → bare)', () => {
    const out = stringify(parse(REPRO))
    // The booleans survive a reparse (the unquoted bare scalar reads back as the
    // same `'true'`/`'false'` string and re-emits bare).
    expect(stringify(parse(out))).toContain('      built: false\n')
    expect(stringify(parse(out))).toContain('      optional: true\n')
  })

  it('is byte-stable across a double round-trip', () => {
    const once = stringify(parse(REPRO))
    const twice = stringify(parse(once))
    const thrice = stringify(parse(twice))
    expect(twice).toBe(once)
    expect(thrice).toBe(twice)
  })

  it('emits a `true`/`false` bin value BARE, like yarn, and round-trips byte-stably', () => {
    // yarn's SYML writer applies one uniform quoting rule (`simpleStringPattern`)
    // to EVERY scalar at every depth — no special-casing by key/nesting. A `bin`
    // target whose value is the token `true`/`false` therefore emits BARE, exactly
    // as yarn does (verified against the upstream yarnpkg-parsers writer). Our
    // parser reads every SYML scalar as a string, so the bare token reads back as
    // `'true'`/`'false'` and the lock stays byte-stable across reparses.
    const src = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!
__metadata:
  version: 8
  cacheKey: 10c0

"weird@npm:1.0.0":
  version: 1.0.0
  resolution: "weird@npm:1.0.0"
  bin:
    built: false
    optional: true
  checksum: 10c0/abc
  languageName: node
  linkType: hard
`
    const out = stringify(parse(src))
    // Bare in, bare out — matches yarn's uniform `simpleStringPattern` rule.
    expect(out).toContain('  bin:\n    built: false\n    optional: true\n')
    expect(out).not.toContain('built: "false"')
    expect(out).not.toContain('optional: "true"')
    // Byte-stable: the bare tokens survive reparse + re-emit unchanged.
    expect(stringify(parse(out))).toBe(out)
  })
})
