import { describe, expect, it } from 'vitest'
import {
  complete,
  modify,
  parse,
  stringify,
} from '../../main/ts/index.ts'
import { replaceRange } from '../../main/ts/modify/replace-range.ts'
import type { FormatId } from '../../main/ts/api/format-contract.ts'
import { parseBerryChecksum } from '../../main/ts/recipe/integrity.ts'
import type { RegistryAdapter } from '../../main/ts/registry/types.ts'
import { addEdge, addPackage, graphOf } from './_modify-test-utils.ts'

const CLASSIC_HEADER = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

`

describe('yarn-classic manifest descriptor anchors', () => {
  it('accepts package.json objects, omits workspace nodes, and drops stale key descriptors', () => {
    const lock = CLASSIC_HEADER + `escalade@^3.1.1, escalade@^3.1.2:
  version "3.2.0"
  resolved "https://registry.yarnpkg.com/escalade/-/escalade-3.2.0.tgz"
`
    const graph = parse(lock, 'yarn-classic', {
      manifests: {
        '': {
          name: 'app',
          version: '1.0.0',
          private: true,
          scripts: { test: 'vitest' },
          dependencies: { escalade: '^3.1.1' },
        },
      },
    })
    expect(graph.getNode('app@1.0.0')?.workspacePath).toBe('')
    const output = stringify(graph, 'yarn-classic')
    expect(output).toContain('escalade@^3.1.1:')
    expect(output).not.toContain('escalade@^3.1.2')
    expect(output).not.toContain('app@1.0.0:')
  })

  it('reports root descriptors as unanchored when manifests are absent', () => {
    const diagnostics: string[] = []
    parse(CLASSIC_HEADER + `foo@^1:
  version "1.0.0"
`, 'yarn-classic', {
      onDiagnostic: diagnostic => diagnostics.push(diagnostic.code),
    })
    expect(diagnostics).toContain('YARN_CLASSIC_ROOT_DESCRIPTORS_UNANCHORED')
  })

  it('itemizes every entry-key descriptor omitted by an incomplete manifest set', () => {
    const diagnostics: Array<{ code: string; subject?: unknown; data?: Record<string, unknown> }> = []
    const graph = parse(CLASSIC_HEADER + `foo@^1, foo@^2:
  version "2.0.0"
`, 'yarn-classic', {
      manifests: { '': { name: 'app', version: '1.0.0', dependencies: { foo: '^1' } } },
      onDiagnostic: diagnostic => diagnostics.push(diagnostic),
    })
    expect(diagnostics.filter(item => item.code === 'YARN_CLASSIC_ROOT_DESCRIPTOR_UNREQUESTED'))
      .toEqual([expect.objectContaining({
        code: 'YARN_CLASSIC_ROOT_DESCRIPTOR_UNREQUESTED',
        subject: 'foo@^2',
        data: { requestedBy: 'none' },
      })])
    expect(graph.diagnostics().filter(item => item.code === 'YARN_CLASSIC_ROOT_DESCRIPTOR_UNREQUESTED'))
      .toEqual([expect.objectContaining({ subject: 'foo@^2' })])
  })

  it.each([
    ['name', { version: '1.0.0' }],
    ['version', { name: 'real-package-shape' }],
    ['name and version', {}],
  ])('anchors every installable root declaration kind when the manifest omits %s', (_missing, identity) => {
    const lock = `${CLASSIC_HEADER}\n` + `dev-only@^1.0.0:
  version "1.0.0"

optional-only@^1.0.0:
  version "1.0.0"

peer-only@^1.0.0:
  version "1.0.0"

prod-only@^1.0.0:
  version "1.0.0"
`
    const graph = parse(lock, 'yarn-classic', {
      manifests: {
        '': {
          ...identity,
          private: true,
          packageManager: 'yarn@1.22.22',
          scripts: { test: 'vitest run' },
          dependencies: { 'prod-only': '^1.0.0' },
          devDependencies: { 'dev-only': '^1.0.0' },
          optionalDependencies: { 'optional-only': '^1.0.0' },
          peerDependencies: { 'peer-only': '^1.0.0' },
        },
      },
    })
    const root = [...graph.nodes()].find(node => node.workspacePath === '')
    expect(root).toBeDefined()
    expect(graph.out(root!.id).map(edge => edge.kind).sort()).toEqual([
      'dep',
      'dev',
      'optional',
    ])
    expect(graph.byName('peer-only')).toEqual([])
    expect(stringify(graph, 'yarn-classic')).toBe(lock.replace(`peer-only@^1.0.0:
  version "1.0.0"

`, ''))
  })

  it('synthesizes a versionless workspace identity and keeps its declarations live', () => {
    const lock = `${CLASSIC_HEADER}\n` + `lodash@4.17.11:
  version "4.17.11"
`
    const graph = parse(lock, 'yarn-classic', {
      manifests: {
        '': { name: 'root', private: true, workspaces: ['packages/*'] },
        'packages/foo': { name: 'foo', private: true, dependencies: { lodash: '4.17.11' } },
      },
    })
    const workspace = [...graph.nodes()].find(node => node.workspacePath === 'packages/foo')
    expect(workspace?.version).toBe('0.0.0-use.local')
    expect(graph.out(workspace!.id)).toHaveLength(1)
    expect(stringify(graph, 'yarn-classic')).toBe(lock)
  })

  it('drops the full c8 closure omitted from a real-shaped root manifest and reaches a strict fixpoint', () => {
    const lock = `${CLASSIC_HEADER}\n` + `@bcoe/v8-coverage@^0.2.3:
  version "0.2.3"

c8@^10.1.3:
  version "10.1.3"
  dependencies:
    "@bcoe/v8-coverage" ^0.2.3
    foreground-child ^1.0.0

foreground-child@^1.0.0:
  version "1.0.0"

live-dev@^2.0.0:
  version "2.0.0"
`
    const manifests = {
      '': {
        name: 'thromise',
        version: '1.0.0',
        devDependencies: { 'live-dev': '^2.0.0' },
      },
    }
    const diagnostics: Array<{ code: string; subject?: unknown; data?: Record<string, unknown> }> = []
    const graph = parse(lock, 'yarn-classic', {
      manifests,
      onDiagnostic: diagnostic => diagnostics.push(diagnostic),
    })
    expect(Array.from(graph.nodes(), node => node.name).sort()).toEqual(['live-dev', 'thromise'])
    expect(diagnostics.filter(item => item.code === 'YARN_CLASSIC_ROOT_DESCRIPTOR_UNREQUESTED'))
      .toEqual([
        expect.objectContaining({
          subject: '@bcoe/v8-coverage@^0.2.3',
          data: { requestedBy: 'unreachable-entry-only' },
        }),
        expect.objectContaining({
          subject: 'c8@^10.1.3',
          data: { requestedBy: 'none' },
        }),
        expect.objectContaining({
          subject: 'foreground-child@^1.0.0',
          data: { requestedBy: 'unreachable-entry-only' },
        }),
      ])

    const once = stringify(graph, 'yarn-classic', { strict: true })
    expect(once).toContain('live-dev@^2.0.0:')
    expect(once).not.toContain('c8@')
    expect(once).not.toContain('foreground-child@')
    expect(once).not.toContain('@bcoe/v8-coverage@')
    const reparsed = parse(once, 'yarn-classic', { manifests })
    expect(stringify(reparsed, 'yarn-classic', { strict: true })).toBe(once)
    expect(Array.from(reparsed.nodes(), node => node.id))
      .toEqual(Array.from(graph.nodes(), node => node.id))
  })

  it('prunes several stale root closures while preserving a live mixed descriptor entry', () => {
    const lock = `${CLASSIC_HEADER}\n` + `deep-stale@^1.0.0:
  version "1.0.0"

live@^2.0.0, live@^3.0.0, live@>=3:
  version "3.0.0"

stale-a@^1.0.0:
  version "1.0.0"
  dependencies:
    deep-stale ^1.0.0
    live ">=3"

stale-b@^1.0.0:
  version "1.0.0"
  dependencies:
    deep-stale ^1.0.0
`
    const manifests = {
      '': { name: 'mixin-root', version: '1.0.0', dependencies: { live: '^3.0.0' } },
    }
    const diagnostics: Array<{ code: string; subject?: unknown; data?: Record<string, unknown> }> = []
    const graph = parse(lock, 'yarn-classic', {
      manifests,
      onDiagnostic: diagnostic => diagnostics.push(diagnostic),
    })
    expect(Array.from(graph.nodes(), node => node.name).sort()).toEqual(['live', 'mixin-root'])
    expect(diagnostics.filter(item => item.code === 'YARN_CLASSIC_ROOT_DESCRIPTOR_UNREQUESTED'))
      .toEqual([
        expect.objectContaining({
          subject: 'deep-stale@^1.0.0',
          data: { requestedBy: 'unreachable-entry-only' },
        }),
        expect.objectContaining({
          subject: 'live@>=3',
          data: { requestedBy: 'unreachable-entry-only' },
        }),
        expect.objectContaining({ subject: 'live@^2.0.0', data: { requestedBy: 'none' } }),
        expect.objectContaining({ subject: 'stale-a@^1.0.0', data: { requestedBy: 'none' } }),
        expect.objectContaining({ subject: 'stale-b@^1.0.0', data: { requestedBy: 'none' } }),
      ])
    const once = stringify(graph, 'yarn-classic', { strict: true })
    expect(once).toContain('live@^3.0.0:')
    expect(once).not.toContain('live@^2.0.0')
    expect(once).not.toContain('live@>=3')
    expect(once).not.toContain('stale-a@')
    expect(once).not.toContain('stale-b@')
    expect(once).not.toContain('deep-stale@')
    expect(stringify(parse(once, 'yarn-classic', { manifests }), 'yarn-classic', { strict: true }))
      .toBe(once)
  })

  it('visibly itemizes and prunes a workspace whose manifest was omitted', () => {
    const lock = `${CLASSIC_HEADER}\n` + `omitted-child@^1.0.0:
  version "1.0.0"

omitted-workspace@1.0.0:
  version "1.0.0"
  resolved "file:packages/omitted"
  dependencies:
    omitted-child ^1.0.0
`
    const manifests = {
      '': { name: 'workspace-root', version: '1.0.0', private: true, workspaces: ['packages/*'] },
    }
    const diagnostics: Array<{ code: string; subject?: unknown; data?: Record<string, unknown> }> = []
    const graph = parse(lock, 'yarn-classic', {
      manifests,
      onDiagnostic: diagnostic => diagnostics.push(diagnostic),
    })
    expect(Array.from(graph.nodes(), node => node.name)).toEqual(['workspace-root'])
    expect(diagnostics.filter(item => item.code === 'YARN_CLASSIC_ROOT_DESCRIPTOR_UNREQUESTED'))
      .toEqual([
        expect.objectContaining({
          subject: 'omitted-child@^1.0.0',
          data: { requestedBy: 'unreachable-entry-only' },
        }),
        expect.objectContaining({
          subject: 'omitted-workspace@1.0.0',
          data: { requestedBy: 'none' },
        }),
      ])
    const once = stringify(graph, 'yarn-classic', { strict: true })
    expect(once).toBe(`${CLASSIC_HEADER}\n`)
    expect(stringify(parse(once, 'yarn-classic', { manifests }), 'yarn-classic', { strict: true }))
      .toBe(once)
  })

  it('counts a governed edge by its declared descriptor under manifest anchors', () => {
    const lock = `${CLASSIC_HEADER}\n` + `consumer@1.0.0:
  version "1.0.0"
  dependencies:
    postcss ^8.2.1

postcss@8.2.15, postcss@^8.2.1:
  version "8.2.15"
`
    const manifests = {
      '': {
        name: 'resolution-root',
        version: '1.0.0',
        dependencies: { consumer: '1.0.0' },
        resolutions: { postcss: '8.2.15' },
      },
    }
    const diagnostics: string[] = []
    const graph = parse(lock, 'yarn-classic', {
      manifests,
      onDiagnostic: diagnostic => diagnostics.push(diagnostic.code),
    })
    expect(diagnostics).not.toContain('YARN_CLASSIC_ROOT_DESCRIPTOR_UNREQUESTED')
    const consumer = Array.from(graph.nodes()).find(node => node.name === 'consumer')
    expect(consumer).toBeDefined()
    expect(graph.out(consumer!.id)[0]?.attributes?.range).toBe('^8.2.1')
    const once = stringify(graph, 'yarn-classic', { strict: true })
    expect(once).toContain('postcss@^8.2.1:')
    expect(once).toContain('postcss@8.2.15')
    expect(stringify(parse(once, 'yarn-classic', { manifests }), 'yarn-classic', { strict: true }))
      .toBe(once)
  })

  it('does not create lock entries from workspace-member peerDependencies', () => {
    const lock = `${CLASSIC_HEADER}\n` + `eslint@^5.0.0:
  version "5.16.0"

neutrino@^9.0.0, neutrino@^9.0.0-0:
  version "9.0.0"
`
    const manifests = {
      '': { name: 'neutrino-root', version: '1.0.0', private: true, workspaces: ['packages/*'] },
      'packages/preset': {
        name: 'preset',
        version: '1.0.0',
        peerDependencies: { eslint: '^5.0.0', neutrino: '^9.0.0' },
      },
    }
    const graph = parse(lock, 'yarn-classic', { manifests })
    expect(Array.from(graph.nodes(), node => node.name).sort()).toEqual([
      'neutrino-root',
      'preset',
    ])
    const preset = Array.from(graph.nodes()).find(node => node.name === 'preset')
    expect(preset).toBeDefined()
    expect(graph.out(preset!.id)).toEqual([])
    const once = stringify(graph, 'yarn-classic', { strict: true })
    expect(once).toBe(`${CLASSIC_HEADER}\n`)
    expect(stringify(parse(once, 'yarn-classic', { manifests }), 'yarn-classic', { strict: true }))
      .toBe(once)
  })

  it('does not add a root peer descriptor beside a live dev descriptor', () => {
    const lock = `${CLASSIC_HEADER}\n` + `is-number@^7.0.0:
  version "7.0.0"
`
    const manifests = {
      '': {
        name: 'peer-and-dev-root',
        version: '1.0.0',
        peerDependencies: { 'is-number': '>=6' },
        devDependencies: { 'is-number': '^7.0.0' },
      },
    }
    const graph = parse(lock, 'yarn-classic', { manifests })
    expect(graph.byName('is-number')).toHaveLength(1)
    expect(stringify(graph, 'yarn-classic', { strict: true })).toBe(lock)
  })

  it('does not retain a closure reachable only through a root peer declaration', () => {
    const lock = `${CLASSIC_HEADER}\n` + `peer-child@^1.0.0:
  version "1.0.0"

peer-only@^1.0.0:
  version "1.0.0"
  dependencies:
    peer-child ^1.0.0
`
    const manifests = {
      '': {
        name: 'peer-root',
        version: '1.0.0',
        peerDependencies: { 'peer-only': '^1.0.0' },
      },
    }
    const diagnostics: Array<{ code: string; subject?: unknown; data?: Record<string, unknown> }> = []
    const graph = parse(lock, 'yarn-classic', {
      manifests,
      onDiagnostic: diagnostic => diagnostics.push(diagnostic),
    })
    expect(Array.from(graph.nodes(), node => node.name)).toEqual(['peer-root'])
    expect(diagnostics.filter(item => item.code === 'YARN_CLASSIC_ROOT_DESCRIPTOR_UNREQUESTED'))
      .toEqual([
        expect.objectContaining({
          subject: 'peer-child@^1.0.0',
          data: { requestedBy: 'unreachable-entry-only' },
        }),
        expect.objectContaining({
          subject: 'peer-only@^1.0.0',
          data: { requestedBy: 'none' },
        }),
      ])
    const once = stringify(graph, 'yarn-classic', { strict: true })
    expect(once).toBe(`${CLASSIC_HEADER}\n`)
    expect(stringify(parse(once, 'yarn-classic', { manifests }), 'yarn-classic', { strict: true }))
      .toBe(once)
  })
})

describe('modify replaceRange', () => {
  it('treats npm: as optional in a Yarn from guard', async () => {
    const graph = graphOf(builder => {
      const root = addPackage(builder, { name: 'app', version: '1.0.0', workspacePath: '' })
      const foo = addPackage(builder, { name: 'foo', version: '1.0.0' })
      addEdge(builder, root, foo, 'dep', 'npm:^1')
    })
    const registry: RegistryAdapter = {
      async packument() { return undefined },
      async resolve(name) { return { name, version: '1.0.0' } },
    }
    const result = await replaceRange(graph, {
      parent: 'app@1.0.0',
      name: 'foo',
      from: '^1',
      to: '^1',
    }, 'yarn-berry-v8', { registry })
    expect(result.graph.out('app@1.0.0')[0]?.attrs?.range).toBe('^1')
  })

  it('moves a declaration before its future target can be resolved', async () => {
    const graph = graphOf(builder => {
      const root = addPackage(builder, { name: 'app', version: '1.0.0', workspacePath: '' })
      const foo = addPackage(builder, { name: 'foo', version: '1.0.0' })
      addEdge(builder, root, foo, 'dep', '^1')
    })
    const registry: RegistryAdapter = {
      async packument() { return undefined },
      async resolve() { return undefined },
    }
    const result = await replaceRange(graph, {
      parent: 'app@1.0.0',
      name: 'foo',
      from: '^1',
      to: '^2',
    }, 'yarn-classic', { registry })
    expect(result.graph.out('app@1.0.0')[0]?.attrs?.range).toBe('^2')
    expect(result.unresolved).toEqual([
      expect.objectContaining({ code: 'MODIFY_RESOLVE_FAILED' }),
      expect.objectContaining({ code: 'MODIFY_RANGE_PENDING' }),
    ])
  })

  it('moves one Classic workspace declaration and leaves its sibling untouched', async () => {
    const lock = CLASSIC_HEADER + `debug@^1:
  version "1.0.0"

debug@^2:
  version "2.0.0"

debug@^3:
  version "3.0.0"
`
    const graph = parse(lock, 'yarn-classic', {
      manifests: {
        '': { name: 'root', version: '1.0.0', workspaces: ['a', 'b', 'c'] },
        a: { name: 'a', version: '1.0.0', dependencies: { debug: '^1' } },
        b: { name: 'b', version: '1.0.0', dependencies: { debug: '^2' } },
        c: { name: 'c', version: '1.0.0', dependencies: { debug: '^3' } },
      },
    })
    const modified = await modify(graph, {
      kind: 'replaceRange',
      parent: 'a@1.0.0',
      name: 'debug',
      from: '^1',
      to: '^3',
    }, { target: 'yarn-classic' })
    const completed = await complete(modified.graph, {
      target: 'yarn-classic',
      seed: modified.frontier,
      pruneOrphans: true,
    })
    expect(completed.graph.out('a@1.0.0')[0]?.attributes?.range).toBe('^3')
    expect(completed.graph.out('b@1.0.0')[0]?.attributes?.range).toBe('^2')
    const output = stringify(completed.graph, 'yarn-classic')
    expect(output).toContain('debug@^2:')
    expect(output).toContain('debug@^3:')
    expect(output).not.toContain('debug@^1:')
    expect(output).not.toContain('root@1.0.0:')
    expect(output).not.toContain('a@1.0.0:')
    expect(output).not.toContain('b@1.0.0:')
    expect(output).not.toContain('c@1.0.0:')
  })

  it('updates Berry declaration and descriptor together', async () => {
    const lock = `__metadata:
  version: 8
  cacheKey: 10c0

"app@workspace:.":
  version: 0.0.0-use.local
  resolution: "app@workspace:."
  dependencies:
    debug: "npm:^1"
  languageName: unknown
  linkType: soft

"debug@npm:^1":
  version: 1.0.0
  resolution: "debug@npm:1.0.0"
  languageName: node
  linkType: hard

"debug@npm:^2":
  version: 2.0.0
  resolution: "debug@npm:2.0.0"
  languageName: node
  linkType: hard
`
    const graph = parse(lock, 'yarn-berry-v8')
    const modified = await modify(graph, {
      kind: 'replaceRange',
      parent: 'app@0.0.0-use.local',
      name: 'debug',
      from: '^1',
      to: '^2',
    }, { target: 'yarn-berry-v8' })
    const completed = await complete(modified.graph, {
      target: 'yarn-berry-v8',
      seed: modified.frontier,
      pruneOrphans: true,
    })
    const output = stringify(completed.graph, 'yarn-berry-v8', { strict: false })
    expect(output).toContain('debug: "npm:^2"')
    expect(output).toContain('"debug@npm:^2":')
    expect(output).not.toContain('"debug@npm:^1":')
  })

  it('enforces from and rejects non-Yarn targets', async () => {
    const lock = CLASSIC_HEADER + `foo@^1:
  version "1.0.0"
`
    const graph = parse(lock, 'yarn-classic', {
      manifests: { '': { name: 'app', version: '1.0.0', dependencies: { foo: '^1' } } },
    })
    await expect(modify(graph, {
      kind: 'replaceRange', parent: 'app@1.0.0', name: 'foo', from: '^2', to: '^1',
    }, { target: 'yarn-classic' })).rejects.toMatchObject({ code: 'INVALID_INPUT' })
    await expect(modify(graph, {
      kind: 'replaceRange', parent: 'app@1.0.0', name: 'foo', to: '^1',
    }, { target: 'npm-3' })).rejects.toMatchObject({ code: 'CAPABILITY_LACK' })
  })

  it.each([
    ['Classic', 'yarn-classic' as const],
    ['Berry', 'yarn-berry-v6' as const],
  ])('%s refuses a pending incompatible binding until the yaf sequence settles it', async (_label, format) => {
    const graph = pendingRangeGraph(format, '^1.0.0')
    const parent = [...graph.nodes()].find(node => node.workspacePath === '')!.id
    let resolveCalls = 0
    const registry: RegistryAdapter = {
      async packument(name) {
        if (name !== 'vuln') return undefined
        const version = {
          name,
          version: '2.0.0',
          tarball: 'https://registry.yarnpkg.com/vuln/-/vuln-2.0.0.tgz',
          ...(format.startsWith('yarn-berry-')
            ? { integrity: parseBerryChecksum('0'.repeat(128)).integrity }
            : {}),
        }
        return {
          name,
          distTags: { latest: '2.0.0' },
          versions: { '2.0.0': version },
        }
      },
      async resolve(name) {
        resolveCalls += 1
        return resolveCalls === 1 ? undefined : {
          name,
          version: '2.0.0',
          tarball: 'https://registry.yarnpkg.com/vuln/-/vuln-2.0.0.tgz',
          ...(format.startsWith('yarn-berry-')
            ? { integrity: parseBerryChecksum('0'.repeat(128)).integrity }
            : {}),
        }
      },
      async manifest(name, version) { return { name, version } },
    }
    const pending = await modify(graph, {
      kind: 'replaceRange', parent, name: 'vuln', to: '^2.0.0',
    }, { target: format, sources: { packuments: [{
      async packument() { return undefined },
      async resolve() { return undefined },
    }] } })
    expect(() => stringify(pending.graph, format)).toThrowError(expect.objectContaining({
      code: 'IRREDUCIBLE_LOSS',
      message: expect.stringContaining(`${parent} declares vuln@^2.0.0`),
      losses: expect.arrayContaining([expect.objectContaining({
        feature: 'modify:replace-range-pending',
        reason: 'MODIFY_RANGE_PENDING',
      })]),
    }))
    const nonStrictDiagnostics: string[] = []
    expect(stringify(pending.graph, format, {
      strict: false,
      onDiagnostic: diagnostic => nonStrictDiagnostics.push(diagnostic.code),
    })).toContain('vuln')
    expect(nonStrictDiagnostics).toContain('MODIFY_RANGE_PENDING')

    const modified = await modify(graph, [
      { kind: 'replaceRange', parent, name: 'vuln', to: '^2.0.0' },
      { kind: 'replaceVersion', selector: { name: 'vuln', fromRange: '^1.0.0' }, to: '2.0.0' },
    ], { target: format, sources: { packuments: [registry] } })
    const completed = await complete(modified.graph, {
      target: format,
      seed: modified.frontier,
      sources: { packuments: [registry] },
    })
    expect(() => stringify(completed.graph, format)).not.toThrow()
    expect(completed.graph.out(parent)[0]).toMatchObject({
      target: 'vuln@2.0.0',
      attributes: { range: '^2.0.0' },
    })
  })

  it.each([
    ['Classic npm protocol', 'yarn-classic' as const, 'npm:^1.0.0', 'npm:^2.0.0', 'vuln'],
    ['Berry npm protocol', 'yarn-berry-v6' as const, 'npm:^1.0.0', 'npm:^2.0.0', 'vuln'],
    ['Classic alias', 'yarn-classic' as const, 'npm:vuln@^1.0.0', 'npm:vuln@^2.0.0', 'safe-vuln'],
    ['Berry alias', 'yarn-berry-v6' as const, 'npm:vuln@^1.0.0', 'npm:vuln@^2.0.0', 'safe-vuln'],
  ])('%s keeps the pending guard on protocol and alias declarations', async (
    _label,
    format,
    from,
    to,
    name,
  ) => {
    const graph = pendingRangeGraph(format, from, name)
    const parent = [...graph.nodes()].find(node => node.workspacePath === '')!.id
    const registry: RegistryAdapter = {
      async packument() { return undefined },
      async resolve() { return undefined },
    }
    const result = await modify(graph, {
      kind: 'replaceRange', parent, name, from, to,
    }, { target: format, sources: { packuments: [registry] } })
    expect(() => stringify(result.graph, format)).toThrowError(expect.objectContaining({
      code: 'IRREDUCIBLE_LOSS',
    }))
    expect(result.graph.diagnostics()).toContainEqual(expect.objectContaining({
      code: 'MODIFY_RANGE_PENDING',
      data: expect.objectContaining({ parent, name, declaredRange: to }),
    }))
  })
})

function pendingRangeGraph(format: FormatId, range: string, declaredName = 'vuln') {
  if (format === 'yarn-classic') {
    return parse(`${CLASSIC_HEADER}${declaredName}@${range}:
  version "1.0.0"
`, format, {
      manifests: {
        '': { name: 'app', version: '1.0.0', dependencies: { [declaredName]: range } },
      },
    })
  }
  const entryRange = declaredName === 'vuln'
    ? `npm:${range.startsWith('npm:') ? range.slice('npm:'.length) : range}`
    : range
  const lockfileVersion = format.slice('yarn-berry-v'.length)
  const checksum = `${format === 'yarn-berry-v6' ? '' : '10c0/'}${'0'.repeat(128)}`
  return parse(`__metadata:
  version: ${lockfileVersion}

"app@workspace:.":
  version: 0.0.0-use.local
  resolution: "app@workspace:."
  dependencies:
    ${declaredName}: "${range}"
  languageName: unknown
  linkType: soft

"${declaredName}@${entryRange}":
  version: 1.0.0
  resolution: "vuln@npm:1.0.0"
  checksum: ${checksum}
  languageName: node
  linkType: hard
`, format)
}
