// Bug #104 — yarn-berry lock-borne PATCH PREFERENCE (Rung-3 overlay).
//
// yarn's `patchedDependencies` (root manifest) makes every consumer of a base
// package resolve to a sibling PATCH copy of the same `name@version`. The lock
// records BOTH a base `<name>@npm:<ver>` node and an `<name>@patch:…` sibling;
// a consumer declaring a plain `npm:` range binds the base (Rung 0/3) and the
// overlay then redirects it onto the patched copy — leaving the base at
// in-degree 0. yarn KEEPS that base entry regardless (it is the patch's install
// source — verified across fsevents / interpret / ast-types / lru-cache locks,
// and a real `yarn install --immutable` rejects a lock with the base dropped),
// so the GC PRESERVES a bare base while its patched variant is live. Shape mined
// from the real highlight/highlight lock (bufrw → ansi-color@npm:^0.2.1, base +
// patch sibling).
//
// Classic flattens patches (no `patch:` protocol) so it is unaffected — covered
// only here for berry.

import { describe, expect, it } from 'vitest'
import { parse, stringify } from '../../main/ts/index.ts'
import { optimize } from '../../main/ts/optimize/optimize.ts'
import type { Graph, Manifest } from '../../main/ts/graph.ts'

// bufrw declares `ansi-color: "npm:^0.2.1"`. The lock carries the BASE
// `ansi-color@npm:0.2.1` AND a sibling patch `ansi-color@patch:…0.2.1…`. Neither
// entry is keyed by `ansi-color@npm:^0.2.1`, so the consumer misses Rung 0 and
// resolves the base via Rung 3 (single eligible tarball) — then the overlay
// redirects to the patch.
const LOCK = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    bufrw: "npm:^1.3.0"
  languageName: unknown
  linkType: soft

"bufrw@npm:^1.3.0":
  version: 1.4.0
  resolution: "bufrw@npm:1.4.0"
  dependencies:
    ansi-color: "npm:^0.2.1"
  languageName: node
  linkType: hard

"ansi-color@npm:0.2.1":
  version: 0.2.1
  resolution: "ansi-color@npm:0.2.1"
  checksum: 10/5e08767ae19f6e5b5717b800e3cba259600b913f04678076718abe5dccad25f66639aa3c6872a08365b18675b18c1f6d781638137d03da3f9da6a5394869c71c
  languageName: node
  linkType: hard

"ansi-color@patch:ansi-color@npm%3A0.2.1#./.yarn/patches/ansi-color-npm-0.2.1-f7243d10a4.patch::locator=root%40workspace%3A.":
  version: 0.2.1
  resolution: "ansi-color@patch:ansi-color@npm%3A0.2.1#./.yarn/patches/ansi-color-npm-0.2.1-f7243d10a4.patch::version=0.2.1&hash=b45cea&locator=root%40workspace%3A."
  checksum: 10/89efd6c95a858a95ae4f023269a8dd75b12a5fec88de52b0953361975ba71f56ec904ed17971a73bad5a3ac1832931fc49b57ade078a5d9865fe98388d4e4a38
  languageName: node
  linkType: hard
`

const BUFRW = 'bufrw@1.4.0'
const ANSI_BASE = 'ansi-color@0.2.1'

function ansiTarget(g: Graph): string | undefined {
  return g.out(BUFRW).find(e => g.getNode(e.dst)?.name === 'ansi-color')?.dst
}

describe('Bug #104 — yarn-berry patch preference (lock-borne)', () => {
  it('redirects the consumer from the base onto the sibling patch node', () => {
    const g = parse('yarn-berry-v8', LOCK)
    const dst = ansiTarget(g)
    expect(dst).toBeDefined()
    // The bound node is the PATCH (node.patch set), not the bare base.
    expect(g.getNode(dst!)?.patch).toBeDefined()
    expect(dst).not.toBe(ANSI_BASE)
    // It is still ansi-color@0.2.1 underneath (same name@version, patched copy).
    expect(g.getNode(dst!)?.name).toBe('ansi-color')
    expect(g.getNode(dst!)?.version).toBe('0.2.1')
  })

  it('emits the observable `_PATCH_PREFERRED` info on the consumer (no override needed)', () => {
    const g = parse('yarn-berry-v8', LOCK)
    const d = g.diagnostics().find(x => x.code === 'YARN_BERRY_V8_PATCH_PREFERRED' && x.subject === BUFRW)
    expect(d).toBeDefined()
    expect(d?.severity).toBe('info')
    expect(d?.message).toMatch(/ansi-color=npm:\^0\.2\.1/)
  })

  it('keeps the base node — GC preserves a bare base while its patch sibling is live', () => {
    const g = parse('yarn-berry-v8', LOCK)
    // The base node has no incoming dep edge (the only consumer was redirected to
    // the patch) — yet yarn keeps the base entry: it is the patch's install
    // source (both `@npm:` and `@patch:` entries are in a valid lock, and
    // `yarn install --immutable` fails if the base is dropped).
    expect(g.getNode(ANSI_BASE)).toBeDefined()
    expect(g.in(ANSI_BASE).filter(e => e.kind === 'dep' || e.kind === 'optional').length).toBe(0)
    // optimize() must PRESERVE the orphaned base while the patch sibling is live
    // (patch-base preservation); the patch node also survives (reachable via bufrw).
    const opt = optimize(g).graph
    expect(opt.getNode(ANSI_BASE)).toBeDefined()
    const patchId = ansiTarget(g)
    expect(opt.getNode(patchId!)).toBeDefined()
  })

  it('round-trips: the patched edge survives parse→stringify→parse', () => {
    const g = parse('yarn-berry-v8', LOCK)
    const out = stringify('yarn-berry-v8', g, { strict: false })
    const g2 = parse('yarn-berry-v8', out)
    const dst2 = ansiTarget(g2)
    expect(dst2).toBeDefined()
    expect(g2.getNode(dst2!)?.patch).toBeDefined()
  })

  it('does NOT fire when the base has no patch sibling (plain bind, no redirect)', () => {
    // Drop the patch entry → bufrw binds the plain base, no overlay.
    const noPatch = LOCK.slice(0, LOCK.indexOf('"ansi-color@patch:'))
    const g = parse('yarn-berry-v8', noPatch)
    expect(ansiTarget(g)).toBe(ANSI_BASE)
    expect(g.getNode(ANSI_BASE)?.patch).toBeUndefined()
    expect(g.diagnostics().some(d => d.code === 'YARN_BERRY_V8_PATCH_PREFERRED')).toBe(false)
  })

  it('with manifests, the OVERRIDE rung redirects — the overlay does NOT double-fire', () => {
    // A `resolutions` pin forcing ansi-color onto the patch. WITH manifests the
    // Rung-2 override binds the patch directly (boundViaOverride), so the overlay
    // is skipped and NO `_PATCH_PREFERRED` fires (no double-redirect). The edge
    // still lands on the patch node.
    const manifests: Record<string, Manifest> = {
      '': {
        name: 'root',
        native: {
          yarnResolutions: {
            'ansi-color@npm:^0.2.1':
              'patch:ansi-color@npm%3A0.2.1#./.yarn/patches/ansi-color-npm-0.2.1-f7243d10a4.patch',
          },
        },
      },
    }
    const g = parse('yarn-berry-v8', LOCK, { manifests })
    const dst = ansiTarget(g)
    expect(g.getNode(dst!)?.patch).toBeDefined() // still the patch (via override)
    // The override path fires no `_PATCH_PREFERRED` (the overlay saw boundViaOverride).
    expect(g.diagnostics().some(d => d.code === 'YARN_BERRY_V8_PATCH_PREFERRED')).toBe(false)
  })
})
