// yaf lockgraph-message (round 3): a `catalog:` descriptor was not resolved to
// an edge in the berry adapter, so a cataloged dep (vitest) looked orphaned and
// an unseeded GC cascaded its whole subtree (vitest → vite → rolldown →
// bindings, 57 nodes on the strapi lock). The catalog maps `catalog:` to a
// concrete range OUTSIDE the lockfile, but the lock already carries the single
// resolved entry — so Rung 3.6 binds the unique registry sibling of that name.

import { describe, expect, it } from 'vitest'
import { parse, stringify } from '../../main/ts/index.ts'
import { pruneOrphans } from '../../main/ts/optimize/prune.ts'

const CK = '10c0/d924b57e7312b3b63ad21fc5b3dc0af5e78d61a1fc7cfb5457edaf26326bf62be5307cc87ffb6862ef1c2b33b0233cdb5d4f01c4c958cc0d660948b65a287a48'

// Two workspaces reference vitest via `catalog:` (default catalog); a named
// catalog (`catalog:tools`) is exercised too. The lock carries ONE vitest entry
// (the catalog-mapped `^4.0.18` → 4.1.5) plus its subtree.
const LOCK = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    eslint: "catalog:tools"
    vitest: "catalog:"
  languageName: unknown
  linkType: soft

"app@workspace:packages/app":
  version: 0.0.0-use.local
  resolution: "app@workspace:packages/app"
  dependencies:
    vitest: "catalog:"
  languageName: unknown
  linkType: soft

"vitest@npm:^4.0.18":
  version: 4.1.5
  resolution: "vitest@npm:4.1.5"
  dependencies:
    "@vitest/runner": "npm:4.1.5"
  checksum: ${CK}
  languageName: node
  linkType: hard

"@vitest/runner@npm:4.1.5":
  version: 4.1.5
  resolution: "@vitest/runner@npm:4.1.5"
  checksum: ${CK}
  languageName: node
  linkType: hard

"eslint@npm:^9.0.0":
  version: 9.20.0
  resolution: "eslint@npm:9.20.0"
  checksum: ${CK}
  languageName: node
  linkType: hard
`

describe('yarn-berry: catalog: protocol resolves to an edge (Rung 3.6)', () => {
  it('binds a catalog: / catalog:<name> descriptor to the unique sibling', () => {
    const g = parse('yarn-berry-v8', LOCK)

    // both workspaces' `vitest: "catalog:"` resolve to the single vitest entry.
    expect(g.out('root@0.0.0-use.local').some(e => e.dst === 'vitest@4.1.5')).toBe(true)
    expect(g.out('app@0.0.0-use.local').some(e => e.dst === 'vitest@4.1.5')).toBe(true)
    expect(g.in('vitest@4.1.5').length).toBe(2)
    // a NAMED catalog (`catalog:tools`) binds the same way.
    expect(g.out('root@0.0.0-use.local').some(e => e.dst === 'eslint@9.20.0')).toBe(true)
  })

  it('keeps the cataloged subtree under an unseeded GC (was cascaded away)', () => {
    const g = parse('yarn-berry-v8', LOCK)
    const pruned = pruneOrphans(g)
    expect(pruned.graph.getNode('vitest@4.1.5')).toBeDefined()
    expect(pruned.graph.getNode('@vitest/runner@4.1.5')).toBeDefined()
    expect(pruned.graph.getNode('eslint@9.20.0')).toBeDefined()
    expect(pruned.removed).toEqual([])
  })

  it('round-trips the catalog: descriptor verbatim (resolving the edge must not rewrite it)', () => {
    const out = stringify('yarn-berry-v8', parse('yarn-berry-v8', LOCK))
    // The resolved edge keeps the ORIGINAL `catalog:` descriptor on emit — yarn
    // must read back its own `catalog:` token, never a synthesized npm: range.
    // (Full-lock byte-identity is covered by the real-world corpus round-trips;
    // here the point is that catalog edge-resolution does not rewrite the value.)
    expect(out).toContain('    vitest: "catalog:"')
    expect(out).toContain('    eslint: "catalog:tools"')
    expect(out).not.toMatch(/vitest: "npm:/)   // not rewritten to the resolved range
  })
})
