// Bug #99 — descriptor→node resolution LADDER, wired into the yarn-family edge
// resolvers (berry `addEdgesFromBlock`, classic `addEdgesFromMap`).
//
// Under a `resolutions` pin, yarn rewrites a consumer's dependency entry key to
// the PINNED descriptor and drops the consumer's own range. A range consumer can
// then no longer find its entry by exact key (Rung 0), so the edge was dropped,
// the node orphaned, and the dependency vanished on round-trip. The ladder adds:
//   - Rung 2: override-map forced link (handles a NON-satisfying pin) — needs
//     `ParseOptions.manifests` (yarn writes no lock-borne resolutions);
//   - Rung 3: source-gated max-satisfying semver (handles the satisfying slice).

import { describe, expect, it } from 'vitest'
import { parse, stringify } from '../../main/ts/index.ts'
import type { Graph, Manifest } from '../../main/ts/graph.ts'

// === yarn-berry minimal repro ===============================================
//
// Two csstype entries: a PINNED `csstype@npm:3.0.9` (the key a `resolutions`
// rewrite produced) and a `csstype@npm:^2.5.2` → 2.6.21. The root consumer
// declares THREE csstype descriptors none of which key any entry directly:
//   - `npm:^3.1.3`  — NON-satisfying vs 3.0.9 → only the override can bridge;
//   - `npm:^2.6.0`  — satisfying vs 2.6.21    → Rung-3 semver bridges (no manifest);
//   - `npm:^3.0.2`  — satisfying vs 3.0.9 but NOT 2.6.21 → Rung-3 picks 3.0.9.
const BERRY_LOCK = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10

"csstype@npm:3.0.9":
  version: 3.0.9
  resolution: "csstype@npm:3.0.9"
  languageName: node
  linkType: hard

"csstype@npm:^2.5.2":
  version: 2.6.21
  resolution: "csstype@npm:2.6.21"
  languageName: node
  linkType: hard

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    csstype: "npm:^3.1.3"
  languageName: unknown
  linkType: soft

"consumer-a@npm:1.0.0":
  version: 1.0.0
  resolution: "consumer-a@npm:1.0.0"
  dependencies:
    csstype: "npm:^2.6.0"
  languageName: node
  linkType: hard

"consumer-b@npm:1.0.0":
  version: 1.0.0
  resolution: "consumer-b@npm:1.0.0"
  dependencies:
    csstype: "npm:^3.0.2"
  languageName: node
  linkType: hard
`

// Root manifest carrying the version-conditioned yarn `resolutions` (the only
// place yarn records a pin — the lock carries none).
const BERRY_MANIFESTS: Record<string, Manifest> = {
  '': {
    name: 'root',
    native: {
      yarnResolutions: {
        'csstype@npm:^3.1.3': '3.0.9',
      },
    },
  },
}

const CSSTYPE_309 = 'csstype@3.0.9'
const CSSTYPE_2621 = 'csstype@2.6.21'
const ROOT = 'root@0.0.0-use.local'
const CONSUMER_A = 'consumer-a@1.0.0'
const CONSUMER_B = 'consumer-b@1.0.0'

function edgeFromTo(g: Graph, src: string, dstName: string): string | undefined {
  return g.out(src).find(e => g.getNode(e.dst)?.name === dstName)?.dst
}

describe('Bug #99 — yarn-berry resolution ladder', () => {
  it('Rung 3 (semver, no manifests): a SATISFYING range resolves to the right pinned node', () => {
    const g = parse('yarn-berry-v8', BERRY_LOCK)
    // consumer-a `^2.6.0` → 2.6.21 (the only satisfying tarball)
    expect(edgeFromTo(g, CONSUMER_A, 'csstype')).toBe(CSSTYPE_2621)
    // consumer-b `^3.0.2` → 3.0.9 (satisfies ^3.0.2; 2.6.21 does not)
    expect(edgeFromTo(g, CONSUMER_B, 'csstype')).toBe(CSSTYPE_309)
  })

  it('Rung 4 (no manifests): a NON-satisfying pin stays dropped + emits an INFO hint', () => {
    const g = parse('yarn-berry-v8', BERRY_LOCK)
    // root `^3.1.3` — neither entry satisfies, no override map → dropped
    expect(edgeFromTo(g, ROOT, 'csstype')).toBeUndefined()
    const diags = g.diagnostics()
    // the drop diagnostic is the family-level UNRESOLVED_DEP (unchanged code)
    expect(diags.some(d => d.code === 'YARN_BERRY_UNRESOLVED_DEP' && d.subject === ROOT)).toBe(true)
    // INFO hint (version-prefixed, mirroring the *_PEER_AMBIGUOUS family) points
    // at the missing manifests (the resolutions-pin signature)
    const info = diags.find(d => d.code === 'YARN_BERRY_V8_RESOLUTION_PIN_UNRESOLVED' && d.subject === ROOT)
    expect(info).toBeDefined()
    expect(info?.severity).toBe('info')
  })

  it('Rung 2 (override map, WITH manifests): a NON-satisfying pin resolves', () => {
    const g = parse('yarn-berry-v8', BERRY_LOCK, { manifests: BERRY_MANIFESTS })
    // root `^3.1.3` → override `csstype@npm:^3.1.3`:"3.0.9" → csstype@3.0.9 node
    expect(edgeFromTo(g, ROOT, 'csstype')).toBe(CSSTYPE_309)
    // …and the previously-orphaned 3.0.9 node now has an incoming edge from root
    expect(g.in(CSSTYPE_309).some(e => e.src === ROOT)).toBe(true)
    // no manifest-less INFO hint when the override resolved it
    expect(g.diagnostics().some(d => d.code === 'YARN_BERRY_V8_RESOLUTION_PIN_UNRESOLVED')).toBe(false)
  })

  it('round-trips the restored dependency line back into the emitted lock', () => {
    const g = parse('yarn-berry-v8', BERRY_LOCK, { manifests: BERRY_MANIFESTS })
    const out: string = stringify('yarn-berry-v8', g)
    // the root workspace entry re-emits its `csstype` dependency (it was dropped
    // pre-fix → the line vanished on round-trip)
    const rootBlock = out.slice(out.indexOf('"root@workspace:.":'))
    expect(rootBlock).toMatch(/dependencies:\n\s+csstype:/)
  })
})

// === yarn-classic minimal repro =============================================
//
// classic is range-keyed too: entry key `csstype@^2.5.2`, but a `resolutions`
// pin produces a `csstype@3.0.9` key. Same ladder.
const CLASSIC_LOCK = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"csstype@3.0.9":
  version "3.0.9"
  resolved "https://registry.yarnpkg.com/csstype/-/csstype-3.0.9.tgz#abc"

"csstype@^2.5.2":
  version "2.6.21"
  resolved "https://registry.yarnpkg.com/csstype/-/csstype-2.6.21.tgz#def"

"consumer-a@1.0.0":
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/consumer-a/-/consumer-a-1.0.0.tgz#aaa"
  dependencies:
    csstype "^2.6.0"

"consumer-b@1.0.0":
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/consumer-b/-/consumer-b-1.0.0.tgz#bbb"
  dependencies:
    csstype "^3.1.3"
`

const CLASSIC_MANIFESTS: Record<string, Manifest> = {
  '': {
    name: 'root',
    native: { yarnResolutions: { 'csstype@^3.1.3': '3.0.9' } },
  },
}

describe('Bug #99 — yarn-classic resolution ladder', () => {
  it('Rung 3 (semver, no manifests): a SATISFYING range resolves', () => {
    const g = parse('yarn-classic', CLASSIC_LOCK)
    expect(edgeFromTo(g, CONSUMER_A, 'csstype')).toBe(CSSTYPE_2621)
  })

  it('Rung 4 (no manifests): a NON-satisfying pin stays dropped', () => {
    const g = parse('yarn-classic', CLASSIC_LOCK)
    expect(edgeFromTo(g, CONSUMER_B, 'csstype')).toBeUndefined()
    expect(g.diagnostics().some(d => d.code === 'YARN_CLASSIC_MISSING_ENTRY' && d.subject === CONSUMER_B)).toBe(true)
    expect(g.diagnostics().some(d => d.code === 'YARN_CLASSIC_RESOLUTION_PIN_UNRESOLVED' && d.subject === CONSUMER_B)).toBe(true)
  })

  it('Rung 2 (override map, WITH manifests): a NON-satisfying pin resolves', () => {
    const g = parse('yarn-classic', CLASSIC_LOCK, { manifests: CLASSIC_MANIFESTS })
    expect(edgeFromTo(g, CONSUMER_B, 'csstype')).toBe(CSSTYPE_309)
    expect(g.in(CSSTYPE_309).some(e => e.src === CONSUMER_B)).toBe(true)
  })
})

// === Source-gating regression (#91 safety) ==================================
//
// An `npm:` range must NEVER bind a git / directory node, even when its locked
// version satisfies the range. The git fork below carries a satisfying version
// (1.5.0) but a git resolution — the registry range must skip it and DROP.
const SOURCE_GATE_LOCK = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10

"forky@https://github.com/o/forky.git#commit=0123456789abcdef0123456789abcdef01234567":
  version: 1.5.0
  resolution: "forky@https://github.com/o/forky.git#commit=0123456789abcdef0123456789abcdef01234567"
  languageName: node
  linkType: hard

"consumer-a@npm:1.0.0":
  version: 1.0.0
  resolution: "consumer-a@npm:1.0.0"
  dependencies:
    forky: "npm:^1.0.0"
  languageName: node
  linkType: hard
`

describe('Bug #99 — source-gating safety (#91)', () => {
  it('an npm: range never binds a git-source node, even on a satisfying version', () => {
    const g = parse('yarn-berry-v8', SOURCE_GATE_LOCK)
    // forky@git node exists with version 1.5.0 satisfying ^1.0.0…
    const gitNode = Array.from(g.nodes()).find(n => n.name === 'forky')
    expect(gitNode?.version).toBe('1.5.0')
    // …but the npm: descriptor must NOT resolve to it → edge dropped.
    expect(edgeFromTo(g, CONSUMER_A, 'forky')).toBeUndefined()
    expect(g.in(gitNode!.id).length).toBe(0)
  })
})

// === Single-candidate short-circuit =========================================
//
// A unique registry sibling binds via the structural short-circuit (no semver
// satisfaction needed, no ambiguity). The genuine ≥2-way max-satisfying tie that
// produces `*_AMBIGUOUS_RESOLUTION` is covered directly in the primitive unit
// suite (a public-parse tie needs peer-virt siblings, out of scope here).
const AMBIGUOUS_LOCK = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10

"dup@npm:1.0.0":
  version: 1.0.0
  resolution: "dup@npm:1.0.0"
  languageName: node
  linkType: hard

"consumer-a@npm:1.0.0":
  version: 1.0.0
  resolution: "consumer-a@npm:1.0.0"
  dependencies:
    dup: "npm:^1.0.0"
  languageName: node
  linkType: hard
`

describe('Bug #99 — single tarball candidate binds (no false ambiguity)', () => {
  it('a unique tarball candidate binds via the structural short-circuit', () => {
    const g = parse('yarn-berry-v8', AMBIGUOUS_LOCK)
    expect(edgeFromTo(g, CONSUMER_A, 'dup')).toBe('dup@1.0.0')
    expect(g.diagnostics().some(d => d.code.endsWith('_AMBIGUOUS_RESOLUTION'))).toBe(false)
  })
})
