import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse, stringify } from '../../main/ts/index.ts'

// Regression for Bug #90 — a workspace consumer references a local package via a
// `link:`/`portal:` dependency recorded BARE in its `dependencies:` block
// (`link:packages/x`), while yarn keys the RESOLVED entry with a
// `::locator=<encoded-consumer>` ownership qualifier
// (`<name>@link:packages/x::locator=…`). The qualifier disambiguates the same
// on-disk path linked from different workspaces (same family as #28/#31/#76 — it
// rides the sentinel-patch NodeId slot).
//
// On parse, `addEdgesFromBlock` re-qualifies the bare consumer edge from the
// consumer's own resolution, so the BARE range survives on the edge's
// `attrs.range`. On emit, `entryKeyOfNode` turned that bare range into a SECOND
// entry-key descriptor — appending a spurious locator-less
// `<name>@link:packages/x` to the (already-qualified) entry key. The entry-key
// descriptor token count went 2→3 — a compound shape yarn never writes (yarn's
// link/portal entry key is the single qualified spec).
//
// Expected: the emitted entry key KEEPS the single `::locator=`-qualified
// descriptor; NO bare locator-less duplicate is introduced; the bare consumer
// dep value in the `dependencies:` block is untouched (yarn records it bare).

// Count entry-key DESCRIPTOR TOKENS of the form `<name>@(link|portal):<path>`.
// Entry keys can be compound (`A, B, C`) — split on ', ' and inspect each token.
const linkTokens = (lock: string): { qualified: string[]; bare: string[] } => {
  const qualified: string[] = []
  const bare: string[] = []
  for (const rawLine of lock.split('\n')) {
    if (/^\s/.test(rawLine)) continue // entry keys live at column 0
    const line = rawLine.trimEnd()
    if (!line.endsWith(':')) continue
    const keyLine = line.slice(0, -1).trim().replace(/^"(.*)"$/, '$1')
    for (const tok of keyLine.split(', ')) {
      if (!/@(?:link|portal):/.test(tok)) continue
      if (/::locator=/.test(tok)) qualified.push(tok)
      else bare.push(tok)
    }
  }
  return { qualified, bare }
}

const ROOT_LOC = encodeURIComponent('grafana@workspace:.')
const MINIMAL = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"grafana@workspace:.":
  version: 0.0.0-use.local
  resolution: "grafana@workspace:."
  dependencies:
    "@grafana/release-cli": "link:packages/release-cli"
  languageName: unknown
  linkType: soft

"@grafana/release-cli@link:packages/release-cli::locator=${ROOT_LOC}":
  version: 0.0.0-use.local
  resolution: "@grafana/release-cli@link:packages/release-cli::locator=${ROOT_LOC}"
  languageName: node
  linkType: soft
`

const PORTAL_LOC = encodeURIComponent('root@workspace:.')
const PORTAL = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  dependencies:
    pkg: "portal:packages/pkg"
  languageName: unknown
  linkType: soft

"pkg@portal:packages/pkg::locator=${PORTAL_LOC}":
  version: 0.0.0-use.local
  resolution: "pkg@portal:packages/pkg::locator=${PORTAL_LOC}"
  languageName: node
  linkType: soft
`

// Consumer records the FULL qualified link range in its deps block. Here the
// edge's `attrs.range` already carries `::locator=`, so the secondary descriptor
// EQUALS the qualified primary and was always de-duped — the #90 guard must
// leave this path unchanged.
const QUALIFIED_DEP = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"grafana@workspace:.":
  version: 0.0.0-use.local
  resolution: "grafana@workspace:."
  dependencies:
    "@grafana/release-cli": "link:packages/release-cli::locator=${ROOT_LOC}"
  languageName: unknown
  linkType: soft

"@grafana/release-cli@link:packages/release-cli::locator=${ROOT_LOC}":
  version: 0.0.0-use.local
  resolution: "@grafana/release-cli@link:packages/release-cli::locator=${ROOT_LOC}"
  languageName: node
  linkType: soft
`

const A_LOC = encodeURIComponent('a@workspace:packages/a')
const B_LOC = encodeURIComponent('b@workspace:packages/b')
// Two workspaces link the SAME on-disk path → two DISTINCT sentinel nodes (one
// per `::locator=`). Each must round-trip its own single qualified entry key
// with no spurious bare duplicate.
const MULTI = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"a@workspace:packages/a":
  version: 0.0.0-use.local
  resolution: "a@workspace:packages/a"
  dependencies:
    shared: "link:../shared"
  languageName: unknown
  linkType: soft

"b@workspace:packages/b":
  version: 0.0.0-use.local
  resolution: "b@workspace:packages/b"
  dependencies:
    shared: "link:../shared"
  languageName: unknown
  linkType: soft

"shared@link:../shared::locator=${A_LOC}":
  version: 0.0.0-use.local
  resolution: "shared@link:../shared::locator=${A_LOC}"
  languageName: node
  linkType: soft

"shared@link:../shared::locator=${B_LOC}":
  version: 0.0.0-use.local
  resolution: "shared@link:../shared::locator=${B_LOC}"
  languageName: node
  linkType: soft
`

describe('yarn-berry link:/portal: ::locator= descriptor round-trip (Bug #90)', () => {
  it('keeps the qualified descriptor; emits NO spurious bare duplicate', () => {
    const g = parse('yarn-berry-v8', MINIMAL)
    const out = stringify('yarn-berry-v8', g, { strict: false })

    const raw = linkTokens(MINIMAL)
    const emitted = linkTokens(out)
    // Raw entry key: exactly one qualified `@link:…::locator=…`, zero bare.
    expect(raw.qualified.length).toBe(1)
    expect(raw.bare.length).toBe(0)
    // Emitted entry key: STILL one qualified, STILL zero bare (no append).
    expect(emitted.qualified.length).toBe(1)
    expect(emitted.bare.length).toBe(0)
    expect(emitted.qualified[0]).toBe(
      '@grafana/release-cli@link:packages/release-cli::locator=grafana%40workspace%3A.')

    // The consumer dep value stays bare (yarn records it bare in deps).
    expect(out).toContain('"@grafana/release-cli": "link:packages/release-cli"')
    expect(out).not.toContain('"@grafana/release-cli": "link:packages/release-cli::locator=')
  })

  it('round-trips parse→stringify→parse with a stable descriptor set', () => {
    const g1 = parse('yarn-berry-v8', MINIMAL)
    const out1 = stringify('yarn-berry-v8', g1, { strict: false })
    const g2 = parse('yarn-berry-v8', out1)
    const out2 = stringify('yarn-berry-v8', g2, { strict: false })

    // Byte-idempotent and structurally stable.
    expect(out2).toBe(out1)
    expect(Array.from(g2.nodes()).length).toBe(Array.from(g1.nodes()).length)

    // The link node keeps its sentinel patch + verbatim qualified resolution,
    // and its single consumer edge — across the full round-trip.
    const link2 = Array.from(g2.nodes()).find(n => n.name === '@grafana/release-cli')!
    expect(link2.patch?.startsWith('unresolved-')).toBe(true)
    expect(g2.tarballOf(link2.id)?.nativeResolution).toBe(
      '@grafana/release-cli@link:packages/release-cli::locator=grafana%40workspace%3A.')
    expect(g2.in(link2.id).length).toBe(1)
    expect(g2.diagnostics().filter(d => d.code === 'YARN_BERRY_UNRESOLVED_DEP').length).toBe(0)
  })

  it('portal: bare-dep emits no spurious bare descriptor', () => {
    const g = parse('yarn-berry-v8', PORTAL)
    const out = stringify('yarn-berry-v8', g)
    const emitted = linkTokens(out)
    expect(emitted.qualified.length).toBe(1)
    expect(emitted.bare.length).toBe(0)
    expect(out).toContain('pkg: "portal:packages/pkg"')
    // idempotent
    expect(stringify('yarn-berry-v8', parse('yarn-berry-v8', out))).toBe(out)
  })

  it('qualified-dep-value control: single key, unaffected by the fix', () => {
    const g = parse('yarn-berry-v8', QUALIFIED_DEP)
    const out = stringify('yarn-berry-v8', g, { strict: false })
    const emitted = linkTokens(out)
    // The secondary descriptor equals the primary → still exactly one qualified
    // token, never a bare one.
    expect(emitted.qualified.length).toBe(1)
    expect(emitted.bare.length).toBe(0)
  })

  it('multi-consumer same path: two distinct single-qualified keys, no bare', () => {
    const g = parse('yarn-berry-v8', MULTI)
    const sharedNodes = Array.from(g.nodes()).filter(n => n.name === 'shared')
    expect(sharedNodes.length).toBe(2) // one sentinel node per ::locator=
    expect(new Set(sharedNodes.map(n => n.id)).size).toBe(2)

    const out = stringify('yarn-berry-v8', g, { strict: false })
    const emitted = linkTokens(out)
    expect(emitted.qualified.length).toBe(2)
    expect(emitted.bare.length).toBe(0)

    // Each consumer dep stays bare; reparse is stable + idempotent.
    expect((out.match(/shared: "link:\.\.\/shared"/g) || []).length).toBe(2)
    const g2 = parse('yarn-berry-v8', out)
    expect(Array.from(g2.nodes()).length).toBe(Array.from(g.nodes()).length)
    expect(stringify('yarn-berry-v8', g2, { strict: false })).toBe(out)
  })
})

// Real-fixture witness — babel/babel keys 4 link entries with `::locator=` and
// references them bare from its workspaces. Before #90 the round-trip appended 2
// spurious bare `$repo-utils@link:…` descriptors (token count 4 → 6). The
// fixture is a v9 lock.
const here = dirname(fileURLToPath(import.meta.url))
const babelLock = readFileSync(
  resolve(here, '../resources/fixtures/real-world/babel-babel-main-ae57969/yarn.lock'),
  'utf8',
)

describe('yarn-berry link: ::locator= descriptor round-trip — real fixture (babel)', () => {
  it('preserves entry-key link descriptor token counts (no spurious bare)', () => {
    const raw = linkTokens(babelLock)
    expect(raw.qualified.length).toBe(4)
    expect(raw.bare.length).toBe(0)

    const g = parse('yarn-berry-v9', babelLock)
    const out = stringify('yarn-berry-v9', g, { strict: false })
    const emitted = linkTokens(out)
    // Same 4 qualified link descriptors survive; zero bare ones are introduced.
    expect(emitted.qualified.length).toBe(4)
    expect(emitted.bare.length).toBe(0)
  })
})
