import { describe, expect, it } from 'vitest'
import { parse, stringify } from '../../main/ts/index.ts'

// #107 — a dist-tag dependency descriptor (`latest`/`next`) binds its
// version-keyed entry AND emits the value BARE, matching yarn's `maybeWrap`
// (yarn-1 cli.js `_stringify` writes a leaf string value via the SAME
// shouldWrapKey rule as keys: a letter-start value with no special char is
// unquoted). The classic dep-value emit previously ALWAYS quoted, over-quoting
// `latest` → `"latest"` (NOT data loss — the edge binds and the line survives,
// but the byte diverged from real yarn, e.g. gatsby@2020-06 `is-empty latest`).

const LOCK =
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n' +
  'is-empty@0.0.1:\n' +
  '  version "0.0.1"\n' +
  '  resolved "https://registry.yarnpkg.com/is-empty/-/is-empty-0.0.1.tgz#09fdc3d649dda5969156c0853a9b76bd781c5a33"\n' +
  'some-consumer@^1.0.0:\n' +
  '  version "1.0.0"\n' +
  '  resolved "https://registry.yarnpkg.com/some-consumer/-/some-consumer-1.0.0.tgz#1111111111111111111111111111111111111111"\n' +
  '  dependencies:\n' +
  '    is-empty latest\n'

describe('yarn-classic dist-tag dep value (#107)', () => {
  it('binds the dist-tag to its version-keyed entry and emits the value BARE (yarn maybeWrap), not over-quoted', () => {
    const out = stringify('yarn-classic', parse('yarn-classic', LOCK))
    expect(out).toContain('    is-empty latest')      // bare, exactly as real yarn writes it
    expect(out).not.toContain('is-empty "latest"')    // not over-quoted (the prior bug)
    // entry survives; the consumer's `is-empty@latest` descriptor merges into the
    // key (C-KEYDROP union), giving `is-empty@0.0.1, is-empty@latest:` — both bound.
    expect(out).toContain('is-empty@0.0.1')
    expect(out).toContain('is-empty@latest:')
    expect(stringify('yarn-classic', parse('yarn-classic', out))).toBe(out) // idempotent
  })

  it('still quotes a range dep value (caret / digit / protocol must stay wrapped)', () => {
    const ranged = LOCK.replace('    is-empty latest\n', '    is-empty "^0.0.1"\n')
    const out = stringify('yarn-classic', parse('yarn-classic', ranged))
    expect(out).toContain('is-empty "^0.0.1"')        // range stays quoted (maybeWrap)
  })
})
