// yaf lockgraph-message (2026-06-20): a dep edge ADDED after parse (by
// completion / replaceVersion-refresh) carries the packument's BARE range
// (`^2.1.3`). Emitted bare, yarn reads it as the `semver:` protocol and aborts
// ("isn't supported by any available resolver"). The berry emitter must
// synthesise the default `npm:` for a prefix-less semver range — while parsed
// edges (already `npm:`) and explicit protocols stay verbatim.

import { describe, expect, it } from 'vitest'
import { parse, stringify } from '../../main/ts/index.ts'

const LOCK = `# This file is generated by running "yarn install" inside your project.
# Manually changing this file will cause non-deterministic behavior.

__metadata:
  version: 8
  cacheKey: 10c0

"app@workspace:.":
  version: 0.0.0-use.local
  resolution: "app@workspace:."
  dependencies:
    tslib: "npm:^2.0.0"
  languageName: unknown
  linkType: soft

"tslib@npm:2.0.0":
  version: 2.0.0
  resolution: "tslib@npm:2.0.0"
  checksum: 10c0/d924b57e7312b3b63ad21fc5b3dc0af5e78d61a1fc7cfb5457edaf26326bf62be5307cc87ffb6862ef1c2b33b0233cdb5d4f01c4c958cc0d660948b65a287a48
  languageName: node
  linkType: hard

"ms@npm:2.1.3":
  version: 2.1.3
  resolution: "ms@npm:2.1.3"
  checksum: 10c0/d924b57e7312b3b63ad21fc5b3dc0af5e78d61a1fc7cfb5457edaf26326bf62be5307cc87ffb6862ef1c2b33b0233cdb5d4f01c4c958cc0d660948b65a287a48
  languageName: node
  linkType: hard
`

describe('yarn-berry: added edges get the npm: protocol on emit', () => {
  it('a bare-range dep edge added post-parse emits as npm:<range>', () => {
    const g0 = parse('yarn-berry-v8', LOCK)
    // a parsed edge already round-trips as `npm:` — establish the baseline.
    expect(stringify('yarn-berry-v8', g0)).toContain('tslib: "npm:^2.0.0"')

    // simulate completion adding a dep edge with the packument's BARE range.
    const g1 = g0.mutate(m => {
      m.addEdge('tslib@2.0.0', 'ms@2.1.3', 'dep', { range: '^2.1.3' })
    }).graph

    const out = stringify('yarn-berry-v8', g1)
    expect(out).toContain('ms: "npm:^2.1.3"')   // synthesised, not bare
    expect(out).not.toContain('ms: ^2.1.3')      // never the bare semver: form
  })
})
