import { describe, expect, it } from 'vitest'
import { parse, stringify } from '../../main/ts/index.ts'

// F11 — yarn-classic entry ORDER. yarn sorts entries by the FIRST descriptor's
// CONTENT (ASCII/code-point), stripping the wrapping `"`. The emitter previously
// sorted by the literal serialized key line: because `"` is ASCII 34 (< `@`=64 <
// letters=97), every QUOTED key (multi-descriptor / special-char) was clustered
// AHEAD of the bare ones instead of interleaving by descriptor content (67/84
// real classic locks differed only by this ordering — no data loss).

const LOCK =
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n' +
  'aaa@^1.0.0:\n' +
  '  version "1.0.0"\n' +
  '  resolved "https://registry.yarnpkg.com/aaa/-/aaa-1.0.0.tgz#1111111111111111111111111111111111111111"\n\n' +
  '"graphql@^14.0.0 || ^15.0.0":\n' +
  '  version "15.0.0"\n' +
  '  resolved "https://registry.yarnpkg.com/graphql/-/graphql-15.0.0.tgz#2222222222222222222222222222222222222222"\n\n' +
  'zzz@^1.0.0:\n' +
  '  version "1.0.0"\n' +
  '  resolved "https://registry.yarnpkg.com/zzz/-/zzz-1.0.0.tgz#3333333333333333333333333333333333333333"\n'

describe('yarn-classic entry order (#11/F11)', () => {
  it('interleaves a quoted key by its descriptor content (g), not clustered ahead by the leading quote', () => {
    const out = stringify('yarn-classic', parse('yarn-classic', LOCK))
    const ia = out.indexOf('aaa@^1.0.0:')
    const ig = out.indexOf('"graphql@^14.0.0 || ^15.0.0":')
    const iz = out.indexOf('zzz@^1.0.0:')
    expect(ia).toBeGreaterThan(-1)
    expect(ig).toBeGreaterThan(-1)
    expect(iz).toBeGreaterThan(-1)
    expect(ia).toBeLessThan(ig) // aaa (content 'a') before graphql (content 'g') — was clustered after the quote
    expect(ig).toBeLessThan(iz) // graphql (content 'g') before zzz (content 'z')
    // Order is deterministic + stable across a re-emit.
    expect(stringify('yarn-classic', parse('yarn-classic', out))).toBe(out)
  })
})
