import { describe, expect, it } from 'vitest'
import { parseFormat, stringifyFormat } from '../_runtime.ts'

describe('interop adversarial §8.4 — multi-spec key preservation', () => {
  it('classic -> berry-v9 currently canonicalises a multi-spec key to the resolved npm locator', () => {
    const sourceLockfile =
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n' +
      '# yarn lockfile v1\n\n\n' +
      '"foo@^1.0.0, foo@^2.0.0":\n' +
      '  version "2.1.0"\n' +
      '  resolved "https://registry.yarnpkg.com/foo/-/foo-2.1.0.tgz#0000000000000000000000000000000000000000"\n' +
      '  integrity sha512-foo\n'
    const sourceGraph = parseFormat('yarn-classic', sourceLockfile)
    const emitted = stringifyFormat('yarn-berry-v9', sourceGraph)

    expect(emitted.lockfile).toContain('"foo@npm:2.1.0":')
  })

  it.todo(
    'classic -> berry-v9 should emit INTEROP_CLASSIC_TO_BERRY_V9_MULTI_SPEC_COLLAPSED once multi-spec canonicalisation is surfaced through the matrix',
  )
})
