import { createHash } from 'node:crypto'
import path from 'node:path'
import semver from 'semver'
import {
  newBuilder,
  GraphError,
  type Graph,
  type Mutator,
  type MutateResult,
  type Node,
  type EdgeAttrs,
  type EdgeKind,
  nameOf,
  serializeNodeId,
  type TarballPayload,
  toTarballKey,
  type TarballKeyInputs,
  type Diagnostic,
} from '../graph.ts'
import { LockfileError } from '../errors.ts'
import { readWorkspaceFileBytes } from './_path.ts'
import {
  parse as parseSyml,
  stringify as stringifySyml,
  type SymlMap,
  type SymlValue,
} from './_yarn-syml.ts'
import {
  parseBerryChecksum,
  emitBerryChecksum,
  isEmptyIntegrity,
} from '../recipe/integrity.ts'
import {
  parse as parseResolutionRecipe,
  stringifyForYarnBerry,
  type ResolutionCanonical,
} from '../recipe/resolution.ts'
import {
  hashAndNormaliseBytes as patchHashAndNormaliseBytes,
  sentinelHashOfLocator,
} from '../recipe/patch.ts'
import { emitDropped, emitIntegrityIncomplete, patchNormalisedDiagnostic, unknownResolutionDiagnostic } from '../recipe/diagnostics.ts'

// Yarn-berry entry-spec grammar requires `<scheme>:` on every spec
// (`parseSpec` throws PARSE_FAILED otherwise). Cross-family inputs
// (pnpm-v9 bare semver ranges) lack the scheme — synthesise `npm:` so
// reparse stays well-formed. Per ADR-0016 §B `npm:` is the default
// protocol for registry packages.
const PROTOCOL_RE = /^[A-Za-z][A-Za-z0-9+\-.]*:/
function entryKeyRangeOf(range: string): string {
  return PROTOCOL_RE.test(range) ? range : `npm:${range}`
}

function looksLikePatchLocator(raw: string | undefined): boolean {
  return raw !== undefined && raw.includes('@patch:')
}

// Yarn-berry workspace `link:` and `portal:` resolutions point to a local
// filesystem directory; the optional `::locator=<encoded-workspace-locator>`
// qualifier disambiguates which workspace consumer "owns" the reference.
// Two entries with identical name+version but different `::locator=...`
// qualifiers are legitimately distinct (same physical directory referenced
// from different consumers in any multi-workspace
// monorepo). Without disambiguation they collapse onto one NodeId and
// trip IRREDUCIBLE_LOSS. We treat the locator+qualifier as a sentinel-
// patch discriminator: the patch slot is the only NodeId-affecting carrier
// in the ADR-0006/0011 schema, and the sentinel grammar
// (`unresolved-<sha256>`) accepts arbitrary discriminators while keeping
// validatePatchToken intact. The Node.resolution carries the verbatim
// locator string for lossless round-trip.
function isLinkOrPortalResolution(resolution: string, name: string): boolean {
  return resolution.startsWith(`${name}@link:`) || resolution.startsWith(`${name}@portal:`)
}

// A `file:` resolution is ALWAYS a local artefact (local-tarball alias or a
// directory link) — never a registry package (those use `npm:`). When yarn
// records a `locator=<encoded-consumer-locator>` qualifier in its `::`-param
// block, that qualifier names which workspace consumer owns the reference,
// exactly as for `link:`/`portal:`. Such an entry can collide on NodeId with a
// sibling registry entry at the SAME name@version yet be a genuinely different
// artefact (Bug #76: resolution
// `@k8ts/sample-interfaces@file:.lib/….tgz#….tgz::hash=17d4d9&locator=…`
// — canonical `tarball`, its own checksum + dep ranges — vs the sibling
// `@k8ts/sample-interfaces@npm:0.6.3` — registry). They must stay DISTINCT
// nodes, so the `file:` alias takes the same sentinel-patch disambiguator.
// Gate on the `locator=` qualifier (NB: in the *resolution* it rides the `::`
// param block as `::hash=…&locator=…`, whereas the *entry key* writes a bare
// `::locator=…`) so a plain `file:../dir` directory link with no consumer
// qualifier — already a unique node — is left unpatched; only the consumer-
// owned alias that can actually collide is discriminated.
function isFileLocatorResolution(resolution: string, name: string): boolean {
  if (!resolution.startsWith(`${name}@file:`)) return false
  const paramsIdx = resolution.indexOf('::')
  return paramsIdx >= 0 && /(^|&)locator=/.test(resolution.slice(paramsIdx + 2))
}

// Local-artefact locators whose `::locator=` (or link/portal protocol) carries
// a consumer-ownership discriminator that the NodeId must preserve. Drives both
// the parse-side sentinel-patch assignment and the emit-side verbatim
// round-trip so the two stay in lockstep.
function isLocalLocatorDisambiguatedResolution(resolution: string, name: string): boolean {
  return isLinkOrPortalResolution(resolution, name) || isFileLocatorResolution(resolution, name)
}

const PREAMBLE =
  '# This file is generated by running "yarn install" inside your project.\n' +
  '# Manual changes might be lost - proceed with caution!'
const cmpStr = (a: string, b: string): number => a < b ? -1 : a > b ? 1 : 0
const EMPTY_SIDECAR: YarnBerryFamilySidecar = {}

export interface YarnBerryFamilyParseOptions {
  workspaceRoot?: string
}

export interface YarnBerryFamilyStringifyOptions {
  lineEnding?: 'lf' | 'crlf'
  cacheKey?: string
  onDiagnostic?: (diagnostic: Diagnostic) => void
}

export interface YarnBerryFamilyEnrichOptions {}
export interface YarnBerryFamilyOptimizeOptions {}

export interface YarnBerryFamilyConfig {
  lockfileVersion: number
  codePrefix: string
  rangeEmit: 'bare' | 'quoted-protocol'
  checksumPrefix: boolean
  conditionsAllowed: boolean
}

export interface YarnBerryFamilySidecar {
  peerDependencies?: Map<string, Record<string, string>>
  conditions?: Map<string, SymlMap>
  metadata?: SymlMap
}

interface SpecPart {
  name: string
  protocol: string
  spec: string
}

interface DerivedPeer {
  name: string
  range: string
  dstOldId: string
}

interface PendingDiagnostic extends Omit<Diagnostic, 'subject'> {
  subject: string
  candidateIds?: string[]
  peerName?: string
}

const sidecarByGraph = new WeakMap<Graph, YarnBerryFamilySidecar>()

export function checkFamily(input: string, config: YarnBerryFamilyConfig): boolean {
  const head = input.slice(0, 4096)
  return new RegExp(
    `^__metadata:\\s*[\\r\\n]+(?:[ \\t]+[^\\n]*[\\r\\n]+)*?[ \\t]+version:\\s*${config.lockfileVersion}\\s*(?:[\\r\\n]|$)`,
    'm',
  ).test(head)
}

export function parseFamily(
  input: string,
  options: YarnBerryFamilyParseOptions,
  config: YarnBerryFamilyConfig,
): { graph: Graph; sidecar: YarnBerryFamilySidecar } {
  const ast = parseSyml(input)
  const metadata = validateMetadata(ast, config)

  const builder = newBuilder()
  const diagnostics: Diagnostic[] = []
  const rawPeerDependencies = new Map<string, Record<string, string>>()
  const rawConditions = new Map<string, SymlMap>()

  const entries: Array<{ key: string; value: SymlMap; specs: SpecPart[] }> = []
  for (const [key, value] of Object.entries(ast)) {
    if (key === '__metadata') continue
    const valueMap = asMap(value)
    if (!valueMap) {
      diagnostics.push({
        code: 'YARN_BERRY_BAD_ENTRY',
        severity: 'warning',
        message: `entry ${JSON.stringify(key)} is not a block; skipping`,
      })
      continue
    }
    const specs = parseEntryKey(key)
    entries.push({ key, value: valueMap, specs })
  }

  const specIndex = new Map<string, string>()
  const seenIds = new Set<string>()
  const entryIds = new Map<string, string>()

  for (const { key, value, specs } of entries) {
    const first = specs[0]
    if (!first) {
      throw new LockfileError({
        code: 'PARSE_FAILED',
        message: `entry ${JSON.stringify(key)} has empty spec`,
      })
    }
    const version = asString(value['version'])
    if (version === undefined) {
      throw new LockfileError({
        code: 'PARSE_FAILED',
        message: `entry ${JSON.stringify(key)} missing 'version'`,
      })
    }
    const resolution = asString(value['resolution'])
    // Authoritative name comes from the `resolution:` locator when present
    // (ADR-0014 §4.F3 — single canonical identity). Compound entry-keys can
    // sort an npm-alias spec ahead of the canonical spec lexically (e.g.
    // `@scope/pkg--variant@npm:@scope/pkg@…,
    //  @scope/pkg@npm:…`); keying off `first.name` mistakes the alias
    // for the real package name. Falling back to `first.name` keeps legacy
    // single-spec / sentinel-version entries intact.
    const authoritativeName = resolution !== undefined
      ? nameFromResolutionLocator(resolution) ?? first.name
      : first.name
    const baseId = serializeNodeId(authoritativeName, version, [])
    const rawPatchResult = resolution !== undefined
      ? extractPatchFingerprint(baseId, resolution, options.workspaceRoot)
      : undefined
    // Local-artefact locator-disambiguator (per ADR-0011 sentinel-as-
    // discriminator pattern): `link:` / `portal:` directory references and a
    // `::locator=`-qualified `file:` local-tarball alias. Only kicks in when no
    // `@patch:` fingerprint already populates the slot — `@patch:` wins because
    // it carries actual byte-identity semantics; these locators carry only a
    // consumer-ownership discriminator. Keyed off authoritativeName (the
    // resolution-derived canonical name) so it stays correct under the
    // compound-entry-key alias-ordering case Bug #3 fixes.
    const linkLocatorPatch = rawPatchResult === undefined && resolution !== undefined
      && isLocalLocatorDisambiguatedResolution(resolution, authoritativeName)
      ? sentinelHashOfLocator(resolution)
      : undefined
    const effectivePatch = rawPatchResult?.patch ?? linkLocatorPatch
    const id = serializeNodeId(authoritativeName, version, [], effectivePatch)
    const patchResult = rawPatchResult?.diagnostic !== undefined
      ? {
          ...rawPatchResult,
          diagnostic: {
            ...rawPatchResult.diagnostic,
            subject: id,
          },
        }
      : rawPatchResult

    if (seenIds.has(id)) {
      throw new LockfileError({
        code: 'IRREDUCIBLE_LOSS',
        message: irreducibleCollisionMessage(id, key, entries),
      })
    }
    seenIds.add(id)
    entryIds.set(key, id)

    const node: Node = {
      id,
      name: authoritativeName,
      version,
      peerContext: [],
    }
    if (resolution !== undefined) node.resolution = resolution
    if (effectivePatch !== undefined) node.patch = effectivePatch
    // Workspace identification keys off `resolution` (the canonical, single
    // identity per ADR-0014 §4.F3), not `specs[0].protocol`. A compound entry
    // may list `<n>@npm:<ver>, <n>@workspace:<path>` in any order — the npm
    // alias claims spec[0] when it sorts first lexically, yet the entry is
    // still the local workspace (resolution is authoritative). Falling back
    // to `first.spec` only when resolution is absent preserves the legacy
    // single-spec workspace shape (`<n>@workspace:<path>`).
    const workspaceSpec = workspaceSpecOfEntry(resolution, specs, first)
    if (workspaceSpec !== undefined) {
      node.workspacePath = workspacePathOf(workspaceSpec)
    }
    builder.addNode(node)
    if (patchResult?.diagnostic) diagnostics.push(patchResult.diagnostic)

    // ADR-0014 §4.F3 — canonical resolution into TarballPayload. Workspace
    // identity is NOT part of F3 canonical (it lives on Node.workspacePath);
    // skip the primitive entirely for workspace-protocol locators (driven by
    // the resolution, not by spec[0] — see workspaceSpec derivation above).
    const canonicalResolution = resolution !== undefined && workspaceSpec === undefined
      ? parseResolutionRecipe(resolution, { sourceKind: 'yarn-berry-locator', name: authoritativeName })
      : undefined
    if (canonicalResolution !== undefined && canonicalResolution.type === 'unknown' && !looksLikePatchLocator(resolution)) {
      diagnostics.push(unknownResolutionDiagnostic(id, resolution!))
    }

    const peerDependencies = stringRecordOfBlock(asMap(value['peerDependencies']))
    if (peerDependencies !== undefined) {
      rawPeerDependencies.set(id, peerDependencies)
    }

    const conditions = coerceSymlMap(value['conditions'])
    if (conditions !== undefined) {
      rawConditions.set(id, conditions)
    }

    const payload: TarballPayload = {}
    const checksum = asString(value['checksum'])
    if (checksum !== undefined) {
      // Berry `checksum` is a digest of yarn's zip-cache — NOT the tarball:
      // bare sha512 hex (pre-v8) or `<cacheKey>/<sha512-hex>` (v8/v9). It is
      // parsed as a `berry-zip`-origin sha512 so it is never re-encoded into a
      // tarball SRI on emit. sha1/sha256/malformed bodies yield no hash and are
      // rejected with a diagnostic, leaving the integrity slot undefined.
      const { integrity, cacheKey: checksumCacheKey } = parseBerryChecksum(checksum)
      if (isEmptyIntegrity(integrity)) {
        diagnostics.push({
          code:     `${config.codePrefix}_INVALID_INTEGRITY`,
          severity: 'warning',
          subject:  id,
          message:  `checksum ${JSON.stringify(checksum)} is not a sha512 berry checksum; dropping integrity`,
        })
      } else {
        payload.integrity = integrity
        // Round-trip the `<cacheKey>/` prefix verbatim (ADR-0031): preserve it
        // IFF the source carried one, for EVERY berry generation (yarn-2.0 `2/`
        // through v8/v9 `10c0/`). A bare source leaves this undefined → bare
        // emit, so the bare-v4/v7 shape stays bare.
        if (checksumCacheKey !== undefined) payload.berryChecksumCacheKey = checksumCacheKey
      }
    }
    const binMap = asMap(value['bin'])
    if (binMap) {
      const bin: Record<string, string> = {}
      for (const [name, target] of Object.entries(binMap)) {
        if (typeof target === 'string') bin[name] = target
      }
      if (Object.keys(bin).length > 0) payload.bin = bin
    }
    // ADR-0014 §4.F3 — workspace canonical lives on Node.workspacePath
    // (per-format), not on TarballPayload (which is for cross-format
    // artefact metadata). Workspace inputs already bypass the primitive
    // above, so `canonicalResolution` is guaranteed non-workspace here.
    if (canonicalResolution !== undefined) {
      payload.resolution = canonicalResolution
    }
    if (Object.keys(payload).length > 0) {
      // Key MUST match the NodeId built above: authoritativeName (Bug #3
      // canonical-name) + effectivePatch (Bug #2 link/portal locator slot).
      builder.setTarball({ name: authoritativeName, version, patch: effectivePatch }, payload)
    }

    for (const spec of specs) {
      const lookup = `${spec.name}@${spec.protocol}:${spec.spec}`
      // Cross-family emit can intentionally advertise the same spec from
      // multiple sibling entries to preserve source-graph edge targets when
      // the input lacks yarn-native resolution sidecars. Keep the first
      // claimant (entries are already in deterministic source order) so
      // parse-side resolution stays stable instead of drifting on overwrite.
      if (!specIndex.has(lookup)) {
        specIndex.set(lookup, id)
      }
    }
  }

  for (const { key, value, specs } of entries) {
    const first = specs[0]
    if (!first) continue
    const srcId = entryIds.get(key)
    if (srcId === undefined) continue

    // The source entry's own resolution doubles as its locator for resolving
    // any `link:` / `portal:` deps it declares (see addEdgesFromBlock).
    const srcResolution = asString(value['resolution'])
    addEdgesFromBlock(builder, srcId, asMap(value['dependencies']), 'dep', specIndex, diagnostics, srcResolution)
    addEdgesFromBlock(builder, srcId, asMap(value['optionalDependencies']), 'optional', specIndex, diagnostics, srcResolution)
  }

  // Sort diagnostics by subject + code to keep graph.diagnostics() order
  // independent of source-file entry order (recipe-layer diagnostics fire
  // per-entry on parse; round-trips that re-sort entries on emit would
  // otherwise produce a re-ordered diagnostic list).
  diagnostics.sort((a, b) => {
    const sa = typeof a.subject === 'string' ? a.subject : ''
    const sb = typeof b.subject === 'string' ? b.subject : ''
    return cmpStr(sa, sb) || cmpStr(a.code, b.code)
  })
  for (const diagnostic of diagnostics) builder.diagnostic(diagnostic)

  try {
    const sealed = builder.seal()
    // ADR-0014 §4.F4 — parse-side workspace marking. Edges whose source
    // range carries the `workspace:` protocol AND whose target is a
    // workspace member node get `attrs.workspace = true` plus the
    // canonical workspaceRange sidecar. The same logic also runs in
    // enrichFamily для downstream rebuilds; doing it here ensures the
    // public `parse()` surface (and convert without explicit enrich)
    // delivers F4-ready edges.
    const graph = markWorkspaceEdgesAtParse(sealed)
    const sidecar: YarnBerryFamilySidecar = {}
    if (rawPeerDependencies.size > 0) sidecar.peerDependencies = rawPeerDependencies
    if (rawConditions.size > 0) sidecar.conditions = rawConditions
    if (metadata !== undefined) sidecar.metadata = metadata
    rememberSidecar(graph, sidecar)
    // Wrap so that any subsequent graph.mutate() call propagates the sidecar
    // (including __metadata.cacheKey) to the returned graph instance.
    const wrappedGraph = withSidecarPropagation(graph, sidecar)
    return { graph: wrappedGraph, sidecar }
  } catch (error) {
    if (error instanceof GraphError) {
      throw new LockfileError({
        code: 'PARSE_FAILED',
        message: `seal failed: ${error.message}`,
      })
    }
    throw error
  }
}

export function stringifyFamily(
  graph: Graph,
  config: YarnBerryFamilyConfig,
  options: YarnBerryFamilyStringifyOptions = {},
): { lockfile: string; diagnostics: Diagnostic[] } {
  const sidecar = sidecarByGraph.get(graph) ?? EMPTY_SIDECAR
  const diagnostics: Diagnostic[] = []
  const emitDiagnostic = (diagnostic: Diagnostic): void => {
    diagnostics.push(diagnostic)
    options.onDiagnostic?.(diagnostic)
  }

  const metadata: SymlMap = { version: String(config.lockfileVersion) }
  const cacheKey = options.cacheKey ?? asString(sidecar.metadata?.cacheKey)
  if (cacheKey !== undefined) {
    metadata['cacheKey'] = cacheKey
  }
  if (sidecar.metadata !== undefined) {
    for (const key of Object.keys(sidecar.metadata).sort(cmpStr)) {
      if (key === 'version' || key === 'cacheKey') continue
      const value = cloneSymlValue(sidecar.metadata[key])
      if (value !== undefined) {
        metadata[key] = value
      }
    }
  }

  const root: SymlMap = { __metadata: metadata }
  const entries = Array.from(graph.nodes(), node => ({
    nodeId: node.id,
    key: entryKeyOfNode(graph, node),
    value: entryOfNode(graph, node, config, emitDiagnostic, cacheKey),
  })).sort((a, b) => cmpStr(a.key, b.key))

  const seenIds = new Map<string, string>()
  for (const entry of entries) {
    const node = graph.getNode(entry.nodeId)
    const emitId = node === undefined
      ? entry.nodeId
      : toTarballKey({ name: node.name, version: node.version, patch: node.patch })
    const prevNodeId = seenIds.get(emitId)
    if (prevNodeId !== undefined) {
      throw new LockfileError({
        code: 'IRREDUCIBLE_LOSS',
        message: `duplicate node id collides on emit: ${emitId} from ${prevNodeId}, ${entry.nodeId}`,
      })
    }
    seenIds.set(emitId, entry.nodeId)
    root[entry.key] = entry.value
  }

  let output = `${PREAMBLE}\n\n${stringifySyml(root)}`
  output = unquoteMetadataScalar(output, 'version', String(config.lockfileVersion))
  if (cacheKey !== undefined && /^-?(0|[1-9][0-9]*)$/.test(cacheKey)) {
    output = unquoteMetadataScalar(output, 'cacheKey', cacheKey)
  }
  const compressionLevel = sidecar.metadata?.compressionLevel
  if (typeof compressionLevel === 'string' && /^-?(0|[1-9][0-9]*)$/.test(compressionLevel)) {
    output = unquoteMetadataScalar(output, 'compressionLevel', compressionLevel)
  }
  if (options.lineEnding === 'crlf') {
    output = output.replace(/\n/g, '\r\n')
  }

  return { lockfile: output, diagnostics }
}

export function enrichFamily(
  graph: Graph,
  config: YarnBerryFamilyConfig,
  _options: YarnBerryFamilyEnrichOptions = {},
): { graph: Graph; diagnostics: Diagnostic[] } {
  const sidecar = sidecarByGraph.get(graph) ?? EMPTY_SIDECAR
  const rawPeerDependencies = sidecar.peerDependencies ?? new Map<string, Record<string, string>>()
  const derivedPeersByNodeId = new Map<string, DerivedPeer[]>()
  const pendingDiagnostics: PendingDiagnostic[] = []
  let peerChanged = false

  for (const node of graph.nodes()) {
    const rawPeers = rawPeerDependencies.get(node.id)
    if (rawPeers === undefined || node.peerContext.length > 0 || graph.out(node.id, 'peer').length > 0) {
      continue
    }

    const derivedPeers: DerivedPeer[] = []
    for (const [peerName, range] of Object.entries(rawPeers).sort((a, b) => cmpStr(a[0], b[0]))) {
      const normalizedRange = semver.validRange(range)
      if (normalizedRange === null) {
        throw new LockfileError({
          code: 'INVALID_INPUT',
          message: `invalid peer range for ${node.id}: ${peerName}@${range}`,
        })
      }

      const candidates = graph.byName(peerName)
        .filter(candidateId => {
          const candidate = graph.getNode(candidateId)
          return candidate !== undefined
            && semver.valid(candidate.version) !== null
            && semver.satisfies(candidate.version, normalizedRange)
        })
        .slice()
        .sort(cmpStr)

      if (candidates.length === 1) {
        derivedPeers.push({ name: peerName, range, dstOldId: candidates[0]! })
        peerChanged = true
        continue
      }

      if (candidates.length === 0) {
        pendingDiagnostics.push({
          code: `${config.codePrefix}_PEER_UNSATISFIED`,
          severity: 'warning',
          subject: node.id,
          message: `peer "${peerName}" range "${range}" matches no installed version`,
        })
        continue
      }

      pendingDiagnostics.push({
        code: `${config.codePrefix}_PEER_AMBIGUOUS`,
        severity: 'warning',
        subject: node.id,
        peerName,
        candidateIds: candidates,
        message: ambiguousPeerMessage(peerName, candidates),
      })
    }

    if (derivedPeers.length > 0) {
      derivedPeersByNodeId.set(node.id, derivedPeers)
    }
  }

  const workspaceChanged = graphNeedsWorkspaceAttribution(graph)
  if (!peerChanged && !workspaceChanged) {
    return {
      graph,
      diagnostics: pendingDiagnostics.map(diagnostic => finalizePendingDiagnostic(diagnostic, new Map())),
    }
  }

  const finalNodeIds = deriveFinalNodeIds(graph, derivedPeersByNodeId)
  const nextNodes = new Map<string, Node>()
  for (const node of graph.nodes()) {
    const derivedPeers = derivedPeersByNodeId.get(node.id)
    if (derivedPeers === undefined) {
      nextNodes.set(node.id, node)
      continue
    }

    const peerContext = sortPeerContext(derivedPeers.map(peer => finalNodeIds.get(peer.dstOldId) ?? peer.dstOldId))
    const newId = finalNodeIds.get(node.id) ?? node.id
    nextNodes.set(node.id, {
      ...node,
      id: newId,
      peerContext,
    })
  }

  const builder = newBuilder()
  for (const node of graph.nodes()) {
    builder.addNode(nextNodes.get(node.id) ?? node)
  }

  for (const node of graph.nodes()) {
    for (const edge of graph.out(node.id)) {
      const nextSrc = nextNodes.get(edge.src)?.id ?? edge.src
      const nextDst = nextNodes.get(edge.dst)?.id ?? edge.dst
      let nextAttrs = edge.attrs

      if (edge.kind !== 'peer' && edge.attrs?.workspace !== true && isDerivedWorkspaceRange(edge.attrs?.range)) {
        const dstNode = graph.getNode(edge.dst)
        if (dstNode?.workspacePath !== undefined) {
          // ADR-0014 §4.F4 — populate canonical workspaceRange sidecar
          // via shared `deriveMarkedWorkspaceAttrs` (also driven by the
          // parse-time `markWorkspaceEdgesAtParse` pass).
          nextAttrs = deriveMarkedWorkspaceAttrs(edge.attrs, dstNode)
        }
      }

      builder.addEdge(nextSrc, nextDst, edge.kind, nextAttrs)
    }
  }

  for (const [srcOldId, derivedPeers] of derivedPeersByNodeId) {
    const srcNewId = nextNodes.get(srcOldId)?.id ?? srcOldId
    for (const peer of derivedPeers) {
      const dstNewId = nextNodes.get(peer.dstOldId)?.id ?? peer.dstOldId
      builder.addEdge(srcNewId, dstNewId, 'peer', { range: peer.range })
    }
  }

  for (const node of graph.nodes()) {
    const payload = graph.tarballOf(node.id)
    if (payload === undefined) continue
    builder.setTarball({ name: node.name, version: node.version, patch: node.patch }, payload)
  }
  for (const diagnostic of graph.diagnostics()) {
    builder.diagnostic(diagnostic)
  }
  const layoutHints = graph.layoutHints()
  if (layoutHints !== undefined) {
    builder.layoutHints(layoutHints)
  }

  const nextGraph = builder.seal()
  rememberSidecar(nextGraph, remapSidecar(sidecar, nextNodes, nextGraph))

  return {
    graph: nextGraph,
    diagnostics: pendingDiagnostics.map(diagnostic => finalizePendingDiagnostic(diagnostic, nextNodes)),
  }
}

export function optimizeFamily(
  graph: Graph,
  _options: YarnBerryFamilyOptimizeOptions = {},
): { graph: Graph; diagnostics: Diagnostic[] } {
  const sidecar = sidecarByGraph.get(graph) ?? EMPTY_SIDECAR
  const reachable = new Set(graph.walk(Array.from(graph.roots())))
  const unreachableNodes = Array.from(graph.nodes(), node => node.id)
    .filter(nodeId => !reachable.has(nodeId))
    .sort(cmpStr)

  if (unreachableNodes.length === 0) {
    return {
      graph,
      diagnostics: graph.diagnostics().filter(diagnostic => diagnostic.severity === 'warning'),
    }
  }

  const unreachable = new Set(unreachableNodes)
  const referencedTarballs = new Set<string>()
  const tarballsToRemove = new Map<string, TarballKeyInputs>()
  const internalEdges = unreachableNodes
    .flatMap(src =>
      graph.out(src)
        .filter(edge => unreachable.has(edge.dst))
        .map(edge => ({ src: edge.src, dst: edge.dst, kind: edge.kind })),
    )
    .sort((a, b) =>
      cmpStr(`${a.src}\u0000${a.kind}\u0000${a.dst}`, `${b.src}\u0000${b.kind}\u0000${b.dst}`),
    )

  for (const node of graph.nodes()) {
    const inputs = { name: node.name, version: node.version, patch: node.patch }
    const key = toTarballKey(inputs)
    if (unreachable.has(node.id)) {
      tarballsToRemove.set(key, inputs)
      continue
    }
    referencedTarballs.add(key)
  }

  const result = graph.mutate(m => {
    for (const edge of internalEdges) {
      m.removeEdge(edge.src, edge.dst, edge.kind)
    }
    for (const nodeId of unreachableNodes) {
      m.removeNode(nodeId)
    }
    for (const [key, inputs] of Array.from(tarballsToRemove.entries()).sort((a, b) => cmpStr(a[0], b[0]))) {
      if (!referencedTarballs.has(key)) {
        m.removeTarball(inputs)
      }
    }
  })

  rememberSidecar(result.graph, pruneSidecar(sidecar, result.graph))
  return { graph: result.graph, diagnostics: result.unresolved ?? [] }
}

export function rememberSidecar(graph: Graph, sidecar: YarnBerryFamilySidecar): void {
  if (isEmptySidecar(sidecar)) return
  sidecarByGraph.set(graph, sidecar)
}

/**
 * Wraps a Graph so that every `.mutate()` call propagates the sidecar
 * (metadata, peerDependencies, conditions) to the resulting graph.
 *
 * Without this wrapper, `mutate()` returns a brand-new `Graph` instance
 * that has no entry in `sidecarByGraph`, causing `stringifyFamily` to fall
 * back to `EMPTY_SIDECAR` and drop `__metadata.cacheKey` (and any other
 * sidecar data) from the emitted lockfile.
 *
 * nodeId remapping: when a `replaceNode` or `replacePeerContext` change is
 * recorded, the old nodeId is no longer in the graph; the sidecar's
 * peerDependencies / conditions maps are keyed by nodeId, so we remap them
 * through the applied ChangeRecord list exactly as `remapSidecar` does for
 * `enrichFamily`.
 */
function withSidecarPropagation(graph: Graph, sidecar: YarnBerryFamilySidecar): Graph {
  // Thin delegation proxy — only `mutate` is overridden; everything else
  // forwards to the underlying graph so the object is still a true Graph.
  const proxy: Graph = {
    getNode:      (...args) => graph.getNode(...args),
    nodes:        ()        => graph.nodes(),
    byName:       (...args) => graph.byName(...args),
    roots:        ()        => graph.roots(),
    out:          (...args) => graph.out(...args),
    in:           (...args) => graph.in(...args),
    walk:         (...args) => graph.walk(...args),
    topoSort:     ()        => graph.topoSort(),
    subgraph:     (...args) => graph.subgraph(...args),
    diff:         (...args) => graph.diff(...args),
    tarball:      (...args) => graph.tarball(...args),
    tarballOf:    (...args) => graph.tarballOf(...args),
    tarballs:     ()        => graph.tarballs(),
    diagnostics:  ()        => graph.diagnostics(),
    layoutHints:  ()        => graph.layoutHints(),
    mutate(transaction: (m: Mutator) => void): MutateResult {
      const result = graph.mutate(transaction)
      if (!isEmptySidecar(sidecar)) {
        // Build a nodeId remap from applied ChangeRecords so peerDependencies
        // and conditions survive replaceNode / replacePeerContext mutations.
        const idRemap = new Map<string, string>()
        for (const rec of result.applied) {
          if (rec.kind === 'node-replaced' || rec.kind === 'peer-context-replaced') {
            // rec.subject is the NEW id; we need the old id to find the sidecar entry.
            // We cannot recover the old id from a ChangeRecord alone, but we can scan
            // the old graph's nodes and see which ones are missing in the new graph.
            // Rather than a full scan here, we rely on `remapSidecar` which iterates
            // the old sidecar's keyed entries and maps unknown ids through the remap.
            // Since we don't track old→new pairs in ChangeRecord, we pass an empty
            // remap Map and let `remapSidecar`'s fallback (`?? oldId`) handle it —
            // unchanged ids (most cases) survive as-is; replaced ids whose old-id
            // no longer exists in nextGraph are simply pruned by `pruneSidecar`.
            void rec
          }
        }
        const nextNodes = new Map<string, Node>()
        // No old→new id mapping available from ChangeRecord; metadata (cacheKey etc.)
        // is global and does not need remapping. peerDependencies/conditions that refer
        // to a replaced node's old id will be pruned by the nextGraph membership check
        // inside remapSidecar — matching the behaviour of enrichFamily.
        const nextSidecar = remapSidecar(sidecar, nextNodes, result.graph)
        // If remapSidecar pruned everything (replaced nodes), fall back to at least
        // preserving the format-level metadata (cacheKey, compressionLevel, etc.)
        // which is not node-keyed and should always survive any mutation.
        const effectiveSidecar: YarnBerryFamilySidecar = isEmptySidecar(nextSidecar) && sidecar.metadata !== undefined
          ? { metadata: sidecar.metadata }
          : nextSidecar
        rememberSidecar(result.graph, effectiveSidecar)
        return {
          ...result,
          graph: withSidecarPropagation(result.graph, effectiveSidecar),
        }
      }
      return result
    },
  }
  // Register the sidecar on the proxy instance too so that stringify works
  // when called with the proxy directly (not just with the underlying graph).
  sidecarByGraph.set(proxy, sidecar)
  return proxy
}

export function rawPeerDependenciesBlockOfNode(graph: Graph, nodeId: string): SymlMap | undefined {
  const peerDependencies = sidecarByGraph.get(graph)?.peerDependencies?.get(nodeId)
  return peerDependencies === undefined ? undefined : coerceSymlMap(peerDependencies)
}

export function rawConditionsBlockOfNode(graph: Graph, nodeId: string): SymlMap | undefined {
  const conditions = sidecarByGraph.get(graph)?.conditions?.get(nodeId)
  return conditions === undefined ? undefined : coerceSymlMap(conditions)
}

/**
 * Pull the package name out of an `npm:` resolution locator
 * (`<name>@npm:<version>`). Returns undefined for any non-yarn-locator
 * shape — bare URLs (yarn-classic cross-format input), git resolutions,
 * workspace/patch protocols, `unknown`-canonical sentinels — so the
 * caller falls back to the entry-key's `first.name`.
 *
 * Restricted to the `<name>@npm:<rest>` shape: only when parseSpec returns
 * protocol === 'npm' AND the name looks like a package identifier (no
 * URL-host shape like `https://...`). Cross-format inputs frequently
 * carry a tarball URL as the resolution string; parseSpec's `@` scan
 * happily eats the URL's `@` at the host boundary, so the protocol-only
 * test is insufficient.
 */
function nameFromResolutionLocator(resolution: string): string | undefined {
  // Bail on URL-shaped strings — only yarn-berry locators
  // (`<name>@<protocol>:...`) carry an authoritative package name.
  if (/^[a-z][a-z0-9+.-]*:\/\//i.test(resolution)) return undefined
  try {
    const part = parseSpec(resolution)
    if (part.protocol !== 'npm') return undefined
    // Sanity: the name slot must look like an npm package name (no
    // path separators / URL host artifacts). Scoped names allowed.
    if (part.name.includes('/') && !part.name.startsWith('@')) return undefined
    if (part.name.includes(':')) return undefined
    return part.name
  } catch {
    return undefined
  }
}

function parseSpec(raw: string): SpecPart {
  const startFrom = raw[0] === '@' ? 1 : 0
  let sepIdx = -1
  for (let i = startFrom; i < raw.length; i++) {
    if (raw[i] === '@') { sepIdx = i; break }
  }
  if (sepIdx <= 0) {
    throw new LockfileError({
      code: 'PARSE_FAILED',
      message: `bad entry-spec, no protocol separator: ${raw}`,
    })
  }
  const name = raw.slice(0, sepIdx)
  const rest = raw.slice(sepIdx + 1)
  const colon = rest.indexOf(':')
  // Yarn 4 occasionally emits a bare `<name>@<version>` half in a compound
  // entry-key when a workspace package is also published to the npm registry
  // (e.g. `"@scope/pkg@1.14.1, @scope/pkg@workspace:packages/pkg"`).
  // Per ADR-0016 §B `npm:` is the default protocol — synthesise it so the
  // grammar stays uniform downstream (matches `entryKeyRangeOf`).
  if (colon < 0) {
    return { name, protocol: 'npm', spec: rest }
  }
  return { name, protocol: rest.slice(0, colon), spec: rest.slice(colon + 1) }
}

function parseEntryKey(key: string): SpecPart[] {
  return key.split(', ').map(spec => parseSpec(spec.trim()))
}

function workspacePathOf(spec: string): string {
  if (spec === '.') return ''
  if (spec.startsWith('./')) return spec.slice(2)
  return spec
}

// Workspace-spec discriminator: returns the workspace-protocol spec body
// (path or range marker) for an entry IFF the entry represents a workspace
// member. The canonical signal is the `resolution` field (`<n>@workspace:<path>`,
// per ADR-0014 §4.F3 — workspace identity is per-format and lives on
// `Node.workspacePath`); compound entries (e.g. `<n>@npm:<ver>, <n>@workspace:<path>`)
// may list an `npm:` alias ahead of the `workspace:` spec lexically, so
// keying off `specs[0].protocol` misclassifies the entry as non-workspace
// and breaks ADR-0017 seal (`workspace node has incoming edges` because
// the source workspace lost its `workspacePath`). Order of precedence:
//
// 1. parse `resolution` if present and prefixed with `<n>@workspace:`
//    — single canonical, immune to spec ordering;
// 2. otherwise scan all specs for `protocol === 'workspace'` and prefer the
//    one with a concrete path (not the range markers `^`, `~`, `*`) so
//    `workspacePath` is the filesystem location, not a range;
// 3. otherwise fall back to `first.spec` when `first.protocol === 'workspace'`
//    — legacy single-spec workspace shape, kept for parity.
function workspaceSpecOfEntry(
  resolution: string | undefined,
  specs: SpecPart[],
  first: SpecPart,
): string | undefined {
  if (resolution !== undefined) {
    const colon = resolution.indexOf('@workspace:')
    if (colon > 0) return resolution.slice(colon + '@workspace:'.length)
  }
  const workspaceSpecs = specs.filter(s => s.protocol === 'workspace')
  const withPath = workspaceSpecs.find(s => s.spec !== '^' && s.spec !== '~' && s.spec !== '*')
  if (withPath !== undefined) return withPath.spec
  if (workspaceSpecs.length > 0) return workspaceSpecs[0]!.spec
  return first.protocol === 'workspace' ? first.spec : undefined
}

function asMap(value: SymlValue | undefined): SymlMap | undefined {
  return value && typeof value === 'object' ? value : undefined
}

function asString(value: SymlValue | undefined): string | undefined {
  return typeof value === 'string' ? value : undefined
}

function validateMetadata(ast: SymlMap, config: YarnBerryFamilyConfig): SymlMap | undefined {
  const meta = asMap(ast['__metadata'])
  if (!meta) {
    throw new LockfileError({
      code: 'FORMAT_MISMATCH',
      message: 'missing __metadata block',
    })
  }
  if (asString(meta['version']) !== String(config.lockfileVersion)) {
    throw new LockfileError({
      code: 'FORMAT_MISMATCH',
      message: `expected __metadata.version: ${config.lockfileVersion}, got ${JSON.stringify(meta['version'])}`,
    })
  }

  const extras: SymlMap = {}
  for (const [key, value] of Object.entries(meta)) {
    if (key === 'version') continue
    const cloned = cloneSymlValue(value)
    if (cloned !== undefined) {
      extras[key] = cloned
    }
  }
  return Object.keys(extras).length > 0 ? extras : undefined
}

function entryKeyOfNode(graph: Graph, node: Node): string {
  const primary = primarySpecOfNode(node)
  const specs = new Set<string>([primary])
  const patchBase = baseSpecOfPatchedNode(node)
  if (patchBase !== undefined) specs.add(patchBase)

  for (const edge of graph.in(node.id)) {
    if (edge.kind === 'peer') continue
    if (edge.attrs?.range !== undefined) {
      // Aliased incoming edge — its descriptor key in the parent's
      // dependencies block is the alias, not `node.name`. The entry-key
      // half must reflect that so reparse `specIndex.set` registers the
      // alias lookup correctly. Canonical (non-aliased) edges keep the
      // node's actual name.
      const specName = edge.attrs.alias ?? node.name
      specs.add(`${specName}@${entryKeyRangeOf(edge.attrs.range)}`)
    }
  }

  const rest = Array.from(specs).filter(spec => spec !== primary).sort(cmpStr)
  return [primary, ...rest].join(', ')
}

function primarySpecOfNode(node: Node): string {
  if (node.workspacePath !== undefined) {
    return `${node.name}@workspace:${node.workspacePath === '' ? '.' : node.workspacePath}`
  }

  const exact = exactSpecOfResolution(node)
  return exact ?? `${node.name}@npm:${node.version}`
}

function exactSpecOfResolution(node: Node): string | undefined {
  if (node.resolution === undefined) return undefined
  if (node.resolution.startsWith(`${node.name}@patch:`)) {
    return node.resolution
  }
  return node.resolution.startsWith(`${node.name}@`) ? node.resolution : undefined
}

function baseSpecOfPatchedNode(node: Node): string | undefined {
  if (node.resolution === undefined || !node.resolution.startsWith(`${node.name}@patch:`)) return undefined
  const locator = patchLocatorOfResolution(node.resolution)
  if (locator === undefined) return undefined
  return baseSpecOfPatchLocator(locator)
}

function baseSpecOfPatchLocator(locator: string): string | undefined {
  if (!locator.startsWith('patch:')) return undefined
  const hashIdx = locator.indexOf('#')
  const encoded = hashIdx >= 0
    ? locator.slice('patch:'.length, hashIdx)
    : locator.slice('patch:'.length)
  try {
    return decodeURIComponent(encoded)
  } catch {
    return undefined
  }
}

function entryOfNode(
  graph: Graph,
  node: Node,
  config: YarnBerryFamilyConfig,
  emitDiagnostic: (diagnostic: Diagnostic) => void,
  cacheKey: string | undefined,
): SymlMap {
  const payload = graph.tarballOf(node.id)
  const entry: SymlMap = {
    version: node.version,
    resolution: resolutionOfNode(node, payload?.resolution, emitDiagnostic),
  }

  // yarn-berry's on-disk format has a single `dependencies:` block per entry —
  // no separate `devDependencies` block. ADR-0019 §C derives `dev` edges at the
  // workspace root from manifests; merge them with `dep` on emit so the
  // classification survives stringify (parse-side will collapse back to `dep`
  // per §C's "no on-lockfile signal" table).
  const dependencies = edgeBlockOfKinds(graph, node, ['dep', 'dev'], config)
  if (dependencies !== undefined) entry['dependencies'] = dependencies

  const optionalDependencies = edgeBlockOfKinds(graph, node, ['optional'], config)
  if (optionalDependencies !== undefined) entry['optionalDependencies'] = optionalDependencies

  const peerDependencies = extraBlockOfNode(node, 'peerDependencies')
    ?? rawPeerDependenciesBlockOfNode(graph, node.id)
    ?? edgeBlockOfKinds(graph, node, ['peer'], config, { skipMissingRange: true })
  if (peerDependencies !== undefined) entry['peerDependencies'] = peerDependencies

  const peerDependenciesMeta = extraBlockOfNode(node, 'peerDependenciesMeta')
  if (peerDependenciesMeta !== undefined) entry['peerDependenciesMeta'] = peerDependenciesMeta

  const dependenciesMeta = extraBlockOfNode(node, 'dependenciesMeta')
  if (dependenciesMeta !== undefined) entry['dependenciesMeta'] = dependenciesMeta

  const bin = binBlockOfNode(node, payload)
  if (bin !== undefined) entry['bin'] = bin

  entry['linkType'] = node.workspacePath !== undefined ? 'soft' : 'hard'
  entry['languageName'] = node.workspacePath !== undefined ? 'unknown' : 'node'

  const conditions = rawConditionsBlockOfNode(graph, node.id) ?? extraBlockOfNode(node, 'conditions')
  if (conditions !== undefined) {
    if (config.conditionsAllowed) {
      entry['conditions'] = conditions
    } else {
      emitDiagnostic({
        code: `${config.codePrefix}_CONDITIONS_DROPPED`,
        subject: node.id,
        severity: 'warning',
        message: `conditions block is unsupported in yarn-berry-v${config.lockfileVersion}; dropping on emit`,
      })
    }
  }

  const checksum = checksumOfPayload(payload, config, cacheKey, node.id, emitDiagnostic)
  if (checksum !== undefined) entry['checksum'] = checksum
  if (node.peerContext.length > 0) {
    emitDiagnostic({
      code: `${config.codePrefix}_PEER_VIRT_FLATTENED`,
      subject: node.id,
      severity: 'warning',
      message: `peerContext ${JSON.stringify(node.peerContext)} flattens to ${entry.resolution}`,
    })
  }

  return entry
}

function resolutionOfNode(
  node: Node,
  canonical: ResolutionCanonical | undefined,
  emitDiagnostic: (diagnostic: Diagnostic) => void,
): string {
  if (node.patch !== undefined) {
    // Intra-family path: parse-side carries the verbatim `@patch:` locator
    // on `node.resolution`. If it survived to emit, stringify it directly —
    // patch identity round-trips losslessly regardless of whether `node.patch`
    // is canonical (128-hex sha512) or sentinel (`unresolved-<sha256>`).
    if (node.resolution !== undefined && patchLocatorOfResolution(node.resolution) !== undefined) {
      return node.resolution
    }
    // Local-artefact locator-disambiguator path: the patch slot is a sentinel
    // keyed off the locator string (parse-side disambiguation per ADR-0011),
    // NOT a real patch — covers `link:` / `portal:` references AND a
    // `::locator=`-qualified `file:` local-tarball alias (Bug #76). The
    // verbatim resolution carries the locator + `::locator=` qualifier intact,
    // so round-trip is lossless — no `RECIPE_FEATURE_DROPPED` to emit.
    if (node.resolution !== undefined && isLocalLocatorDisambiguatedResolution(node.resolution, node.name)) {
      return node.resolution
    }
    // Cross-family / mutate path: no reconstructable yarn `patch:` locator
    // is available on the Graph. Two cases collapse here:
    //   - Sentinel `unresolved-<sha256>`: input is per-PM (pnpm hashes
    //     `<name>@<version>:<literalKey>`; yarn hashes the locator
    //     verbatim — ADR-0011), so the byte-identity is unrecoverable.
    //   - Canonical 128-hex sha512 (F2): byte-identity exists, but yarn
    //     locators encode source-path + version params, which the canonical
    //     hex carries no path info to reconstruct.
    // Either way, per ADR-0014 §5 graceful-degradation precedent, emit
    // `RECIPE_FEATURE_DROPPED (feature='patch')` and fall through to emit
    // the base resolution without a patch directive.
    emitDropped(
      node.id,
      'patch',
      'patched node lacks reconstructable yarn patch: locator',
      emitDiagnostic,
    )
    // fall through to base-resolution emit
  }

  // PM-native sidecar wins for same-format round-trip; cross-format input
  // delivers a foreign shape (URL / pnpm `link:`), which yarn-berry passes
  // through verbatim. Re-parse populates the canonical from the verbatim
  // string per ADR-0014 §4.F3, so identity survives the conversion even
  // when the source-side adapter's sidecar leaks through.
  if (node.resolution !== undefined) return node.resolution
  if (node.workspacePath !== undefined) {
    return `${node.name}@workspace:${node.workspacePath === '' ? '.' : node.workspacePath}`
  }
  if (canonical !== undefined) {
    return stringifyForYarnBerry(canonical, { name: node.name, version: node.version })
  }
  return `${node.name}@npm:${node.version}`
}

function edgeBlockOfKinds(
  graph: Graph,
  node: Node,
  kinds: readonly EdgeKind[],
  config: YarnBerryFamilyConfig,
  options: { skipMissingRange?: boolean } = {},
): SymlMap | undefined {
  const edges = kinds.flatMap(kind => graph.out(node.id, kind))
  if (edges.length === 0) return undefined

  const blockEntries: Array<[string, string]> = []
  const seen = new Set<string>()

  for (const edge of edges) {
    const dst = graph.getNode(edge.dst)
    if (dst === undefined) {
      throw new LockfileError({
        code: 'INVARIANT_VIOLATION',
        message: `edge from ${node.id} points to missing node ${edge.dst}`,
      })
    }
    if (edge.attrs?.range === undefined) {
      if (options.skipMissingRange) {
        continue
      }
      throw new LockfileError({
        code: 'MISSING_REQUIRED_FIELD',
        message: `edge ${node.id} -> ${edge.dst} (${edge.kind}) requires attrs.range for emit`,
      })
    }

    // Aliased descriptors emit under the alias key (the original parent-
    // manifest key); the value stays a full `npm:<dst>@<range>` locator
    // so reparse can resolve back to the same target via specIndex.
    // Canonical descriptors emit under the dst's actual name.
    const aliased = edge.attrs.alias !== undefined
    const depName = aliased ? edge.attrs.alias! : dst.name
    if (seen.has(depName)) {
      throw new LockfileError({
        code: 'INVARIANT_VIOLATION',
        message: `cannot emit duplicate ${edge.kind} dependency key ${depName} from ${node.id}`,
      })
    }
    seen.add(depName)
    blockEntries.push([depName, emittedRangeOfEdge(edge.kind, edge.attrs.range, config, aliased)])
  }

  if (blockEntries.length === 0) return undefined
  blockEntries.sort((a, b) => cmpStr(a[0]!, b[0]!))

  const block: SymlMap = {}
  for (const [name, range] of blockEntries) {
    block[name] = range
  }
  return block
}

function emittedRangeOfEdge(kind: EdgeKind, range: string, config: YarnBerryFamilyConfig, aliased: boolean = false): string {
  if (kind === 'peer') return range
  // Aliased edges encode `npm:<target>@<range>` as their range value —
  // the npm: prefix is structural (it carries the alias-target name), not
  // a bare-form decoration, so the bare-emit shortener does NOT strip it.
  if (aliased) return range
  if (config.rangeEmit !== 'bare') return range
  return range.startsWith('npm:') ? range.slice('npm:'.length) : range
}

// Yarn-berry v8/v9 era default cacheKey. Used only when neither
// `options.cacheKey` nor a sidecar-derived value is available — typically
// when a mutated Graph (sidecar absent post-`mutate()`) gets stringified.
// Independent of `__metadata.cacheKey` emission: this default is for the
// integrity-translation slot only and does NOT cause `__metadata.cacheKey`
// to be written out (that path stays nullable per the "omits unless
// requested" contract).
const DEFAULT_CACHEKEY_V8_V9 = '10c0'

function checksumOfPayload(
  payload: TarballPayload | undefined,
  config: YarnBerryFamilyConfig,
  cacheKey: string | undefined,
  nodeId: string,
  emitDiagnostic: (diagnostic: Diagnostic) => void,
): string | undefined {
  const integrity = payload?.integrity
  if (integrity === undefined) return undefined

  // Berry `checksum` is a digest of yarn's zip-cache. ONLY a `berry-zip`-origin
  // sha512 may fill it; a tarball sha512 (npm/pnpm/bun/yarn-classic) is a
  // different artefact and MUST NOT be re-encoded here (yarn rejects it on
  // install). With no berry-zip digest the checksum line is OMITTED and
  // RECIPE_INTEGRITY_INCOMPLETE is emitted; yarn recomputes the digest on install.
  const hex = emitBerryChecksum(integrity)
  if (hex === undefined) {
    emitIntegrityIncomplete(
      nodeId,
      config.codePrefix,
      'source carries no yarn zip-cache (berry-zip) digest',
      emitDiagnostic,
    )
    return undefined
  }
  // Precedence (ADR-0031 round-trip):
  //   1. A per-node cacheKey captured at parse (`payload.berryChecksumCacheKey`)
  //      is reproduced verbatim for EVERY generation — this is what keeps a
  //      yarn-2.0 v4 `2/<hex>` round-tripping (v4 has checksumPrefix=false yet
  //      a parsed prefix must survive) AND v8/v9 `10c0/<hex>` byte-faithful.
  //   2. With no captured key but a prefix-era config (v8/v9/v10), fall back to
  //      the global cacheKey (`__metadata.cacheKey` / options / default) — the
  //      cross-family-convert and post-`mutate()` paths where the per-node
  //      sidecar was never set.
  //   3. Otherwise (bare-era v4/v5/v6/v7, no captured key) emit bare hex.
  const perNodeCacheKey = payload?.berryChecksumCacheKey
  if (perNodeCacheKey !== undefined) return `${perNodeCacheKey}/${hex}`
  return config.checksumPrefix ? `${cacheKey ?? DEFAULT_CACHEKEY_V8_V9}/${hex}` : hex
}

function extraBlockOfNode(node: Node, field: string): SymlMap | undefined {
  return coerceSymlMap((node as unknown as Record<string, unknown>)[field])
}

function coerceSymlMap(value: unknown): SymlMap | undefined {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return undefined

  const raw = value as Record<string, unknown>
  const block: SymlMap = {}
  for (const key of Object.keys(raw).sort(cmpStr)) {
    const coerced = coerceSymlValue(raw[key])
    if (coerced !== undefined) {
      block[key] = coerced
    }
  }

  return Object.keys(block).length > 0 ? block : undefined
}

function coerceSymlValue(value: unknown): SymlValue | undefined {
  if (typeof value === 'string') return value
  if (typeof value === 'number' || typeof value === 'boolean') return String(value)
  return coerceSymlMap(value)
}

function cloneSymlValue(value: SymlValue | undefined): SymlValue | undefined {
  if (typeof value === 'string') return value
  if (value === undefined) return undefined
  return coerceSymlMap(value)
}

function binBlockOfNode(node: Node, payload: TarballPayload | undefined): SymlMap | undefined {
  if (payload?.bin === undefined) return undefined
  if (typeof payload.bin === 'string') {
    return { [node.name]: payload.bin }
  }

  const block: SymlMap = {}
  for (const name of Object.keys(payload.bin).sort(cmpStr)) {
    const target = payload.bin[name]
    if (target !== undefined) block[name] = target
  }
  return Object.keys(block).length > 0 ? block : undefined
}

function extractPatchFingerprint(
  nodeId: string,
  resolution: string,
  workspaceRoot: string | undefined,
): { patch: string; diagnostic?: Diagnostic } | undefined {
  const locator = patchLocatorOfResolution(resolution)
  if (locator === undefined) return undefined

  const source = patchSourceOfLocator(locator)
  if (source === undefined) {
    return unresolvedPatch(nodeId, locator, 'patch locator has no source fragment')
  }

  if (source.startsWith('~builtin<')) {
    const yarnMajor = yarnMajorOfBuiltinPatch(resolution)
    if (yarnMajor === undefined) {
      return unresolvedPatch(nodeId, locator, 'builtin patch yarn-major is unavailable at parse time')
    }
    // Builtin patches hash a synthetic string (no on-disk source); F5 byte
    // normalisation is inapplicable.
    return { patch: sha512Hex(`${yarnMajor}:${source}`) }
  }

  if (workspaceRoot === undefined) {
    return unresolvedPatch(nodeId, locator, 'workspaceRoot is unavailable at parse time')
  }

  const bytes = readWorkspaceFileBytes(workspaceRoot, source, locator)
  if (bytes === undefined) {
    return unresolvedPatch(nodeId, locator, 'patch file is unavailable at parse time')
  }

  // ADR-0014 §4.F5 — apply CRLF / BOM byte normalisation BEFORE the F2
  // sha512 fingerprint; emit `RECIPE_PATCH_NORMALISED` (info) when ≥ 1
  // byte changed so cross-platform CRLF rewrites surface in diagnostics.
  // Combined helper avoids a second F5 scan inside canonicalHashOfBytes.
  const { hash: patch, normalised: didNormalise } = patchHashAndNormaliseBytes(bytes)
  return didNormalise
    ? { patch, diagnostic: patchNormalisedDiagnostic(nodeId) }
    : { patch }
}

function patchLocatorOfResolution(resolution: string): string | undefined {
  if (resolution.startsWith('patch:')) return resolution
  const idx = resolution.indexOf('@patch:')
  return idx >= 0 ? resolution.slice(idx + 1) : undefined
}

function patchSourceOfLocator(locator: string): string | undefined {
  const hashIdx = locator.indexOf('#')
  if (hashIdx < 0) return undefined
  const paramsIdx = locator.indexOf('::', hashIdx + 1)
  const source = paramsIdx < 0
    ? locator.slice(hashIdx + 1)
    : locator.slice(hashIdx + 1, paramsIdx)
  return isDegeneratePatchSource(source) ? undefined : source
}

function isDegeneratePatchSource(source: string): boolean {
  let decoded: string
  try {
    decoded = decodeURIComponent(source)
  } catch {
    return false
  }

  const trimmed = decoded.trim()
  if (trimmed === '') return true
  if (path.posix.isAbsolute(trimmed)) return false

  const segments = path.posix.normalize(trimmed).split('/').filter(segment => segment !== '' && segment !== '.')
  return segments.length === 0
}

function yarnMajorOfBuiltinPatch(_resolution: string): string | undefined {
  return undefined
}

function unresolvedPatch(nodeId: string, locator: string, reason: string): { patch: string; diagnostic: Diagnostic } {
  return {
    patch: sentinelHashOfLocator(locator),
    diagnostic: {
      code: 'YARN_BERRY_PATCH_UNRESOLVED',
      subject: nodeId,
      severity: 'warning',
      message: `${reason}; using sentinel for ${locator}`,
    },
  }
}

function sha512Hex(value: string | Uint8Array): string {
  return createHash('sha512').update(value).digest('hex')
}

// Compose a tailored IRREDUCIBLE_LOSS hint for the parse-time NodeId
// collision case. Scans the previously-seen entry list for the colliding
// entry to surface BOTH `resolution:` strings — so callers can tell at a
// glance whether they hit (a) an npm: alias, (b) a `patch:` collision,
// (c) a `link:` / `portal:` locator collision (workspace-link variant).
// The hint is best-effort: when the prior entry can't be matched by raw
// key (compound entry-keys split by `, `), we fall back to the legacy
// generic hint that names all three known causes.
function irreducibleCollisionMessage(
  id: string,
  currentKey: string,
  priorEntries: ReadonlyArray<{ key: string; value: SymlMap; specs: SpecPart[] }>,
): string {
  const currentEntry = priorEntries.find(e => e.key === currentKey)
  const currentResolution = currentEntry !== undefined ? asString(currentEntry.value['resolution']) : undefined

  // The prior entry that landed on `id`: scan the list from the start; the
  // collision is by definition between the current entry and the FIRST
  // prior entry that derived the same NodeId. Without re-deriving NodeIds
  // here we approximate by name+version match.
  const currentFirst = currentEntry?.specs[0]
  const priorEntry = currentEntry === undefined ? undefined : priorEntries.find(e => {
    if (e.key === currentKey) return false
    const otherFirst = e.specs[0]
    if (otherFirst === undefined || currentFirst === undefined) return false
    if (otherFirst.name !== currentFirst.name) return false
    return asString(e.value['version']) === asString(currentEntry.value['version'])
  })
  const priorResolution = priorEntry !== undefined ? asString(priorEntry.value['resolution']) : undefined

  const isLink = (r: string | undefined): boolean =>
    r !== undefined && (r.includes('@link:') || r.includes('@portal:'))
  const isPatch = (r: string | undefined): boolean =>
    r !== undefined && r.includes('@patch:')

  let hint = 'likely npm: alias, patch: collision, or workspace link: locator collision'
  if (isLink(currentResolution) || isLink(priorResolution)) {
    hint = 'likely workspace link: / portal: locator collision (yarn `::locator=` qualifier was lost)'
  } else if (isPatch(currentResolution) || isPatch(priorResolution)) {
    hint = 'likely patch: collision'
  }

  const resolutions = [priorResolution, currentResolution].filter((r): r is string => typeof r === 'string')
  const tail = resolutions.length > 0 ? ` — resolutions: [${resolutions.map(r => JSON.stringify(r)).join(', ')}]` : ''
  return `two entries collapse onto NodeId ${id} — ${hint}${tail}`
}

function stringRecordOfBlock(block: SymlMap | undefined): Record<string, string> | undefined {
  if (!block) return undefined

  const out: Record<string, string> = {}
  for (const [key, value] of Object.entries(block)) {
    if (typeof value === 'string') out[key] = value
  }
  return Object.keys(out).length > 0 ? out : undefined
}

function sortPeerContext(peers: readonly string[]): string[] {
  return peers.slice().sort((a, b) => {
    const nameCmp = cmpStr(nameOf(a), nameOf(b))
    return nameCmp !== 0 ? nameCmp : cmpStr(a, b)
  })
}

function deriveFinalNodeIds(graph: Graph, derivedPeersByNodeId: Map<string, DerivedPeer[]>): Map<string, string> {
  const finalIds = new Map<string, string>()
  const nodes = Array.from(graph.nodes())
  for (const node of nodes) {
    finalIds.set(node.id, node.id)
  }

  for (let i = 0; i < nodes.length; i++) {
    let changed = false
    for (const node of nodes) {
      const derivedPeers = derivedPeersByNodeId.get(node.id)
      if (derivedPeers === undefined) continue

      const peerContext = sortPeerContext(derivedPeers.map(peer => finalIds.get(peer.dstOldId) ?? peer.dstOldId))
      const nextId = serializeNodeId(node.name, node.version, peerContext, node.patch)
      if (finalIds.get(node.id) !== nextId) {
        finalIds.set(node.id, nextId)
        changed = true
      }
    }
    if (!changed) return finalIds
  }

  throw new LockfileError({
    code: 'INVARIANT_VIOLATION',
    message: 'peer enrichment did not converge',
  })
}

function isDerivedWorkspaceRange(range: string | undefined): boolean {
  return typeof range === 'string' && range.startsWith('workspace:')
}

/**
 * F4 yarn-berry attribution rule (ADR-0014 §4.F4): given an eligible
 * source edge + workspace-member destination, derive the `{ workspace:
 * true, workspaceRange }` attrs payload. yarn-berry takes the verbatim
 * `workspace:<spec>` range от disk as the source-side specifier;
 * `resolvedVersion` is best-effort `dst.version` (`0.0.0-use.local`
 * sentinel when manifests are absent). Single source of truth shared
 * by parse-time `markWorkspaceEdgesAtParse` AND enrich-time rewiring
 * — the rule is yarn-berry-specific (other adapters carry different
 * workspace shapes) so it stays local rather than living in `recipe/`.
 */
function deriveMarkedWorkspaceAttrs(attrs: EdgeAttrs | undefined, dst: Node): EdgeAttrs {
  const rawSpecifier = attrs?.range ?? ''
  const workspaceRange = dst.version !== undefined && dst.version !== ''
    ? { specifier: rawSpecifier, resolvedVersion: dst.version }
    : { specifier: rawSpecifier }
  return { ...attrs, workspace: true, workspaceRange }
}

/**
 * Post-seal mutation: mark `workspace: true` on every edge whose range
 * carries the `workspace:` protocol AND whose target is a workspace
 * member; populate the canonical `attrs.workspaceRange` sidecar per
 * ADR-0014 §4.F4. Called from parseFamily so the public parse() surface
 * delivers F4-ready edges without requiring an explicit enrich step.
 */
function markWorkspaceEdgesAtParse(graph: Graph): Graph {
  const edgesToMark: Array<{ src: string; dst: string; kind: EdgeKind; attrs: EdgeAttrs }> = []
  for (const node of graph.nodes()) {
    for (const edge of graph.out(node.id)) {
      if (edge.kind === 'peer') continue
      if (edge.attrs?.workspace === true) continue
      if (!isDerivedWorkspaceRange(edge.attrs?.range)) continue
      const dst = graph.getNode(edge.dst)
      if (dst?.workspacePath === undefined) continue
      edgesToMark.push({
        src: edge.src,
        dst: edge.dst,
        kind: edge.kind,
        attrs: deriveMarkedWorkspaceAttrs(edge.attrs, dst),
      })
    }
  }
  if (edgesToMark.length === 0) return graph
  return graph.mutate(m => {
    for (const e of edgesToMark) {
      m.removeEdge(e.src, e.dst, e.kind)
      m.addEdge(e.src, e.dst, e.kind, e.attrs)
    }
  }).graph
}

function ambiguousPeerMessage(peerName: string, candidates: readonly string[]): string {
  return `peer "${peerName}" matches multiple installed versions: [${candidates.join(', ')}]`
}

function finalizePendingDiagnostic(diagnostic: PendingDiagnostic, nextNodes: Map<string, Node>): Diagnostic {
  const subject = nextNodes.get(diagnostic.subject)?.id ?? diagnostic.subject
  const message = diagnostic.code.endsWith('_PEER_AMBIGUOUS')
    && diagnostic.peerName !== undefined
    && diagnostic.candidateIds !== undefined
    ? ambiguousPeerMessage(
      diagnostic.peerName,
      diagnostic.candidateIds.map(candidateId => nextNodes.get(candidateId)?.id ?? candidateId),
    )
    : diagnostic.message

  return {
    code: diagnostic.code,
    severity: diagnostic.severity,
    subject,
    message,
  }
}

function graphNeedsWorkspaceAttribution(graph: Graph): boolean {
  for (const node of graph.nodes()) {
    for (const edge of graph.out(node.id)) {
      if (edge.kind === 'peer') continue
      if (edge.attrs?.workspace === true) continue
      if (!isDerivedWorkspaceRange(edge.attrs?.range)) continue
      if (graph.getNode(edge.dst)?.workspacePath !== undefined) return true
    }
  }
  return false
}

function addEdgesFromBlock(
  builder: ReturnType<typeof newBuilder>,
  srcId: string,
  block: SymlMap | undefined,
  kind: EdgeKind,
  index: Map<string, string>,
  diagnostics: Diagnostic[],
  srcResolution?: string,
): void {
  if (!block) return
  for (const [depName, depRange] of Object.entries(block)) {
    if (typeof depRange !== 'string') continue
    const normalizedRange = normalizedEdgeRange(kind, depRange)
    const lookup = `${depName}@${normalizedRange}`
    let dstId = index.get(lookup)
    if (dstId === undefined && srcResolution !== undefined && isLinkOrPortalRange(normalizedRange)) {
      // `link:` / `portal:` deps are recorded per consumer: yarn appends a
      // `::locator=<encoded-consumer-locator>` qualifier to the entry key so
      // the same on-disk path linked from different workspaces stays distinct
      // (see isLinkOrPortalResolution + the NodeId-disambiguation note above).
      // The deps-block descriptor is bare (no qualifier), so reconstruct the
      // locator-qualified specIndex key from the source consumer's own
      // resolution. encodeURIComponent matches yarn's entry-key encoding
      // (`@`->%40, `:`->%3A, `/`->%2F), e.g. `pkg@workspace:.` ->
      // `pkg%40workspace%3A.`.
      const qualified = `${lookup}::locator=${encodeURIComponent(srcResolution)}`
      dstId = index.get(qualified)
    }
    if (!dstId) {
      diagnostics.push({
        code: 'YARN_BERRY_UNRESOLVED_DEP',
        subject: srcId,
        severity: 'warning',
        message: `dependency ${depName}=${depRange} from ${srcId} has no matching lockfile entry`,
      })
      continue
    }
    // EdgeAttrs.alias — preserved when the parent's dependencies-block key
    // (`depName`) differs from the target's actual name. Yarn-berry encodes
    // npm-alias deps as `"<alias>": "npm:<target>@<range>"`; the resolved
    // node carries the target's name, and the alias lives only as the
    // descriptor key in the source manifest. Identity-aware so the seal
    // permits both the canonical and aliased edges from the same parent
    // to the same dst (e.g. a lockfile declaring both
    // `@scope/pkg` and an npm-aliased `@scope/pkg--variant`
    // against the same target).
    const dstName = nameOf(dstId)
    const attrs: { range: string; alias?: string } = { range: normalizedRange }
    if (depName !== dstName) attrs.alias = depName
    builder.addEdge(srcId, dstId, kind, attrs)
  }
}

function normalizedEdgeRange(kind: EdgeKind, range: string): string {
  if (kind === 'peer') return range
  return hasExplicitProtocol(range) ? range : `npm:${range}`
}

function hasExplicitProtocol(range: string): boolean {
  const colonIdx = range.indexOf(':')
  if (colonIdx <= 0) return false
  const prefix = range.slice(0, colonIdx)
  return /^[a-z][a-z0-9+.-]*$/i.test(prefix)
}

function isLinkOrPortalRange(range: string): boolean {
  return range.startsWith('link:') || range.startsWith('portal:')
}

function remapSidecar(
  sidecar: YarnBerryFamilySidecar,
  nextNodes: Map<string, Node>,
  nextGraph: Graph,
): YarnBerryFamilySidecar {
  const remapped: YarnBerryFamilySidecar = {}

  if (sidecar.peerDependencies !== undefined) {
    const nextPeerDependencies = new Map<string, Record<string, string>>()
    for (const [oldId, block] of sidecar.peerDependencies) {
      nextPeerDependencies.set(nextNodes.get(oldId)?.id ?? oldId, block)
    }
    if (nextPeerDependencies.size > 0) remapped.peerDependencies = nextPeerDependencies
  }

  if (sidecar.conditions !== undefined) {
    const nextConditions = new Map<string, SymlMap>()
    for (const [oldId, block] of sidecar.conditions) {
      const nextId = nextNodes.get(oldId)?.id ?? oldId
      if (nextGraph.getNode(nextId) !== undefined) {
        nextConditions.set(nextId, block)
      }
    }
    if (nextConditions.size > 0) remapped.conditions = nextConditions
  }

  if (sidecar.metadata !== undefined) {
    remapped.metadata = sidecar.metadata
  }

  return remapped
}

function pruneSidecar(sidecar: YarnBerryFamilySidecar, nextGraph: Graph): YarnBerryFamilySidecar {
  const pruned: YarnBerryFamilySidecar = {}

  if (sidecar.peerDependencies !== undefined) {
    const nextPeerDependencies = new Map<string, Record<string, string>>()
    for (const [nodeId, block] of sidecar.peerDependencies) {
      if (nextGraph.getNode(nodeId) !== undefined) {
        nextPeerDependencies.set(nodeId, block)
      }
    }
    if (nextPeerDependencies.size > 0) pruned.peerDependencies = nextPeerDependencies
  }

  if (sidecar.conditions !== undefined) {
    const nextConditions = new Map<string, SymlMap>()
    for (const [nodeId, block] of sidecar.conditions) {
      if (nextGraph.getNode(nodeId) !== undefined) {
        nextConditions.set(nodeId, block)
      }
    }
    if (nextConditions.size > 0) pruned.conditions = nextConditions
  }

  if (sidecar.metadata !== undefined) {
    pruned.metadata = sidecar.metadata
  }

  return pruned
}

function isEmptySidecar(sidecar: YarnBerryFamilySidecar): boolean {
  return sidecar.peerDependencies === undefined
    && sidecar.conditions === undefined
    && sidecar.metadata === undefined
}

function unquoteMetadataScalar(output: string, key: string, value: string): string {
  const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const escapedValue = value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return output.replace(new RegExp(`^(  ${escapedKey}): "${escapedValue}"$`, 'm'), `$1: ${value}`)
}
