import { createHash } from 'node:crypto'
import path from 'node:path'
// @ts-ignore -- local fixture installs do not provide semver typings.
import semver from 'semver'
import {
  newBuilder,
  GraphError,
  type Graph,
  type Node,
  type EdgeKind,
  nameOf,
  serializeNodeId,
  type TarballPayload,
  toTarballKey,
  type TarballKeyInputs,
  type Diagnostic,
} from '../graph.ts'
import { LockfileError } from '../errors.ts'
import { readWorkspaceFileBytes } from './_path.ts'
import {
  parse as parseSyml,
  stringify as stringifySyml,
  type SymlMap,
  type SymlValue,
} from './_yarn-syml.ts'

const PREAMBLE =
  '# This file is generated by running "yarn install" inside your project.\n' +
  '# Manual changes might be lost - proceed with caution!'
const cmpStr = (a: string, b: string): number => a < b ? -1 : a > b ? 1 : 0
const EMPTY_SIDECAR: YarnBerryFamilySidecar = {}

export interface YarnBerryFamilyParseOptions {
  workspaceRoot?: string
}

export interface YarnBerryFamilyStringifyOptions {
  lineEnding?: 'lf' | 'crlf'
  cacheKey?: string
  onDiagnostic?: (diagnostic: Diagnostic) => void
}

export interface YarnBerryFamilyEnrichOptions {}
export interface YarnBerryFamilyOptimizeOptions {}

export interface YarnBerryFamilyConfig {
  lockfileVersion: number
  codePrefix: string
  rangeEmit: 'bare' | 'quoted-protocol'
  checksumPrefix: boolean
  conditionsAllowed: boolean
}

export interface YarnBerryFamilySidecar {
  peerDependencies?: Map<string, Record<string, string>>
  conditions?: Map<string, SymlMap>
  metadata?: SymlMap
}

interface SpecPart {
  name: string
  protocol: string
  spec: string
}

interface DerivedPeer {
  name: string
  range: string
  dstOldId: string
}

interface PendingDiagnostic extends Omit<Diagnostic, 'subject'> {
  subject: string
  candidateIds?: string[]
  peerName?: string
}

const sidecarByGraph = new WeakMap<Graph, YarnBerryFamilySidecar>()

export function checkFamily(input: string, config: YarnBerryFamilyConfig): boolean {
  const head = input.slice(0, 4096)
  return new RegExp(
    `^__metadata:\\s*[\\r\\n]+(?:[ \\t]+[^\\n]*[\\r\\n]+)*?[ \\t]+version:\\s*${config.lockfileVersion}\\s*(?:[\\r\\n]|$)`,
    'm',
  ).test(head)
}

export function parseFamily(
  input: string,
  options: YarnBerryFamilyParseOptions,
  config: YarnBerryFamilyConfig,
): { graph: Graph; sidecar: YarnBerryFamilySidecar } {
  const ast = parseSyml(input)
  const metadata = validateMetadata(ast, config)

  const builder = newBuilder()
  const diagnostics: Diagnostic[] = []
  const rawPeerDependencies = new Map<string, Record<string, string>>()
  const rawConditions = new Map<string, SymlMap>()

  const entries: Array<{ key: string; value: SymlMap; specs: SpecPart[] }> = []
  for (const [key, value] of Object.entries(ast)) {
    if (key === '__metadata') continue
    const valueMap = asMap(value)
    if (!valueMap) {
      diagnostics.push({
        code: 'YARN_BERRY_BAD_ENTRY',
        severity: 'warning',
        message: `entry ${JSON.stringify(key)} is not a block; skipping`,
      })
      continue
    }
    const specs = parseEntryKey(key)
    entries.push({ key, value: valueMap, specs })
  }

  const specIndex = new Map<string, string>()
  const seenIds = new Set<string>()

  for (const { key, value, specs } of entries) {
    const first = specs[0]
    if (!first) {
      throw new LockfileError({
        code: 'PARSE_FAILED',
        message: `entry ${JSON.stringify(key)} has empty spec`,
      })
    }
    const version = asString(value['version'])
    if (version === undefined) {
      throw new LockfileError({
        code: 'PARSE_FAILED',
        message: `entry ${JSON.stringify(key)} missing 'version'`,
      })
    }
    const id = `${first.name}@${version}`

    if (seenIds.has(id)) {
      throw new LockfileError({
        code: 'IRREDUCIBLE_LOSS',
        message: `two entries collapse onto NodeId ${id} — likely npm: alias or patch: collision`,
      })
    }
    seenIds.add(id)

    const resolution = asString(value['resolution'])
    const patchResult = resolution !== undefined
      ? extractPatchFingerprint(id, resolution, options.workspaceRoot)
      : undefined

    const node: Node = {
      id,
      name: first.name,
      version,
      peerContext: [],
    }
    if (resolution !== undefined) node.resolution = resolution
    if (patchResult?.patch !== undefined) node.patch = patchResult.patch
    if (first.protocol === 'workspace') {
      node.workspacePath = workspacePathOf(first.spec)
    }
    builder.addNode(node)
    if (patchResult?.diagnostic) diagnostics.push(patchResult.diagnostic)

    const peerDependencies = stringRecordOfBlock(asMap(value['peerDependencies']))
    if (peerDependencies !== undefined) {
      rawPeerDependencies.set(id, peerDependencies)
    }

    const conditions = coerceSymlMap(value['conditions'])
    if (conditions !== undefined) {
      rawConditions.set(id, conditions)
    }

    const payload: TarballPayload = {}
    const checksum = asString(value['checksum'])
    if (checksum !== undefined) payload.integrity = checksum
    const binMap = asMap(value['bin'])
    if (binMap) {
      const bin: Record<string, string> = {}
      for (const [name, target] of Object.entries(binMap)) {
        if (typeof target === 'string') bin[name] = target
      }
      if (Object.keys(bin).length > 0) payload.bin = bin
    }
    if (Object.keys(payload).length > 0) {
      builder.setTarball({ name: first.name, version, patch: patchResult?.patch }, payload)
    }

    for (const spec of specs) {
      const lookup = `${spec.name}@${spec.protocol}:${spec.spec}`
      specIndex.set(lookup, id)
    }
  }

  for (const { value, specs } of entries) {
    const first = specs[0]
    if (!first) continue
    const version = asString(value['version'])
    if (version === undefined) continue
    const srcId = `${first.name}@${version}`

    addEdgesFromBlock(builder, srcId, asMap(value['dependencies']), 'dep', specIndex, diagnostics)
    addEdgesFromBlock(builder, srcId, asMap(value['optionalDependencies']), 'optional', specIndex, diagnostics)
  }

  for (const diagnostic of diagnostics) builder.diagnostic(diagnostic)

  try {
    const graph = builder.seal()
    const sidecar: YarnBerryFamilySidecar = {}
    if (rawPeerDependencies.size > 0) sidecar.peerDependencies = rawPeerDependencies
    if (rawConditions.size > 0) sidecar.conditions = rawConditions
    if (metadata !== undefined) sidecar.metadata = metadata
    rememberSidecar(graph, sidecar)
    return { graph, sidecar }
  } catch (error) {
    if (error instanceof GraphError) {
      throw new LockfileError({
        code: 'PARSE_FAILED',
        message: `seal failed: ${error.message}`,
      })
    }
    throw error
  }
}

export function stringifyFamily(
  graph: Graph,
  config: YarnBerryFamilyConfig,
  options: YarnBerryFamilyStringifyOptions = {},
): { lockfile: string; diagnostics: Diagnostic[] } {
  const sidecar = sidecarByGraph.get(graph) ?? EMPTY_SIDECAR
  const diagnostics: Diagnostic[] = []
  const emitDiagnostic = (diagnostic: Diagnostic): void => {
    diagnostics.push(diagnostic)
    options.onDiagnostic?.(diagnostic)
  }

  const metadata: SymlMap = { version: String(config.lockfileVersion) }
  const cacheKey = options.cacheKey ?? asString(sidecar.metadata?.cacheKey)
  if (cacheKey !== undefined) {
    metadata['cacheKey'] = cacheKey
  }
  if (sidecar.metadata !== undefined) {
    for (const key of Object.keys(sidecar.metadata).sort(cmpStr)) {
      if (key === 'version' || key === 'cacheKey') continue
      const value = cloneSymlValue(sidecar.metadata[key])
      if (value !== undefined) {
        metadata[key] = value
      }
    }
  }

  const root: SymlMap = { __metadata: metadata }
  const entries = Array.from(graph.nodes(), node => ({
    nodeId: node.id,
    key: entryKeyOfNode(graph, node),
    value: entryOfNode(graph, node, config, emitDiagnostic),
  })).sort((a, b) => cmpStr(a.key, b.key))

  const seenIds = new Map<string, string>()
  for (const entry of entries) {
    const node = graph.getNode(entry.nodeId)
    const emitId = `${node?.name}@${node?.version}`
    const prevNodeId = seenIds.get(emitId)
    if (prevNodeId !== undefined) {
      throw new LockfileError({
        code: 'IRREDUCIBLE_LOSS',
        message: `duplicate node id collides on emit: ${emitId} from ${prevNodeId}, ${entry.nodeId}`,
      })
    }
    seenIds.set(emitId, entry.nodeId)
    root[entry.key] = entry.value
  }

  let output = `${PREAMBLE}\n\n${stringifySyml(root)}`
  output = unquoteMetadataScalar(output, 'version', String(config.lockfileVersion))
  if (cacheKey !== undefined && /^-?(0|[1-9][0-9]*)$/.test(cacheKey)) {
    output = unquoteMetadataScalar(output, 'cacheKey', cacheKey)
  }
  const compressionLevel = sidecar.metadata?.compressionLevel
  if (typeof compressionLevel === 'string' && /^-?(0|[1-9][0-9]*)$/.test(compressionLevel)) {
    output = unquoteMetadataScalar(output, 'compressionLevel', compressionLevel)
  }
  if (options.lineEnding === 'crlf') {
    output = output.replace(/\n/g, '\r\n')
  }

  return { lockfile: output, diagnostics }
}

export function enrichFamily(
  graph: Graph,
  config: YarnBerryFamilyConfig,
  _options: YarnBerryFamilyEnrichOptions = {},
): { graph: Graph; diagnostics: Diagnostic[] } {
  const sidecar = sidecarByGraph.get(graph) ?? EMPTY_SIDECAR
  const rawPeerDependencies = sidecar.peerDependencies ?? new Map<string, Record<string, string>>()
  const derivedPeersByNodeId = new Map<string, DerivedPeer[]>()
  const pendingDiagnostics: PendingDiagnostic[] = []
  let peerChanged = false

  for (const node of graph.nodes()) {
    const rawPeers = rawPeerDependencies.get(node.id)
    if (rawPeers === undefined || node.peerContext.length > 0 || graph.out(node.id, 'peer').length > 0) {
      continue
    }

    const derivedPeers: DerivedPeer[] = []
    for (const [peerName, range] of Object.entries(rawPeers).sort((a, b) => cmpStr(a[0], b[0]))) {
      const normalizedRange = semver.validRange(range)
      if (normalizedRange === null) {
        throw new LockfileError({
          code: 'INVALID_INPUT',
          message: `invalid peer range for ${node.id}: ${peerName}@${range}`,
        })
      }

      const candidates = graph.byName(peerName)
        .filter(candidateId => {
          const candidate = graph.getNode(candidateId)
          return candidate !== undefined
            && semver.valid(candidate.version) !== null
            && semver.satisfies(candidate.version, normalizedRange)
        })
        .slice()
        .sort(cmpStr)

      if (candidates.length === 1) {
        derivedPeers.push({ name: peerName, range, dstOldId: candidates[0]! })
        peerChanged = true
        continue
      }

      if (candidates.length === 0) {
        pendingDiagnostics.push({
          code: `${config.codePrefix}_PEER_UNSATISFIED`,
          severity: 'warning',
          subject: node.id,
          message: `peer "${peerName}" range "${range}" matches no installed version`,
        })
        continue
      }

      pendingDiagnostics.push({
        code: `${config.codePrefix}_PEER_AMBIGUOUS`,
        severity: 'warning',
        subject: node.id,
        peerName,
        candidateIds: candidates,
        message: ambiguousPeerMessage(peerName, candidates),
      })
    }

    if (derivedPeers.length > 0) {
      derivedPeersByNodeId.set(node.id, derivedPeers)
    }
  }

  const workspaceChanged = graphNeedsWorkspaceAttribution(graph)
  if (!peerChanged && !workspaceChanged) {
    return {
      graph,
      diagnostics: pendingDiagnostics.map(diagnostic => finalizePendingDiagnostic(diagnostic, new Map())),
    }
  }

  const finalNodeIds = deriveFinalNodeIds(graph, derivedPeersByNodeId)
  const nextNodes = new Map<string, Node>()
  for (const node of graph.nodes()) {
    const derivedPeers = derivedPeersByNodeId.get(node.id)
    if (derivedPeers === undefined) {
      nextNodes.set(node.id, node)
      continue
    }

    const peerContext = sortPeerContext(derivedPeers.map(peer => finalNodeIds.get(peer.dstOldId) ?? peer.dstOldId))
    const newId = finalNodeIds.get(node.id) ?? node.id
    nextNodes.set(node.id, {
      ...node,
      id: newId,
      peerContext,
    })
  }

  const builder = newBuilder()
  for (const node of graph.nodes()) {
    builder.addNode(nextNodes.get(node.id) ?? node)
  }

  for (const node of graph.nodes()) {
    for (const edge of graph.out(node.id)) {
      const nextSrc = nextNodes.get(edge.src)?.id ?? edge.src
      const nextDst = nextNodes.get(edge.dst)?.id ?? edge.dst
      let nextAttrs = edge.attrs

      if (edge.kind !== 'peer' && edge.attrs?.workspace !== true && isDerivedWorkspaceRange(edge.attrs?.range)) {
        const dstNode = graph.getNode(edge.dst)
        if (dstNode?.workspacePath !== undefined) {
          nextAttrs = { ...edge.attrs, workspace: true }
        }
      }

      builder.addEdge(nextSrc, nextDst, edge.kind, nextAttrs)
    }
  }

  for (const [srcOldId, derivedPeers] of derivedPeersByNodeId) {
    const srcNewId = nextNodes.get(srcOldId)?.id ?? srcOldId
    for (const peer of derivedPeers) {
      const dstNewId = nextNodes.get(peer.dstOldId)?.id ?? peer.dstOldId
      builder.addEdge(srcNewId, dstNewId, 'peer', { range: peer.range })
    }
  }

  for (const node of graph.nodes()) {
    const payload = graph.tarballOf(node.id)
    if (payload === undefined) continue
    builder.setTarball({ name: node.name, version: node.version, patch: node.patch }, payload)
  }
  for (const diagnostic of graph.diagnostics()) {
    builder.diagnostic(diagnostic)
  }
  const layoutHints = graph.layoutHints()
  if (layoutHints !== undefined) {
    builder.layoutHints(layoutHints)
  }

  const nextGraph = builder.seal()
  rememberSidecar(nextGraph, remapSidecar(sidecar, nextNodes, nextGraph))

  return {
    graph: nextGraph,
    diagnostics: pendingDiagnostics.map(diagnostic => finalizePendingDiagnostic(diagnostic, nextNodes)),
  }
}

export function optimizeFamily(
  graph: Graph,
  _options: YarnBerryFamilyOptimizeOptions = {},
): { graph: Graph; diagnostics: Diagnostic[] } {
  const sidecar = sidecarByGraph.get(graph) ?? EMPTY_SIDECAR
  const reachable = new Set(graph.walk(Array.from(graph.roots())))
  const unreachableNodes = Array.from(graph.nodes(), node => node.id)
    .filter(nodeId => !reachable.has(nodeId))
    .sort(cmpStr)

  if (unreachableNodes.length === 0) {
    return {
      graph,
      diagnostics: graph.diagnostics().filter(diagnostic => diagnostic.severity === 'warning'),
    }
  }

  const unreachable = new Set(unreachableNodes)
  const referencedTarballs = new Set<string>()
  const tarballsToRemove = new Map<string, TarballKeyInputs>()
  const internalEdges = unreachableNodes
    .flatMap(src =>
      graph.out(src)
        .filter(edge => unreachable.has(edge.dst))
        .map(edge => ({ src: edge.src, dst: edge.dst, kind: edge.kind })),
    )
    .sort((a, b) =>
      cmpStr(`${a.src}\u0000${a.kind}\u0000${a.dst}`, `${b.src}\u0000${b.kind}\u0000${b.dst}`),
    )

  for (const node of graph.nodes()) {
    const inputs = { name: node.name, version: node.version, patch: node.patch }
    const key = toTarballKey(inputs)
    if (unreachable.has(node.id)) {
      tarballsToRemove.set(key, inputs)
      continue
    }
    referencedTarballs.add(key)
  }

  const result = graph.mutate(m => {
    for (const edge of internalEdges) {
      m.removeEdge(edge.src, edge.dst, edge.kind)
    }
    for (const nodeId of unreachableNodes) {
      m.removeNode(nodeId)
    }
    for (const [key, inputs] of Array.from(tarballsToRemove.entries()).sort((a, b) => cmpStr(a[0], b[0]))) {
      if (!referencedTarballs.has(key)) {
        m.removeTarball(inputs)
      }
    }
  })

  rememberSidecar(result.graph, pruneSidecar(sidecar, result.graph))
  return { graph: result.graph, diagnostics: result.unresolved ?? [] }
}

export function rememberSidecar(graph: Graph, sidecar: YarnBerryFamilySidecar): void {
  if (isEmptySidecar(sidecar)) return
  sidecarByGraph.set(graph, sidecar)
}

export function rawPeerDependenciesBlockOfNode(graph: Graph, nodeId: string): SymlMap | undefined {
  const peerDependencies = sidecarByGraph.get(graph)?.peerDependencies?.get(nodeId)
  return peerDependencies === undefined ? undefined : coerceSymlMap(peerDependencies)
}

export function rawConditionsBlockOfNode(graph: Graph, nodeId: string): SymlMap | undefined {
  const conditions = sidecarByGraph.get(graph)?.conditions?.get(nodeId)
  return conditions === undefined ? undefined : coerceSymlMap(conditions)
}

function parseSpec(raw: string): SpecPart {
  const startFrom = raw[0] === '@' ? 1 : 0
  let sepIdx = -1
  for (let i = startFrom; i < raw.length; i++) {
    if (raw[i] === '@') { sepIdx = i; break }
  }
  if (sepIdx <= 0) {
    throw new LockfileError({
      code: 'PARSE_FAILED',
      message: `bad entry-spec, no protocol separator: ${raw}`,
    })
  }
  const name = raw.slice(0, sepIdx)
  const rest = raw.slice(sepIdx + 1)
  const colon = rest.indexOf(':')
  if (colon < 0) {
    throw new LockfileError({
      code: 'PARSE_FAILED',
      message: `bad entry-spec, no protocol colon: ${raw}`,
    })
  }
  return { name, protocol: rest.slice(0, colon), spec: rest.slice(colon + 1) }
}

function parseEntryKey(key: string): SpecPart[] {
  return key.split(', ').map(spec => parseSpec(spec.trim()))
}

function workspacePathOf(spec: string): string {
  if (spec === '.') return ''
  if (spec.startsWith('./')) return spec.slice(2)
  return spec
}

function asMap(value: SymlValue | undefined): SymlMap | undefined {
  return value && typeof value === 'object' ? value : undefined
}

function asString(value: SymlValue | undefined): string | undefined {
  return typeof value === 'string' ? value : undefined
}

function validateMetadata(ast: SymlMap, config: YarnBerryFamilyConfig): SymlMap | undefined {
  const meta = asMap(ast['__metadata'])
  if (!meta) {
    throw new LockfileError({
      code: 'FORMAT_MISMATCH',
      message: 'missing __metadata block',
    })
  }
  if (asString(meta['version']) !== String(config.lockfileVersion)) {
    throw new LockfileError({
      code: 'FORMAT_MISMATCH',
      message: `expected __metadata.version: ${config.lockfileVersion}, got ${JSON.stringify(meta['version'])}`,
    })
  }

  const extras: SymlMap = {}
  for (const [key, value] of Object.entries(meta)) {
    if (key === 'version') continue
    const cloned = cloneSymlValue(value)
    if (cloned !== undefined) {
      extras[key] = cloned
    }
  }
  return Object.keys(extras).length > 0 ? extras : undefined
}

function entryKeyOfNode(graph: Graph, node: Node): string {
  const primary = primarySpecOfNode(node)
  const specs = new Set<string>([primary])

  for (const edge of graph.in(node.id)) {
    if (edge.kind === 'peer') continue
    if (edge.attrs?.range !== undefined) {
      specs.add(`${node.name}@${edge.attrs.range}`)
    }
  }

  const rest = Array.from(specs).filter(spec => spec !== primary).sort(cmpStr)
  return [primary, ...rest].join(', ')
}

function primarySpecOfNode(node: Node): string {
  if (node.workspacePath !== undefined) {
    return `${node.name}@workspace:${node.workspacePath === '' ? '.' : node.workspacePath}`
  }

  const exact = exactSpecOfResolution(node)
  return exact ?? `${node.name}@npm:${node.version}`
}

function exactSpecOfResolution(node: Node): string | undefined {
  if (node.resolution === undefined) return undefined
  if (node.resolution.startsWith(`${node.name}@patch:`)) {
    const locator = patchLocatorOfResolution(node.resolution)
    if (locator === undefined) return undefined
    return baseSpecOfPatchLocator(locator)
  }
  return node.resolution.startsWith(`${node.name}@`) ? node.resolution : undefined
}

function baseSpecOfPatchLocator(locator: string): string | undefined {
  if (!locator.startsWith('patch:')) return undefined
  const hashIdx = locator.indexOf('#')
  const encoded = hashIdx >= 0
    ? locator.slice('patch:'.length, hashIdx)
    : locator.slice('patch:'.length)
  try {
    return decodeURIComponent(encoded)
  } catch {
    return undefined
  }
}

function entryOfNode(
  graph: Graph,
  node: Node,
  config: YarnBerryFamilyConfig,
  emitDiagnostic: (diagnostic: Diagnostic) => void,
): SymlMap {
  const payload = graph.tarballOf(node.id)
  const entry: SymlMap = {
    version: node.version,
    resolution: resolutionOfNode(node),
  }

  // yarn-berry's on-disk format has a single `dependencies:` block per entry —
  // no separate `devDependencies` block. ADR-0019 §C derives `dev` edges at the
  // workspace root from manifests; merge them with `dep` on emit so the
  // classification survives stringify (parse-side will collapse back to `dep`
  // per §C's "no on-lockfile signal" table).
  const dependencies = edgeBlockOfKinds(graph, node, ['dep', 'dev'], config)
  if (dependencies !== undefined) entry['dependencies'] = dependencies

  const optionalDependencies = edgeBlockOfKinds(graph, node, ['optional'], config)
  if (optionalDependencies !== undefined) entry['optionalDependencies'] = optionalDependencies

  const peerDependencies = extraBlockOfNode(node, 'peerDependencies')
    ?? rawPeerDependenciesBlockOfNode(graph, node.id)
    ?? edgeBlockOfKinds(graph, node, ['peer'], config, { skipMissingRange: true })
  if (peerDependencies !== undefined) entry['peerDependencies'] = peerDependencies

  const peerDependenciesMeta = extraBlockOfNode(node, 'peerDependenciesMeta')
  if (peerDependenciesMeta !== undefined) entry['peerDependenciesMeta'] = peerDependenciesMeta

  const dependenciesMeta = extraBlockOfNode(node, 'dependenciesMeta')
  if (dependenciesMeta !== undefined) entry['dependenciesMeta'] = dependenciesMeta

  const bin = binBlockOfNode(node, payload)
  if (bin !== undefined) entry['bin'] = bin

  entry['linkType'] = node.workspacePath !== undefined ? 'soft' : 'hard'
  entry['languageName'] = node.workspacePath !== undefined ? 'unknown' : 'node'

  const conditions = rawConditionsBlockOfNode(graph, node.id) ?? extraBlockOfNode(node, 'conditions')
  if (conditions !== undefined) {
    if (config.conditionsAllowed) {
      entry['conditions'] = conditions
    } else {
      emitDiagnostic({
        code: `${config.codePrefix}_CONDITIONS_DROPPED`,
        subject: node.id,
        severity: 'warning',
        message: `conditions block is unsupported in yarn-berry-v${config.lockfileVersion}; dropping on emit`,
      })
    }
  }

  const checksum = checksumOfPayload(payload, config)
  if (checksum !== undefined) entry['checksum'] = checksum
  if (node.peerContext.length > 0) {
    emitDiagnostic({
      code: `${config.codePrefix}_PEER_VIRT_FLATTENED`,
      subject: node.id,
      severity: 'warning',
      message: `peerContext ${JSON.stringify(node.peerContext)} flattens to ${entry.resolution}`,
    })
  }

  return entry
}

function resolutionOfNode(node: Node): string {
  if (node.patch?.startsWith('unresolved-')) {
    if (node.resolution === undefined || patchLocatorOfResolution(node.resolution) === undefined) {
      throw new LockfileError({
        code: 'MISSING_REQUIRED_FIELD',
        message: `sentinel patch node ${node.id} requires an original patch resolution to emit`,
      })
    }
    return node.resolution
  }

  if (node.resolution !== undefined) return node.resolution
  if (node.workspacePath !== undefined) {
    return `${node.name}@workspace:${node.workspacePath === '' ? '.' : node.workspacePath}`
  }
  return `${node.name}@npm:${node.version}`
}

function edgeBlockOfKinds(
  graph: Graph,
  node: Node,
  kinds: readonly EdgeKind[],
  config: YarnBerryFamilyConfig,
  options: { skipMissingRange?: boolean } = {},
): SymlMap | undefined {
  const edges = kinds.flatMap(kind => graph.out(node.id, kind))
  if (edges.length === 0) return undefined

  const blockEntries: Array<[string, string]> = []
  const seen = new Set<string>()

  for (const edge of edges) {
    const dst = graph.getNode(edge.dst)
    if (dst === undefined) {
      throw new LockfileError({
        code: 'INVARIANT_VIOLATION',
        message: `edge from ${node.id} points to missing node ${edge.dst}`,
      })
    }
    if (edge.attrs?.range === undefined) {
      if (options.skipMissingRange) {
        continue
      }
      throw new LockfileError({
        code: 'MISSING_REQUIRED_FIELD',
        message: `edge ${node.id} -> ${edge.dst} (${edge.kind}) requires attrs.range for emit`,
      })
    }

    const depName = dst.name
    if (seen.has(depName)) {
      throw new LockfileError({
        code: 'INVARIANT_VIOLATION',
        message: `cannot emit duplicate ${edge.kind} dependency key ${depName} from ${node.id}`,
      })
    }
    seen.add(depName)
    blockEntries.push([depName, emittedRangeOfEdge(edge.kind, edge.attrs.range, config)])
  }

  if (blockEntries.length === 0) return undefined
  blockEntries.sort((a, b) => cmpStr(a[0]!, b[0]!))

  const block: SymlMap = {}
  for (const [name, range] of blockEntries) {
    block[name] = range
  }
  return block
}

function emittedRangeOfEdge(kind: EdgeKind, range: string, config: YarnBerryFamilyConfig): string {
  if (kind === 'peer') return range
  if (config.rangeEmit !== 'bare') return range
  return range.startsWith('npm:') ? range.slice('npm:'.length) : range
}

function checksumOfPayload(payload: TarballPayload | undefined, config: YarnBerryFamilyConfig): string | undefined {
  const integrity = payload?.integrity
  if (integrity === undefined) return undefined

  if (config.checksumPrefix) {
    return integrity
  }

  const slashIdx = integrity.indexOf('/')
  return slashIdx >= 0 ? integrity.slice(slashIdx + 1) : integrity
}

function extraBlockOfNode(node: Node, field: string): SymlMap | undefined {
  return coerceSymlMap((node as unknown as Record<string, unknown>)[field])
}

function coerceSymlMap(value: unknown): SymlMap | undefined {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return undefined

  const raw = value as Record<string, unknown>
  const block: SymlMap = {}
  for (const key of Object.keys(raw).sort(cmpStr)) {
    const coerced = coerceSymlValue(raw[key])
    if (coerced !== undefined) {
      block[key] = coerced
    }
  }

  return Object.keys(block).length > 0 ? block : undefined
}

function coerceSymlValue(value: unknown): SymlValue | undefined {
  if (typeof value === 'string') return value
  if (typeof value === 'number' || typeof value === 'boolean') return String(value)
  return coerceSymlMap(value)
}

function cloneSymlValue(value: SymlValue | undefined): SymlValue | undefined {
  if (typeof value === 'string') return value
  if (value === undefined) return undefined
  return coerceSymlMap(value)
}

function binBlockOfNode(node: Node, payload: TarballPayload | undefined): SymlMap | undefined {
  if (payload?.bin === undefined) return undefined
  if (typeof payload.bin === 'string') {
    return { [node.name]: payload.bin }
  }

  const block: SymlMap = {}
  for (const name of Object.keys(payload.bin).sort(cmpStr)) {
    const target = payload.bin[name]
    if (target !== undefined) block[name] = target
  }
  return Object.keys(block).length > 0 ? block : undefined
}

function extractPatchFingerprint(
  nodeId: string,
  resolution: string,
  workspaceRoot: string | undefined,
): { patch: string; diagnostic?: Diagnostic } | undefined {
  const locator = patchLocatorOfResolution(resolution)
  if (locator === undefined) return undefined

  const source = patchSourceOfLocator(locator)
  if (source === undefined) {
    return unresolvedPatch(nodeId, locator, 'patch locator has no source fragment')
  }

  if (source.startsWith('~builtin<')) {
    const yarnMajor = yarnMajorOfBuiltinPatch(resolution)
    if (yarnMajor === undefined) {
      return unresolvedPatch(nodeId, locator, 'builtin patch yarn-major is unavailable at parse time')
    }
    return { patch: sha512Hex(`${yarnMajor}:${source}`) }
  }

  if (workspaceRoot === undefined) {
    return unresolvedPatch(nodeId, locator, 'workspaceRoot is unavailable at parse time')
  }

  const bytes = readWorkspaceFileBytes(workspaceRoot, source, locator)
  if (bytes === undefined) {
    return unresolvedPatch(nodeId, locator, 'patch file is unavailable at parse time')
  }

  return { patch: sha512Hex(bytes) }
}

function patchLocatorOfResolution(resolution: string): string | undefined {
  if (resolution.startsWith('patch:')) return resolution
  const idx = resolution.indexOf('@patch:')
  return idx >= 0 ? resolution.slice(idx + 1) : undefined
}

function patchSourceOfLocator(locator: string): string | undefined {
  const hashIdx = locator.indexOf('#')
  if (hashIdx < 0) return undefined
  const paramsIdx = locator.indexOf('::', hashIdx + 1)
  const source = paramsIdx < 0
    ? locator.slice(hashIdx + 1)
    : locator.slice(hashIdx + 1, paramsIdx)
  return isDegeneratePatchSource(source) ? undefined : source
}

function isDegeneratePatchSource(source: string): boolean {
  let decoded: string
  try {
    decoded = decodeURIComponent(source)
  } catch {
    return false
  }

  const trimmed = decoded.trim()
  if (trimmed === '') return true
  if (path.posix.isAbsolute(trimmed)) return false

  const segments = path.posix.normalize(trimmed).split('/').filter(segment => segment !== '' && segment !== '.')
  return segments.length === 0
}

function yarnMajorOfBuiltinPatch(_resolution: string): string | undefined {
  return undefined
}

function unresolvedPatch(nodeId: string, locator: string, reason: string): { patch: string; diagnostic: Diagnostic } {
  return {
    patch: `unresolved-${sha256Hex(locator)}`,
    diagnostic: {
      code: 'YARN_BERRY_PATCH_UNRESOLVED',
      subject: nodeId,
      severity: 'warning',
      message: `${reason}; using sentinel for ${locator}`,
    },
  }
}

function sha512Hex(value: string | Uint8Array): string {
  return createHash('sha512').update(value).digest('hex')
}

function sha256Hex(value: string): string {
  return createHash('sha256').update(value, 'utf8').digest('hex')
}

function stringRecordOfBlock(block: SymlMap | undefined): Record<string, string> | undefined {
  if (!block) return undefined

  const out: Record<string, string> = {}
  for (const [key, value] of Object.entries(block)) {
    if (typeof value === 'string') out[key] = value
  }
  return Object.keys(out).length > 0 ? out : undefined
}

function sortPeerContext(peers: readonly string[]): string[] {
  return peers.slice().sort((a, b) => {
    const nameCmp = cmpStr(nameOf(a), nameOf(b))
    return nameCmp !== 0 ? nameCmp : cmpStr(a, b)
  })
}

function deriveFinalNodeIds(graph: Graph, derivedPeersByNodeId: Map<string, DerivedPeer[]>): Map<string, string> {
  const finalIds = new Map<string, string>()
  const nodes = Array.from(graph.nodes())
  for (const node of nodes) {
    finalIds.set(node.id, node.id)
  }

  for (let i = 0; i < nodes.length; i++) {
    let changed = false
    for (const node of nodes) {
      const derivedPeers = derivedPeersByNodeId.get(node.id)
      if (derivedPeers === undefined) continue

      const peerContext = sortPeerContext(derivedPeers.map(peer => finalIds.get(peer.dstOldId) ?? peer.dstOldId))
      const nextId = serializeNodeId(node.name, node.version, peerContext)
      if (finalIds.get(node.id) !== nextId) {
        finalIds.set(node.id, nextId)
        changed = true
      }
    }
    if (!changed) return finalIds
  }

  throw new LockfileError({
    code: 'INVARIANT_VIOLATION',
    message: 'peer enrichment did not converge',
  })
}

function isDerivedWorkspaceRange(range: string | undefined): boolean {
  return typeof range === 'string' && range.startsWith('workspace:')
}

function ambiguousPeerMessage(peerName: string, candidates: readonly string[]): string {
  return `peer "${peerName}" matches multiple installed versions: [${candidates.join(', ')}]`
}

function finalizePendingDiagnostic(diagnostic: PendingDiagnostic, nextNodes: Map<string, Node>): Diagnostic {
  const subject = nextNodes.get(diagnostic.subject)?.id ?? diagnostic.subject
  const message = diagnostic.code.endsWith('_PEER_AMBIGUOUS')
    && diagnostic.peerName !== undefined
    && diagnostic.candidateIds !== undefined
    ? ambiguousPeerMessage(
      diagnostic.peerName,
      diagnostic.candidateIds.map(candidateId => nextNodes.get(candidateId)?.id ?? candidateId),
    )
    : diagnostic.message

  return {
    code: diagnostic.code,
    severity: diagnostic.severity,
    subject,
    message,
  }
}

function graphNeedsWorkspaceAttribution(graph: Graph): boolean {
  for (const node of graph.nodes()) {
    for (const edge of graph.out(node.id)) {
      if (edge.kind === 'peer') continue
      if (edge.attrs?.workspace === true) continue
      if (!isDerivedWorkspaceRange(edge.attrs?.range)) continue
      if (graph.getNode(edge.dst)?.workspacePath !== undefined) return true
    }
  }
  return false
}

function addEdgesFromBlock(
  builder: ReturnType<typeof newBuilder>,
  srcId: string,
  block: SymlMap | undefined,
  kind: EdgeKind,
  index: Map<string, string>,
  diagnostics: Diagnostic[],
): void {
  if (!block) return
  for (const [depName, depRange] of Object.entries(block)) {
    if (typeof depRange !== 'string') continue
    const normalizedRange = normalizedEdgeRange(kind, depRange)
    const lookup = `${depName}@${normalizedRange}`
    const dstId = index.get(lookup)
    if (!dstId) {
      diagnostics.push({
        code: 'YARN_BERRY_UNRESOLVED_DEP',
        subject: srcId,
        severity: 'warning',
        message: `dependency ${depName}=${depRange} from ${srcId} has no matching lockfile entry`,
      })
      continue
    }
    builder.addEdge(srcId, dstId, kind, { range: normalizedRange })
  }
}

function normalizedEdgeRange(kind: EdgeKind, range: string): string {
  if (kind === 'peer') return range
  return hasExplicitProtocol(range) ? range : `npm:${range}`
}

function hasExplicitProtocol(range: string): boolean {
  const colonIdx = range.indexOf(':')
  if (colonIdx <= 0) return false
  const prefix = range.slice(0, colonIdx)
  return /^[a-z][a-z0-9+.-]*$/i.test(prefix)
}

function remapSidecar(
  sidecar: YarnBerryFamilySidecar,
  nextNodes: Map<string, Node>,
  nextGraph: Graph,
): YarnBerryFamilySidecar {
  const remapped: YarnBerryFamilySidecar = {}

  if (sidecar.peerDependencies !== undefined) {
    const nextPeerDependencies = new Map<string, Record<string, string>>()
    for (const [oldId, block] of sidecar.peerDependencies) {
      nextPeerDependencies.set(nextNodes.get(oldId)?.id ?? oldId, block)
    }
    if (nextPeerDependencies.size > 0) remapped.peerDependencies = nextPeerDependencies
  }

  if (sidecar.conditions !== undefined) {
    const nextConditions = new Map<string, SymlMap>()
    for (const [oldId, block] of sidecar.conditions) {
      const nextId = nextNodes.get(oldId)?.id ?? oldId
      if (nextGraph.getNode(nextId) !== undefined) {
        nextConditions.set(nextId, block)
      }
    }
    if (nextConditions.size > 0) remapped.conditions = nextConditions
  }

  if (sidecar.metadata !== undefined) {
    remapped.metadata = sidecar.metadata
  }

  return remapped
}

function pruneSidecar(sidecar: YarnBerryFamilySidecar, nextGraph: Graph): YarnBerryFamilySidecar {
  const pruned: YarnBerryFamilySidecar = {}

  if (sidecar.peerDependencies !== undefined) {
    const nextPeerDependencies = new Map<string, Record<string, string>>()
    for (const [nodeId, block] of sidecar.peerDependencies) {
      if (nextGraph.getNode(nodeId) !== undefined) {
        nextPeerDependencies.set(nodeId, block)
      }
    }
    if (nextPeerDependencies.size > 0) pruned.peerDependencies = nextPeerDependencies
  }

  if (sidecar.conditions !== undefined) {
    const nextConditions = new Map<string, SymlMap>()
    for (const [nodeId, block] of sidecar.conditions) {
      if (nextGraph.getNode(nodeId) !== undefined) {
        nextConditions.set(nodeId, block)
      }
    }
    if (nextConditions.size > 0) pruned.conditions = nextConditions
  }

  if (sidecar.metadata !== undefined) {
    pruned.metadata = sidecar.metadata
  }

  return pruned
}

function isEmptySidecar(sidecar: YarnBerryFamilySidecar): boolean {
  return sidecar.peerDependencies === undefined
    && sidecar.conditions === undefined
    && sidecar.metadata === undefined
}

function unquoteMetadataScalar(output: string, key: string, value: string): string {
  const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const escapedValue = value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return output.replace(new RegExp(`^(  ${escapedKey}): "${escapedValue}"$`, 'm'), `$1: ${value}`)
}
