import {
  GraphError,
  newBuilder,
  nameOf,
  toTarballKey,
  type Diagnostic,
  type Edge,
  type EdgeAttrs,
  type Graph,
  type Node,
  type OverrideConstraint,
  type TarballKeyInputs,
} from '../graph.ts'
import { LockfileError } from '../errors.ts'
import { parseSri, emitSri, isEmptyIntegrity, type Integrity } from '../recipe/integrity.ts'
import {
  ambiguousResolutionDiagnostic,
  emitDropped as patchEmitDropped,
  emitWorkspaceResolved,
  emitWorkspaceUnresolved,
  invalidIntegrityDiagnostic,
  resolutionPinUnresolvedDiagnostic,
  unknownResolutionDiagnostic,
} from '../recipe/diagnostics.ts'
import { distTagResolve, overrideTargetFor, semverResolve, type SemverCandidate } from '../recipe/descriptor-resolve.ts'
import {
  parse as parseResolutionRecipe,
  stringifyForYarnClassic,
} from '../recipe/resolution.ts'
import {
  isWorkspaceEdge,
  shouldEmitWorkspaceResolved,
  stringifyForVersionOnly,
  workspaceRangeOfEdge,
} from '../recipe/workspace.ts'

const HEADER =
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n' +
  '# yarn lockfile v1\n\n\n'
const HEADER_LINE_1 = '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.'
const HEADER_LINE_2 = '# yarn lockfile v1'
const cmpUtf16 = (a: string, b: string): number => a < b ? -1 : a > b ? 1 : 0

// A dependency pair `<name> <value>` where each side is a quoted string OR a
// bare whitespace-free token. Yarn 1 emits bare ranges/tags/`v`-prefixed
// versions (`latest`, `v0.5.0`, `^1.0.0`) unquoted — the value side must accept
// them, not only quoted strings.
const DEP_PAIR_RE = /^("(?:\\.|[^"])*"|[^\s"]\S*) ("(?:\\.|[^"])*"|[^\s"]\S*)$/
const BARE_DEP_NAME_RE = /^[A-Za-z0-9._-]+$/
const ENTRY_KEY_SPECIAL_RE = /[\s:",#?*&!|>'`[\]{}]/
const BERRY_HEADER_RE = /^__metadata:\s*(?:\r?\n|$)/m

interface YarnClassicSidecar {
  entrySpecs: Map<string, string[]>
  /** Per-NodeId verbatim unknown entry-field lines (see YarnClassicEntry.extras),
   *  for round-trip re-emit. */
  entryExtras?: Map<string, string[]>
}

interface YarnClassicEntry {
  key: string
  version?: string
  resolved?: string
  integrity?: string
  /** Unknown scalar entry fields captured VERBATIM (sans the 2-space indent) —
   *  e.g. yarn-1's legacy `uid ""` on link:/file: entries. Tolerated +
   *  round-tripped rather than rejected (forward-compat for unmodelled fields). */
  extras?: string[]
  dependencies: Map<string, string>
  optionalDependencies: Map<string, string>
}

export interface YarnClassicParseOptions {
  // Bug #99 — canonical override constraints (ADR-0025), threaded from the
  // public `parse()` after F6-capturing `ParseOptions.manifests`. yarn-classic
  // joins consumer ranges to entries by exact `<name>@<range>` key; a
  // `resolutions` pin rewrites that key, so the override map bridges the miss.
  // Absent → Rung-3 semver only. Classic locks carry no resolved-version entries
  // (it is range-keyed like berry), so the same ladder applies.
  overrides?: OverrideConstraint[]
}

export interface YarnClassicStringifyOptions {
  lineEnding?: 'lf' | 'crlf'
  onDiagnostic?: (diagnostic: Diagnostic) => void
}

export interface YarnClassicManifest {
  name?: string
  version?: string
  dependencies?: Record<string, string>
  devDependencies?: Record<string, string>
  optionalDependencies?: Record<string, string>
}

export interface YarnClassicEnrichOptions {
  manifests?: Record<string, YarnClassicManifest>
}

export interface YarnClassicOptimizeOptions {}

const sidecarByGraph = new WeakMap<Graph, YarnClassicSidecar>()

// Mined from legacy/main/ts/formats/yarn-classic.ts:30, but tightened to the
// exact §A header shape rather than a loose substring probe.
function stripBom(input: string): string {
  return input.charCodeAt(0) === 0xfeff ? input.slice(1) : input
}

export function check(input: string): boolean {
  const normalized = stripBom(normalizeLineEndings(input))
  // Full header (a populated lockfile carries the trailing blank lines) OR the
  // two comment lines alone (a fresh-init empty v1 lockfile has no entries → no
  // trailing blanks). BOM-tolerant — fixes the detect asymmetry vs berry.
  if (normalized.startsWith(HEADER)) return true
  const lines = normalized.split('\n')
  if (lines[0] === HEADER_LINE_1 && lines[1] === HEADER_LINE_2) return true
  // D1 (#94) — structural fallback. The two header comment lines can be absent
  // or displaced (a tool prepends its own comment; a `#`-stripper removes them),
  // leaving a headerless body that detect() would otherwise miss. Recognise the
  // classic entry-block SHAPE itself — a col-0 `<name>@<range>:` descriptor
  // immediately followed by `  version "<x>"` — which no other lockfile family
  // emits, so the npm/pnpm/bun garbage-rejection boundary (#83) stays intact.
  return hasClassicStructuralBody(normalized, lines)
}

// D1 (#94) — does the body carry the unmistakable yarn-classic entry-block
// shape, independent of the header comments? The signature is a col-0 entry-key
// line that parses as a `<name>@<range>` descriptor and ends with `:`, FOLLOWED
// (after any inner `#` comment / blank lines) by a 2-space-indented bare
// `version "<x>"` field — `version` un-quoted, value quoted, NO `:` after the
// key. That last detail is the discriminant:
//   - npm / bun are JSON (`{ "version": "…" }`) — never a col-0 `name@range:`;
//   - pnpm / yarn-berry are SYML/YAML (`version: …` WITH a colon, value bare) —
//     never the bare-key + quoted-value `version "…"` form;
//   - a `yarn-error.log` `Lockfile:` dump re-indents the whole lock by 2 spaces,
//     so its entry keys sit at `  <name>@range:` (indented) and never at col 0.
// A yarn-berry `__metadata:` head is excluded up front for a fast, unambiguous bail.
function hasClassicStructuralBody(normalized: string, lines: string[]): boolean {
  if (BERRY_HEADER_RE.test(normalized)) return false
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] ?? ''
    // A col-0 entry-key line: no leading whitespace, ends with ':', and is not a
    // comment/blank. Must parse as a `<name>@<range>` descriptor list.
    if (line.length === 0 || line[0] === ' ' || line[0] === '\t' || line[0] === '#') continue
    if (!line.endsWith(':')) continue
    if (!isClassicEntryKeyLine(line.slice(0, -1))) continue
    // The first non-comment, non-blank body line must be `  version "<x>"`.
    for (let j = i + 1; j < lines.length; j++) {
      const body = lines[j] ?? ''
      if (body.length === 0) return false       // blank before any body → not an entry
      if (body.startsWith('  #')) continue       // tolerate an inner comment
      return CLASSIC_VERSION_FIELD_RE.test(body)
    }
    return false
  }
  return false
}

// `  version "<x>"` — exactly two spaces, bare `version` key, a space, then a
// double-quoted value, to EOL. The quoted value + absence of a `:` after the key
// is what separates yarn-classic from every YAML/JSON sibling.
const CLASSIC_VERSION_FIELD_RE = /^ {2}version "(?:\\.|[^"])*"\s*$/

// Is `key` a yarn-classic entry-key descriptor list — one or more comma-joined
// `<name>@<range>` specs (quoted or bare)? Reuses the parse-side splitter +
// per-spec `@<range>` check, so the detector and the parser agree on the grammar
// (no separate, drifting regex). A bare package name with no `@<range>` (the #83
// malformed shape) does NOT qualify — the structural fallback must not adopt a
// non-lockfile.
function isClassicEntryKeyLine(key: string): boolean {
  let specs: string[]
  try {
    specs = splitEntryKey(parseEntryKeyToken(key))
  } catch {
    return false
  }
  if (specs.length === 0) return false
  for (const spec of specs) {
    const idx = spec.indexOf('@', spec.startsWith('@') ? 1 : 0)
    if (idx <= 0 || idx === spec.length - 1) return false
  }
  return true
}

export function parse(input: string, options: YarnClassicParseOptions = {}): Graph {
  const normalized = stripBom(normalizeLineEndings(input))
  ensureClassicHeader(normalized)

  const builder = newBuilder()
  const diagnostics: Diagnostic[] = []
  const entries = parseEntries(normalized)
  const specIndex = new Map<string, string>()
  const sidecar = new Map<string, string[]>()
  const entryExtras = new Map<string, string[]>()
  const unknownFields = new Set<string>()
  const entryNodes: Array<{ node: Node; entry: YarnClassicEntry }> = []
  const seenEntries = new Map<string, { resolved?: string; integrity?: string }>()
  // Bug #99 Rung-3 — name → registry-class candidate index for source-gated
  // max-satisfying semver, built alongside the node table (the resolver runs
  // against the write-only builder). Source class comes from the F3 canonical
  // resolution; only `tarball` candidates are eligible for an `npm:`/bare match.
  const semverCandidatesByName = new Map<string, SemverCandidate[]>()

  for (const entry of entries) {
    const specs = splitEntryKey(entry.key)
    if (specs.length === 0) {
      throw parseFailed(`entry ${JSON.stringify(entry.key)} has empty spec list`)
    }
    if (entry.version === undefined) {
      throw parseFailed(`entry ${JSON.stringify(entry.key)} missing version`)
    }

    // F6 (#93) — group entry-key descriptors by their RESOLVED package name
    // (the `npm:`-alias target, else the descriptor's own name), collecting the
    // verbatim descriptor keys. An npm-aliased descriptor
    // (`<alias>@npm:<target>@<range>`) thus joins the SAME group as a plain
    // `<target>@<range>` descriptor — one node, keyed by the target — instead of
    // splitting off a duplicate `<alias>@<version>` node.
    const specsByResolvedName = new Map<string, string[]>()
    for (const spec of specs) {
      const identity = specIdentity(parseSpec(spec))
      const current = specsByResolvedName.get(identity.resolvedName)
      if (current === undefined) specsByResolvedName.set(identity.resolvedName, [identity.descriptorKey])
      else current.push(identity.descriptorKey)
    }

    for (const [name, rawDescriptors] of specsByResolvedName) {
      const descriptors = Array.from(new Set(rawDescriptors)).sort(cmpUtf16)
      const id = `${name}@${entry.version}`
      const prior = seenEntries.get(id)
      if (prior !== undefined) {
        // Two separate entry blocks resolve to the same name@version. Merge
        // their descriptor keys onto the one node when the resolution +
        // integrity agree (the comma-joined `a@^1, a@^2:` form already merges
        // this way); only a genuine conflict — differing `resolved` or
        // `integrity` — is an irreducible loss.
        if (prior.resolved !== entry.resolved || prior.integrity !== entry.integrity) {
          throw new LockfileError({
            code: 'IRREDUCIBLE_LOSS',
            message: `two entries collapse onto NodeId ${id} with differing resolution`,
          })
        }
        const merged = sidecar.get(id) ?? []
        for (const spec of descriptors) {
          if (!merged.includes(spec)) merged.push(spec)
          specIndex.set(spec, id)
        }
        sidecar.set(id, merged)
        continue
      }
      seenEntries.set(id, { resolved: entry.resolved, integrity: entry.integrity })

      const node: Node = {
        id,
        name,
        version: entry.version,
        peerContext: [],
      }
      if (entry.resolved !== undefined) {
        node.resolution = parseResolution(entry.resolved)
      }
      builder.addNode(node)

      // ADR-0014 §4.F3 — canonical resolution into TarballPayload.
      // Workspace canonical (yarn-classic sentinel-version entries) lives on
      // Node.workspacePath via enrich; not on TarballPayload.
      const canonicalResolution = entry.resolved !== undefined
        ? canonicalResolutionOfResolved(entry.resolved)
        : undefined
      if (canonicalResolution !== undefined && canonicalResolution.type === 'unknown') {
        diagnostics.push(unknownResolutionDiagnostic(id, entry.resolved!))
      }

      // Bug #99 Rung-3 — register as a max-satisfying-semver candidate under its
      // name. `'absent'` source (no `resolved:`) is non-registry → ineligible for
      // an `npm:`/bare match inside `semverResolve`.
      const candidate: SemverCandidate = {
        id,
        version: entry.version,
        sourceType: canonicalResolution?.type ?? 'absent',
      }
      const candidateList = semverCandidatesByName.get(name)
      if (candidateList === undefined) semverCandidatesByName.set(name, [candidate])
      else candidateList.push(candidate)

      if (entry.integrity !== undefined) {
        const integrity = parseSri(entry.integrity, 'sri')
        if (isEmptyIntegrity(integrity)) {
          diagnostics.push(invalidIntegrityDiagnostic('YARN_CLASSIC', id, entry.integrity))
        } else {
          const payload: { integrity: Integrity; resolution?: typeof canonicalResolution } = { integrity }
          if (canonicalResolution !== undefined) payload.resolution = canonicalResolution
          builder.setTarball({ name, version: entry.version }, payload)
        }
      } else if (canonicalResolution !== undefined) {
        builder.setTarball({ name, version: entry.version }, { resolution: canonicalResolution })
      }

      sidecar.set(id, descriptors.slice())
      if (entry.extras !== undefined && entry.extras.length > 0) {
        entryExtras.set(id, entry.extras)
        for (const raw of entry.extras) unknownFields.add(raw.split(' ', 1)[0] ?? raw)
      }
      entryNodes.push({ node, entry })
      for (const spec of descriptors) {
        specIndex.set(spec, id)
      }
    }
  }

  if (unknownFields.size > 0) {
    diagnostics.push({
      code: 'YARN_CLASSIC_UNKNOWN_FIELD',
      severity: 'info',
      subject: 'yarn-classic',
      message: `preserved unmodelled yarn-classic entry field(s) verbatim for round-trip: ${Array.from(unknownFields).sort(cmpUtf16).join(', ')}`,
    })
  }

  // Bug #99 — the descriptor→node ladder's Rung-2/3 inputs (shared shape with
  // the berry resolver). Bundled once so the steady-state Rung-0 path is a
  // single `specIndex.get`.
  const ladder: ClassicEdgeLadderContext = {
    candidatesByName:  semverCandidatesByName,
    overrides:         options.overrides ?? [],
    manifestsProvided: options.overrides !== undefined,
  }
  for (const { node, entry } of entryNodes) {
    addEdgesFromMap(builder, diagnostics, node.id, entry.dependencies, 'dep', specIndex, ladder)
    addEdgesFromMap(builder, diagnostics, node.id, entry.optionalDependencies, 'optional', specIndex, ladder)
  }

  for (const diagnostic of diagnostics) {
    builder.diagnostic(diagnostic)
  }

  try {
    const graph = builder.seal()
    rememberSidecar(graph, { entrySpecs: sidecar, entryExtras })
    return graph
  } catch (error) {
    if (error instanceof GraphError) {
      throw new LockfileError({
        code: 'PARSE_FAILED',
        message: `seal failed: ${error.message}`,
      })
    }
    throw error
  }
}

export function stringify(graph: Graph, options: YarnClassicStringifyOptions = {}): string {
  const warnedPeerEdges = new Set<string>()
  const warnedPeerContexts = new Set<string>()
  const warnedPatches = new Set<string>()
  const emitDiagnostic = (diagnostic: Diagnostic): void => {
    options.onDiagnostic?.(diagnostic)
  }

  // yarn-classic identifies entries by `<name>@<version>` (no patch
  // disambiguator); patched and unpatched siblings of the same
  // `<name>@<version>` collapse onto a single entry on reparse and trip
  // `IRREDUCIBLE_LOSS`. Emit only the cleaner sibling (prefer the unpatched
  // node) and the discarded patch is attributed by `warnPatchDrop` /
  // `RECIPE_FEATURE_DROPPED`. Order preserves stability of the entry-key
  // sorting downstream.
  const sortedNodes = Array.from(graph.nodes()).sort((a, b) =>
    cmpUtf16(a.id, b.id)
      || ((a.patch === undefined ? 0 : 1) - (b.patch === undefined ? 0 : 1)),
  )
  const emittedNameVersion = new Set<string>()
  const dedupedNodes: Node[] = []
  for (const node of sortedNodes) {
    if (node.workspacePath !== undefined) {
      dedupedNodes.push(node)
      continue
    }
    const nameVersion = `${node.name}@${node.version}`
    if (emittedNameVersion.has(nameVersion)) {
      warnPatchDrop(node, warnedPatches, emitDiagnostic)
      continue
    }
    emittedNameVersion.add(nameVersion)
    dedupedNodes.push(node)
  }

  const emitSidecar = sidecarByGraph.get(graph)
  const entries = dedupedNodes.map(node => {
    warnPatchDrop(node, warnedPatches, emitDiagnostic)
    warnPeerContextFlatten(node, warnedPeerContexts, emitDiagnostic)
    warnDroppedPeerEdges(graph, node.id, warnedPeerEdges, emitDiagnostic)

    const key = stringifyEntryKey(entrySpecsOfNode(graph, node))
    const lines = [
      `${key}:`,
      `  version "${escapeQuoted(node.version)}"`,
    ]

    const payload = graph.tarballOf(node.id)
    const resolved = formatResolution(node.resolution)
      ?? deriveResolvedFromCanonical(payload?.resolution)
    if (resolved !== undefined) {
      lines.push(`  resolved "${escapeQuoted(resolved)}"`)
    }

    const integrity = payload?.integrity && emitSri(payload.integrity)
    if (integrity !== undefined && integrity !== '') {
      // F5 (#92) — a single-hash SRI emits BARE; a space-joined multi-hash SRI
      // (`sha1-… sha512-…`) emits QUOTED, matching yarn 1's "quote any value
      // with a space" rule, so the round-trip is byte-faithful and reparse
      // un-quotes it back into the full multiset.
      lines.push(`  integrity ${integrity.includes(' ') ? `"${integrity}"` : integrity}`)
    }

    // Round-trip unknown scalar entry fields (e.g. yarn-1 `uid ""`) captured
    // verbatim on parse — re-emitted after the modelled fields, before deps.
    const extras = emitSidecar?.entryExtras?.get(node.id)
    if (extras !== undefined) {
      for (const raw of extras) lines.push(`  ${raw}`)
    }

    const dependencies = collectDependencyBlockEntries(graph, node.id, emitDiagnostic)
    if (dependencies.length > 0) {
      lines.push('  dependencies:')
      for (const [name, range] of dependencies) {
        lines.push(`    ${quoteDepName(name)} "${escapeQuoted(range)}"`)
      }
    }

    const optionalDependencies = collectBlockEntries(graph, graph.out(node.id, 'optional'), emitDiagnostic)
    if (optionalDependencies.length > 0) {
      lines.push('  optionalDependencies:')
      for (const [name, range] of optionalDependencies) {
        lines.push(`    ${quoteDepName(name)} "${escapeQuoted(range)}"`)
      }
    }

    return { key, text: lines.join('\n') }
  }).sort((a, b) => cmpUtf16(a.key, b.key))

  // §A header strict shape: empty graph emits HEADER as-is (two blank lines
  // after `# yarn lockfile v1`), so `check` / `ensureClassicHeader` treat the
  // output as a valid classic file with zero entries (ADR-0020 §8.1).
  const body = entries.length === 0
    ? ''
    : `${entries.map(entry => entry.text).join('\n\n')}\n`
  const output = HEADER + body

  if (options.lineEnding === 'crlf') {
    return output.replace(/\n/g, '\r\n')
  }

  return output
}

export function enrich(
  graph: Graph,
  sidecar: YarnClassicSidecar | undefined = sidecarByGraph.get(graph),
  options: YarnClassicEnrichOptions = {},
): { graph: Graph; diagnostics: Diagnostic[] } {
  if (options.manifests === undefined) {
    return {
      graph,
      diagnostics: [{
        code: 'YARN_CLASSIC_NO_MANIFESTS',
        severity: 'warning',
        message: 'workspace concretisation requires manifests; leaving yarn-classic graph unclassified',
      }],
    }
  }

  const memberManifests = memberManifestsByName(options.manifests)
  const rootManifest = options.manifests['']
  const rootNodeId = rootManifest?.name !== undefined && rootManifest.version !== undefined
    ? `${rootManifest.name}@${rootManifest.version}`
    : undefined
  const specIndex = specIndexOfGraph(graph, sidecar)
  const plan = planClassicEnrich(graph, rootNodeId, rootManifest, memberManifests, specIndex)

  if (
    plan.rootNode === undefined
    && plan.rootNodeReplacement === undefined
    && plan.addRootEdges.length === 0
    && plan.removeRootEdges.length === 0
    && plan.markWorkspaceEdges.length === 0
    && plan.memberNodeReplacements.length === 0
  ) {
    return { graph, diagnostics: [] }
  }

  const result = graph.mutate(m => {
    if (plan.rootNode !== undefined) {
      m.addNode(plan.rootNode)
    }
    if (plan.rootNodeReplacement !== undefined) {
      m.replaceNode(plan.rootNodeReplacement.id, plan.rootNodeReplacement)
    }
    for (const replacement of plan.memberNodeReplacements) {
      m.replaceNode(replacement.id, replacement)
    }
    for (const edge of plan.removeRootEdges) {
      m.removeEdge(edge.src, edge.dst, edge.kind)
    }
    for (const edge of plan.addRootEdges) {
      m.addEdge(edge.src, edge.dst, edge.kind, edge.attrs)
    }
    for (const edge of plan.markWorkspaceEdges) {
      m.removeEdge(edge.src, edge.dst, edge.kind)
      m.addEdge(edge.src, edge.dst, edge.kind, edge.attrs)
    }
  })

  rememberSidecar(result.graph, sidecar ?? { entrySpecs: new Map() })
  return { graph: result.graph, diagnostics: [] }
}

export function optimize(
  graph: Graph,
  _options: YarnClassicOptimizeOptions = {},
): { graph: Graph; diagnostics: Diagnostic[] } {
  const sidecar = sidecarByGraph.get(graph)
  const reachable = new Set(graph.walk(Array.from(graph.roots())))
  const unreachableNodes = Array.from(graph.nodes(), node => node.id)
    .filter(nodeId => !reachable.has(nodeId))
    .sort(cmpUtf16)

  if (unreachableNodes.length === 0) {
    return {
      graph,
      diagnostics: graph.diagnostics().filter(diagnostic => diagnostic.severity === 'warning'),
    }
  }

  const unreachable = new Set(unreachableNodes)
  const referencedTarballs = new Set<string>()
  const tarballsToRemove = new Map<string, TarballKeyInputs>()
  const internalEdges = unreachableNodes
    .flatMap(src =>
      graph.out(src)
        .filter(edge => unreachable.has(edge.dst))
        .map(edge => ({ src: edge.src, dst: edge.dst, kind: edge.kind })),
    )
    .sort((a, b) =>
      cmpUtf16(`${a.src}\u0000${a.kind}\u0000${a.dst}`, `${b.src}\u0000${b.kind}\u0000${b.dst}`),
    )

  for (const node of graph.nodes()) {
    const inputs = { name: node.name, version: node.version, patch: node.patch }
    const key = toTarballKey(inputs)
    if (unreachable.has(node.id)) {
      tarballsToRemove.set(key, inputs)
      continue
    }
    referencedTarballs.add(key)
  }

  const result = graph.mutate(m => {
    for (const edge of internalEdges) {
      m.removeEdge(edge.src, edge.dst, edge.kind)
    }
    for (const nodeId of unreachableNodes) {
      m.removeNode(nodeId)
    }
    for (const [key, inputs] of Array.from(tarballsToRemove.entries()).sort((a, b) => cmpUtf16(a[0], b[0]))) {
      if (!referencedTarballs.has(key) && graph.tarball(inputs) !== undefined) {
        m.removeTarball(inputs)
      }
    }
  })

  if (sidecar !== undefined) {
    rememberSidecar(result.graph, pruneSidecar(sidecar, result.graph))
  }
  return { graph: result.graph, diagnostics: result.unresolved }
}

function rememberSidecar(graph: Graph, sidecar: YarnClassicSidecar): void {
  if (sidecar.entrySpecs.size === 0 && (sidecar.entryExtras?.size ?? 0) === 0) return
  sidecarByGraph.set(graph, sidecar)
}

function pruneSidecar(sidecar: YarnClassicSidecar, graph: Graph): YarnClassicSidecar {
  const reachableIds = new Set(Array.from(graph.nodes(), node => node.id))
  const entrySpecs = new Map<string, string[]>()
  for (const [nodeId, specs] of sidecar.entrySpecs) {
    if (reachableIds.has(nodeId)) {
      entrySpecs.set(nodeId, specs.slice())
    }
  }
  let entryExtras: Map<string, string[]> | undefined
  if (sidecar.entryExtras !== undefined) {
    entryExtras = new Map<string, string[]>()
    for (const [nodeId, extras] of sidecar.entryExtras) {
      if (reachableIds.has(nodeId)) entryExtras.set(nodeId, extras.slice())
    }
  }
  return entryExtras !== undefined ? { entrySpecs, entryExtras } : { entrySpecs }
}

function ensureClassicHeader(input: string): void {
  if (check(input)) return
  if (BERRY_HEADER_RE.test(input)) {
    throw new LockfileError({
      code: 'FORMAT_MISMATCH',
      message: 'expected yarn-classic lockfile header, got yarn-berry metadata header',
    })
  }
  const lines = input.split('\n')
  if (lines[0] !== HEADER_LINE_1 || lines[1] !== HEADER_LINE_2) {
    throw new LockfileError({
      code: 'FORMAT_MISMATCH',
      message: 'expected yarn-classic lockfile v1 header',
    })
  }
  throw new LockfileError({
    code: 'PARSE_FAILED',
    message: 'yarn-classic header is malformed',
  })
}

function normalizeLineEndings(input: string): string {
  return input.replace(/\r\n/g, '\n')
}

function parseEntries(input: string): YarnClassicEntry[] {
  const entries: YarnClassicEntry[] = []
  const lines = input.split('\n')
  let current: YarnClassicEntry | undefined
  let block: 'dependencies' | 'optionalDependencies' | undefined

  // Start at 0 and let the loop's own `#`-comment and blank-line skipping
  // consume the header block. Old yarn (e.g. lodash's lock) omits the blank
  // line(s) between `# yarn lockfile v1` and the first entry, so a fixed
  // header-length offset would mis-align and orphan the first entry's body.
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] ?? ''
    if (line.length === 0) {
      block = undefined
      continue
    }
    if (line.startsWith('#')) continue

    if (!line.startsWith(' ')) {
      if (!line.endsWith(':')) {
        throw parseFailed(`top-level entry line must end with ':' (${JSON.stringify(line)})`)
      }
      current = {
        key: parseEntryKeyToken(line.slice(0, -1)),
        dependencies: new Map(),
        optionalDependencies: new Map(),
      }
      entries.push(current)
      block = undefined
      continue
    }

    if (current === undefined) {
      throw parseFailed(`body line without entry header (${JSON.stringify(line)})`)
    }

    if (line.startsWith('    ')) {
      if (block === undefined) {
        throw parseFailed(`dependency line outside dependency block (${JSON.stringify(line)})`)
      }
      const [name, range] = parseDependencyLine(line)
      current[block].set(name, range)
      continue
    }

    if (!line.startsWith('  ')) {
      throw parseFailed(`unexpected indent (${JSON.stringify(line)})`)
    }

    if (line === '  dependencies:') {
      block = 'dependencies'
      continue
    }
    if (line === '  optionalDependencies:') {
      block = 'optionalDependencies'
      continue
    }

    block = undefined
    // A QUOTED field-key (`  "version" "1.0.0"`, `  "resolved" "…"`) is not a
    // shape yarn 1 emits — its lockfile writer quotes string VALUES but never
    // field KEYS (`version` / `resolved` / `integrity` begin with a letter and
    // are emitted bare). A quoted key at field position is the signature of a
    // yarn-error.log "Lockfile:" dump (yarn's reporter re-indents the lockfile
    // under that heading) or an otherwise mangled, non-lockfile input. Reject
    // cleanly with a diagnostic that names the likely source, rather than
    // silently capturing it as an unknown-field extra and later throwing a
    // misleading "missing version" (#83 finding 3 — garbage → clean reject; do
    // NOT bend the parser to accept non-lockfiles).
    if (line.startsWith('  "')) {
      throw parseFailed(
        `quoted field-key ${JSON.stringify(line.trimStart())} is not valid yarn-classic `
          + `(yarn 1 never quotes entry field names); input looks like a yarn-error.log dump `
          + `or a mangled lockfile, not a yarn.lock`,
      )
    }
    if (line.startsWith('  version ')) {
      current.version = parseQuotedToken(line.slice('  version '.length))
      continue
    }
    if (line.startsWith('  resolved ')) {
      current.resolved = parseQuotedToken(line.slice('  resolved '.length))
      continue
    }
    if (line.startsWith('  integrity ')) {
      // F5 (#92) — the integrity value is BARE for a single hash
      // (`integrity sha512-…`) but QUOTED when it is a space-separated
      // multi-hash SRI (`integrity "sha1-… sha512-…"`) — yarn 1 quotes any
      // value containing a space. A quoted value must be un-quoted here, else
      // the surrounding `"` glue onto the first/last members and `parseSri`
      // skips every hash (silent integrity loss — the sha1 AND the sha512 both
      // vanish). Un-quote into the bare SRI string so the shared multi-hash
      // parser preserves every algorithm (spec/formats/_common.md §3.1).
      const value = line.slice('  integrity '.length)
      current.integrity = value.startsWith('"') ? parseQuotedToken(value) : value
      continue
    }

    // Unknown scalar entry field — e.g. yarn-1's legacy `uid ""` on link:/file:
    // entries. A universal converter must not reject a valid lockfile over an
    // unmodelled field: capture the line VERBATIM (sans the 2-space indent) for
    // faithful round-trip. The parse surfaces one info diagnostic listing the
    // unmodelled field names.
    current.extras ??= []
    current.extras.push(line.slice(2))
    continue
  }

  return entries
}

// Splits a comma-separated entry-key token into individual descriptor strings,
// handling mixed quoted/unquoted descriptors in the same list as real yarn 1
// lockfiles freely use (e.g. `"foo@1 || 2", foo@^2.0.0`).
// Each descriptor is un-quoted individually; the result is rejoined with ', '
// so that the downstream splitEntryKey(', ') split works on plain strings.
function parseEntryKeyToken(token: string): string {
  const parts = splitMixedDescriptorList(token)
  return parts
    .map(part => (part.startsWith('"') ? parseQuotedToken(part) : part))
    .join(', ')
}

// Splits a raw entry-key token on top-level ', ' boundaries, respecting quoted
// segments so that a range like `"foo@1 || 2"` is never split mid-descriptor.
function splitMixedDescriptorList(token: string): string[] {
  const parts: string[] = []
  let start = 0
  let quoted = false
  let escaped = false

  for (let i = 0; i < token.length; i++) {
    const char = token[i]
    if (escaped) {
      escaped = false
      continue
    }
    if (char === '\\') {
      escaped = true
      continue
    }
    if (char === '"') {
      quoted = !quoted
      continue
    }
    // A top-level comma followed by a space is our delimiter
    if (!quoted && char === ',' && token[i + 1] === ' ') {
      parts.push(token.slice(start, i))
      start = i + 2 // skip ', '
      i++ // skip the space
    }
  }
  parts.push(token.slice(start))
  return parts
}

function parseDependencyLine(line: string): [string, string] {
  const raw = line.slice(4)
  if (!DEP_PAIR_RE.test(raw)) {
    throw parseFailed(`malformed dependency line (${JSON.stringify(line)})`)
  }

  const splitAt = splitDependencyPair(raw)
  const nameToken = raw.slice(0, splitAt)
  const rangeToken = raw.slice(splitAt + 1)
  return [
    nameToken.startsWith('"') ? parseQuotedToken(nameToken) : nameToken,
    rangeToken.startsWith('"') ? parseQuotedToken(rangeToken) : rangeToken,
  ]
}

function splitDependencyPair(raw: string): number {
  let escaped = false
  let quoted = false
  for (let i = 0; i < raw.length; i++) {
    const char = raw[i]
    if (escaped) {
      escaped = false
      continue
    }
    if (char === '\\') {
      escaped = true
      continue
    }
    if (char === '"') {
      quoted = !quoted
      continue
    }
    if (char === ' ' && !quoted) {
      return i
    }
  }
  throw parseFailed(`malformed dependency pair (${JSON.stringify(raw)})`)
}

function parseQuotedToken(token: string): string {
  if (!token.startsWith('"') || !token.endsWith('"')) {
    throw parseFailed(`expected quoted token, got ${JSON.stringify(token)}`)
  }

  let value = ''
  for (let i = 1; i < token.length - 1; i++) {
    const char = token[i]
    if (char !== '\\') {
      value += char
      continue
    }

    const next = token[++i]
    if (next === '\\' || next === '"') {
      value += next
      continue
    }
    throw parseFailed(`unsupported escape sequence in ${JSON.stringify(token)}`)
  }
  return value
}

// Mined from legacy/main/ts/formats/yarn-classic.ts:69-74 — same split on ', '
// after stripping the top-level entry quotes.
function splitEntryKey(key: string): string[] {
  return key.split(', ').filter(Boolean)
}

function parseSpec(spec: string): { name: string; spec: string } {
  const idx = spec.indexOf('@', spec.startsWith('@') ? 1 : 0)
  // A bare package-name entry key (`foo:` with no `@<range>`) is NOT a shape
  // yarn 1 emits — its lockfile writer always keys entries by `<name>@<range>`
  // descriptors (#83 finding 2: malformed, not genuine). Reject with a clear,
  // typed diagnostic that names the missing `@<range>`, rather than the generic
  // "bad entry-spec" message, so the failure is actionable.
  if (idx < 0) {
    throw parseFailed(
      `entry key ${JSON.stringify(spec)} is a bare package name with no '@<range>' descriptor; `
        + `yarn-classic keys must be '<name>@<range>'`,
    )
  }
  if (idx === 0 || idx === spec.length - 1) {
    throw parseFailed(`bad entry-spec ${JSON.stringify(spec)}`)
  }
  return {
    name: spec.slice(0, idx),
    spec: spec.slice(idx + 1),
  }
}

// F6 (#93) — the package identity carried by one entry-key descriptor.
//
// yarn 1 encodes an npm-alias as `"<alias>@npm:<target>@<range>"` (the dep is
// declared under `<alias>` but resolves to the registry package `<target>`).
// The RESOLVED package — the node identity — is `<target>`, NOT `<alias>`;
// `<alias>` lives only as the consumer-facing descriptor name. Keying the node
// off `<alias>` (as the bare `parseSpec().name` does) splits the npm-aliased
// entry into a phantom `<alias>@<version>` node DISTINCT from the real
// `<target>@<version>`, duplicating it. So:
//   - `resolvedName` is the node-identity name — `<target>` for an `npm:` alias,
//     else the descriptor's own name;
//   - `aliasName` is the consumer-facing alias (`<alias>`), or `undefined` for a
//     canonical (non-aliased) descriptor;
//   - `descriptorKey` is the verbatim `<part.name>@<part.spec>` join — the exact
//     entry-key spec, indexed into `specIndex` so a consumer that declares the
//     alias range resolves to the same node, and preserved on the entry key.
//
// Only the `npm:` protocol aliases an identity. A bare/`file:`/`link:`/`git…`
// spec keeps its own name. The alias TARGET may itself be scoped
// (`npm:@scope/pkg@^1`).
function specIdentity(part: { name: string; spec: string }): {
  resolvedName: string
  aliasName?: string
  descriptorKey: string
} {
  const descriptorKey = `${part.name}@${part.spec}`
  if (part.spec.startsWith('npm:')) {
    const target = part.spec.slice('npm:'.length)
    // An alias REQUIRES the `npm:` body to be a full `<target-name>@<range>`
    // locator — a name AND an embedded `@<range>` separator. The target name may
    // be scoped (`npm:@scope/pkg@^1`).
    //
    // CRUCIAL boundary vs the yarn-BERRY default-protocol form `npm:<range>`
    // (`undici-types@npm:~5.26.4`): there the body is a BARE range with NO
    // embedded `@`, so it is NOT an alias — the resolved name is the descriptor's
    // own name. Treating `~5.26.4` as a "target package name" would mint a
    // phantom `~5.26.4@<version>` node (the cross-family berry→classic regression
    // this guard prevents). So: no embedded `@` ⇒ default-protocol range, never
    // an alias.
    const at = target.indexOf('@', target.startsWith('@') ? 1 : 0)
    const targetName = at > 0 ? target.slice(0, at) : undefined
    if (targetName !== undefined && targetName.length > 0 && targetName !== part.name) {
      return { resolvedName: targetName, aliasName: part.name, descriptorKey }
    }
    // A self-referential `npm:` alias to the SAME name (`foo@npm:foo@^1`), or a
    // bare default-protocol range (`foo@npm:^1`), is not a rename — no alias edge
    // attr, identity unchanged.
    return { resolvedName: part.name, descriptorKey }
  }
  return { resolvedName: part.name, descriptorKey }
}

// Bug #99 — Rung-2/3 ladder inputs for the classic edge resolver (the patch /
// link rungs are berry-specific, so classic has no Rung 1 here — Rung 0 → 2 →
// 3 → drop). See spec/formats/_common.md §"Descriptor→node resolution".
interface ClassicEdgeLadderContext {
  candidatesByName:  Map<string, SemverCandidate[]>
  overrides:         readonly OverrideConstraint[]
  manifestsProvided: boolean
}

// A classic descriptor range is a registry range (bare semver or `npm:`-aliased)
// — the only class Rung-3 semver + the resolutions-pin INFO hint apply to. A
// `file:`/`link:`/`git…`/URL range carries an explicit non-`npm:` protocol.
function isClassicRegistryRange(range: string): boolean {
  if (range.startsWith('npm:')) return true
  const colonIdx = range.indexOf(':')
  if (colonIdx <= 0) return true // bare semver / tag
  return !/^[a-z][a-z0-9+.-]*$/i.test(range.slice(0, colonIdx))
}

function addEdgesFromMap(
  builder: ReturnType<typeof newBuilder>,
  diagnostics: Diagnostic[],
  srcId: string,
  deps: Map<string, string>,
  kind: 'dep' | 'optional',
  specIndex: Map<string, string>,
  ladder: ClassicEdgeLadderContext,
): void {
  for (const [name, range] of Array.from(deps.entries()).sort((a, b) => cmpUtf16(a[0], b[0]))) {
    // Rung 0 — exact specIndex match (UNCHANGED, O(1)).
    let dstId = specIndex.get(`${name}@${range}`)
    // Rung 2 — OVERRIDE-MAP forced link. Authoritative pin (`resolutions`) beats
    // semver inference; handles a NON-satisfying pin. The `to` target is fed back
    // through Rung 0 (`specIndex.get`); a target classic can't key (a `patch:`
    // descriptor) falls through to Rung 3 on the ORIGINAL range — never throws.
    if (dstId === undefined && ladder.overrides.length > 0) {
      const to = overrideTargetFor(name, range, [nameOf(srcId)], ladder.overrides)
      if (to !== undefined) {
        const viaOverride = specIndex.get(`${name}@${to}`)
        if (viaOverride !== undefined) dstId = viaOverride
      }
    }
    // Rung 3 — SOURCE-GATED max-satisfying semver (tarball candidates only).
    if (dstId === undefined) {
      const result = semverResolve(range, ladder.candidatesByName.get(name) ?? [])
      if (result.kind === 'bound') {
        dstId = result.id
      } else if (result.kind === 'ambiguous') {
        diagnostics.push(ambiguousResolutionDiagnostic('YARN_CLASSIC', srcId, name, range, result.candidateIds))
        continue // do not guess — mirror the *_PEER_AMBIGUOUS rule
      }
    }
    // Rung 3.5 — DIST-TAG bind (#107). A registry range that is a published
    // dist-TAG (`latest` / `next`, e.g. `node-gyp "latest"`), not a semver range,
    // binds the UNIQUE registry sibling of that name (source-gated like Rung 3).
    // A multi-version tag → diagnose + drop (channel pointers are never guessed).
    if (dstId === undefined) {
      const result = distTagResolve(range, ladder.candidatesByName.get(name) ?? [])
      if (result.kind === 'bound') {
        dstId = result.id
      } else if (result.kind === 'ambiguous') {
        diagnostics.push(ambiguousResolutionDiagnostic('YARN_CLASSIC', srcId, name, range, result.candidateIds))
        if (!ladder.manifestsProvided) {
          diagnostics.push(resolutionPinUnresolvedDiagnostic('YARN_CLASSIC', srcId, name, range))
        }
        continue // do not guess — mirror the *_PEER_AMBIGUOUS rule
      }
    }
    if (dstId === undefined) {
      // Rung 4 — drop (UNCHANGED). Add the resolutions-pin INFO hint when a
      // registry range missed everything and no manifests were supplied.
      diagnostics.push({
        code: 'YARN_CLASSIC_MISSING_ENTRY',
        severity: 'warning',
        subject: srcId,
        message: `missing lockfile entry for ${name}@${range}`,
      })
      if (!ladder.manifestsProvided && isClassicRegistryRange(range) && (ladder.candidatesByName.get(name)?.length ?? 0) > 0) {
        diagnostics.push(resolutionPinUnresolvedDiagnostic('YARN_CLASSIC', srcId, name, range))
      }
      continue
    }
    // F6 (#93) — npm-alias edge attr. When the consumer's dependency-block key
    // (`name`) differs from the resolved target's actual name, the dep is an
    // npm-alias (`<alias> "npm:<target>@<range>"`); record `<alias>` on the edge
    // so emit re-keys the dependency line + entry-key descriptor under the alias
    // (mirrors the shared `EdgeAttrs.alias` model the berry adapter populates).
    // Identity-aware, so the canonical + aliased edges to one target coexist.
    const dstName = nameOf(dstId)
    const attrs: EdgeAttrs = { range }
    if (name !== dstName) attrs.alias = name
    builder.addEdge(srcId, dstId, kind, attrs)
  }
}

function specIndexOfGraph(graph: Graph, sidecar: YarnClassicSidecar | undefined): Map<string, string> {
  const specIndex = new Map<string, string>()
  for (const node of graph.nodes()) {
    const fromSidecar = sidecar?.entrySpecs.get(node.id) ?? []
    if (fromSidecar.length > 0) {
      for (const spec of fromSidecar) {
        specIndex.set(spec, node.id)
      }
      continue
    }

    for (const edge of graph.in(node.id)) {
      if (
        (edge.kind === 'dep' || edge.kind === 'dev' || edge.kind === 'optional')
        && edge.attrs?.range !== undefined
      ) {
        specIndex.set(`${node.name}@${edge.attrs.range}`, node.id)
      }
    }
  }
  return specIndex
}

function memberManifestsByName(manifests: Record<string, YarnClassicManifest>): Map<string, { path: string; manifest: YarnClassicManifest }> {
  const byName = new Map<string, { path: string; manifest: YarnClassicManifest }>()
  for (const [path, manifest] of Object.entries(manifests)) {
    if (path === '' || manifest.name === undefined) continue
    byName.set(manifest.name, { path, manifest })
  }
  return byName
}

function planClassicEnrich(
  graph: Graph,
  rootNodeId: string | undefined,
  rootManifest: YarnClassicManifest | undefined,
  memberManifests: Map<string, { path: string; manifest: YarnClassicManifest }>,
  specIndex: Map<string, string>,
): {
  rootNode: Node | undefined
  rootNodeReplacement: Node | undefined
  memberNodeReplacements: Node[]
  addRootEdges: Edge[]
  removeRootEdges: Edge[]
  markWorkspaceEdges: Edge[]
} {
  const addRootEdges: Edge[] = []
  const removeRootEdges: Edge[] = []
  const markWorkspaceEdges: Edge[] = []
  const memberNodeReplacements: Node[] = []
  const existingRootNode = rootNodeId === undefined ? undefined : graph.getNode(rootNodeId)

  const rootNode = rootNodeId !== undefined
    && existingRootNode === undefined
    && rootManifest?.name !== undefined
    && rootManifest.version !== undefined
    ? {
      id: rootNodeId,
      name: rootManifest.name,
      version: rootManifest.version,
      peerContext: [],
      workspacePath: '',
    }
    : undefined
  const rootNodeReplacement = existingRootNode !== undefined
    && existingRootNode.workspacePath === undefined
    && rootManifest?.name !== undefined
    && rootManifest.version !== undefined
    ? { ...existingRootNode, workspacePath: '' }
    : undefined

  // §C item (b): distinguish workspace-member entries from external lookalikes
  // by setting `workspacePath` on each in-graph node whose name matches a
  // manifest workspace member. Without this, downstream emit (e.g. yarn-berry
  // stringify) cannot tell members apart and emits them as plain npm entries,
  // which strips the `attrs.workspace = true` markers across format boundaries.
  //
  // The version match permits both the `0.0.0-use.local` literal and the
  // manifest-declared version, but a same-name+version external published
  // package would also satisfy that. Tarball presence discriminates: external
  // published packages carry a tarball entry; workspace members are
  // soft-linked and do not.
  for (const node of graph.nodes()) {
    if (node.workspacePath !== undefined) continue
    const member = memberManifests.get(node.name)
    if (member === undefined) continue
    if (node.version !== '0.0.0-use.local' && node.version !== member.manifest.version) continue
    if (graph.tarball({ name: node.name, version: node.version }) !== undefined) continue
    memberNodeReplacements.push({ ...node, workspacePath: member.path })
  }

  const rootOut = rootNodeId === undefined ? [] : graph.out(rootNodeId)
  if (rootNodeId !== undefined && rootManifest !== undefined) {
    const desired = desiredRootEdges(graph, rootNodeId, rootManifest, memberManifests, specIndex)
    const existingByDst = new Map<string, Edge[]>()
    for (const edge of rootOut) {
      const current = existingByDst.get(edge.dst)
      if (current === undefined) existingByDst.set(edge.dst, [edge])
      else current.push(edge)
    }

    for (const edge of desired) {
      const existing = existingByDst.get(edge.dst) ?? []
      const matches = existing.some(candidate => rootEdgeMatches(candidate, edge))
      if (!matches) addRootEdges.push(edge)
      for (const candidate of existing) {
        if (!rootEdgeMatches(candidate, edge)) {
          removeRootEdges.push(candidate)
        }
      }
    }
  }

  for (const node of graph.nodes()) {
    for (const edge of graph.out(node.id)) {
      if (
        edge.kind === 'peer'
        || edge.attrs?.workspace === true
        || edge.attrs?.range === undefined
        || !isWorkspaceProtocolRange(edge.attrs.range)
      ) {
        continue
      }

      const dst = graph.getNode(edge.dst)
      if (dst === undefined || !memberManifests.has(dst.name)) continue
      // ADR-0014 §4.F4 — populate canonical workspaceRange sidecar; yarn-
      // classic carries no `workspace:` protocol on disk, so the F4
      // specifier is the empty pending sentinel and resolvedVersion is
      // best-effort `dst.version`.
      const workspaceRange = dst.version !== undefined && dst.version !== ''
        ? { specifier: '', resolvedVersion: dst.version }
        : { specifier: '' }
      markWorkspaceEdges.push({
        src: edge.src,
        dst: edge.dst,
        kind: edge.kind,
        attrs: { ...edge.attrs, workspace: true, workspaceRange },
      })
    }
  }

  return { rootNode, rootNodeReplacement, memberNodeReplacements, addRootEdges, removeRootEdges, markWorkspaceEdges }
}

function desiredRootEdges(
  graph: Graph,
  rootNodeId: string,
  rootManifest: YarnClassicManifest,
  memberManifests: Map<string, { path: string; manifest: YarnClassicManifest }>,
  specIndex: Map<string, string>,
): Edge[] {
  const edges: Edge[] = []
  for (const [kind, deps] of [
    ['dep', rootManifest.dependencies],
    ['dev', rootManifest.devDependencies],
    ['optional', rootManifest.optionalDependencies],
  ] as const) {
    if (deps === undefined) continue
    for (const [name, range] of Object.entries(deps).sort((a, b) => cmpUtf16(a[0], b[0]))) {
      const dstId = resolveManifestTarget(graph, name, range, memberManifests, specIndex)
      if (dstId === undefined) continue
      if (isWorkspaceProtocolRange(range)) {
        const dst = graph.getNode(dstId)
        const workspaceRange = dst?.version !== undefined && dst.version !== ''
          ? { specifier: range, resolvedVersion: dst.version }
          : { specifier: range }
        edges.push({
          src: rootNodeId,
          dst: dstId,
          kind,
          attrs: { range, workspace: true, workspaceRange },
        })
      } else {
        edges.push({ src: rootNodeId, dst: dstId, kind, attrs: { range } })
      }
    }
  }
  return edges
}

function resolveManifestTarget(
  graph: Graph,
  name: string,
  range: string,
  memberManifests: Map<string, { path: string; manifest: YarnClassicManifest }>,
  specIndex: Map<string, string>,
): string | undefined {
  if (isWorkspaceProtocolRange(range)) {
    return resolveWorkspaceMemberNodeId(graph, name, memberManifests.get(name)?.manifest.version)
  }

  const exact = specIndex.get(`${name}@${range}`)
  if (exact !== undefined) return exact

  const candidates = graph.byName(name)
  if (candidates.length === 1) return candidates[0]
  return candidates.find(id => graph.getNode(id)?.version === range)
}

function resolveWorkspaceMemberNodeId(
  graph: Graph,
  name: string,
  manifestVersion: string | undefined,
): string | undefined {
  const candidates = graph.byName(name)
  return candidates.find(id => graph.getNode(id)?.version === '0.0.0-use.local')
    ?? (manifestVersion === undefined ? undefined : candidates.find(id => graph.getNode(id)?.version === manifestVersion))
    ?? candidates[0]
}

function rootEdgeMatches(left: Edge, right: Edge): boolean {
  return left.src === right.src
    && left.dst === right.dst
    && left.kind === right.kind
    && JSON.stringify(left.attrs ?? {}) === JSON.stringify(right.attrs ?? {})
}

function isWorkspaceProtocolRange(range: string): boolean {
  return range.startsWith('workspace:')
}

function entrySpecsOfNode(graph: Graph, node: Node): string[] {
  // F6 (#93) — an npm-aliased incoming edge keys its entry-key descriptor under
  // the ALIAS, not the node's actual name (`<alias>@npm:<target>@<range>`); the
  // range already carries the `npm:<target>@…` locator. A canonical edge keys
  // under the node's own name. Mirrors the berry `entryKeyOfNode` alias branch.
  const liveSpecs = Array.from(graph.in(node.id))
    .filter(edge => edge.kind === 'dep' || edge.kind === 'optional')
    .filter(edge => edge.attrs?.range !== undefined)
    .map(edge => `${edge.attrs!.alias ?? node.name}@${edge.attrs!.range}`)
  if (liveSpecs.length > 0) {
    return Array.from(new Set(liveSpecs)).sort(cmpUtf16)
  }

  const sidecarSpecs = sidecarByGraph.get(graph)?.entrySpecs.get(node.id)
  if (sidecarSpecs !== undefined && sidecarSpecs.length > 0) {
    return sidecarSpecs.slice().sort(cmpUtf16)
  }

  return [`${node.name}@${node.version}`]
}

function stringifyEntryKey(specs: string[]): string {
  const key = specs.join(', ')
  return mustQuoteEntryKey(specs) ? `"${escapeQuoted(key)}"` : key
}

function mustQuoteEntryKey(specs: string[]): boolean {
  if (specs.length > 1) return true
  return specs.some(spec =>
    spec.startsWith('@')
      || spec.includes('||')
      || ENTRY_KEY_SPECIAL_RE.test(spec)
      || hasNonAscii(spec),
  )
}

function quoteDepName(name: string): string {
  return name.startsWith('@') || !BARE_DEP_NAME_RE.test(name)
    ? `"${escapeQuoted(name)}"`
    : name
}

function escapeQuoted(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

function hasNonAscii(value: string): boolean {
  for (let i = 0; i < value.length; i++) {
    if (value.charCodeAt(i) > 0x7f) return true
  }
  return false
}

function collectDependencyBlockEntries(
  graph: Graph,
  srcId: string,
  emitDiagnostic: (d: Diagnostic) => void,
): Array<[string, string]> {
  return collectBlockEntries(
    graph,
    Array.from(graph.out(srcId, 'dep')).concat(graph.out(srcId, 'dev')),
    emitDiagnostic,
  )
}

function collectBlockEntries(
  graph: Graph,
  edges: readonly Edge[],
  emitDiagnostic: (d: Diagnostic) => void,
): Array<[string, string]> {
  return edges
    .map(edge => {
      const dst = graph.getNode(edge.dst)
      if (dst === undefined || edge.attrs?.range === undefined) return undefined
      // ADR-0014 §4.F4 — workspace edges: yarn-classic lacks `workspace:`
      // protocol; drop the specifier and emit `resolvedVersion` (or fire
      // RECIPE_WORKSPACE_UNRESOLVED when no resolved version is available).
      // Empty pending specifier carried nothing к drop — gate via
      // shouldEmitWorkspaceResolved per ADR-0014 §5:412.
      if (isWorkspaceEdge(edge)) {
        const ws = workspaceRangeOfEdge(edge, dst)
        if (ws !== undefined) {
          const resolved = stringifyForVersionOnly(ws)
          if (resolved === undefined) {
            emitWorkspaceUnresolved(
              { src: edge.src, dst: edge.dst, kind: edge.kind },
              emitDiagnostic,
            )
            return undefined
          }
          if (shouldEmitWorkspaceResolved(ws)) {
            emitWorkspaceResolved(
              { src: edge.src, dst: edge.dst, kind: edge.kind },
              ws.specifier,
              resolved,
              emitDiagnostic,
            )
          }
          return [dst.name, resolved] as [string, string]
        }
      }
      // F6 (#93) — an npm-aliased edge emits its dependency line under the ALIAS
      // name with the verbatim `npm:<target>@<range>` locator as the value
      // (`<alias> "npm:<target>@<range>"`), so reparse re-binds it via the
      // alias-keyed `specIndex` descriptor. A canonical edge uses the target's
      // own name.
      return [edge.attrs.alias ?? dst.name, edge.attrs.range] as [string, string]
    })
    .filter((entry): entry is [string, string] => entry !== undefined)
    .sort((a, b) => cmpUtf16(a[0], b[0]))
}

function warnDroppedPeerEdges(
  graph: Graph,
  srcId: string,
  warned: Set<string>,
  emitDiagnostic: (diagnostic: Diagnostic) => void,
): void {
  for (const edge of graph.out(srcId, 'peer')) {
    const key = `${edge.src}\u0000${edge.dst}\u0000${edge.attrs?.range ?? ''}`
    if (warned.has(key)) continue
    warned.add(key)

    const dst = graph.getNode(edge.dst)
    emitDiagnostic({
      code: 'YARN_CLASSIC_PEER_DROPPED',
      severity: 'warning',
      subject: srcId,
      message: dst === undefined || edge.attrs?.range === undefined
        ? `peer edge ${edge.src} -> ${edge.dst} is unsupported in yarn-classic; dropping on emit`
        : `peer edge ${edge.src} -> ${dst.name}@${edge.attrs.range} is unsupported in yarn-classic; dropping on emit`,
    })
  }
}

function warnPeerContextFlatten(
  node: Node,
  warned: Set<string>,
  emitDiagnostic: (diagnostic: Diagnostic) => void,
): void {
  if (node.peerContext.length === 0 || warned.has(node.id)) return
  warned.add(node.id)
  emitDiagnostic({
    code: 'YARN_CLASSIC_PEER_VIRT_FLATTENED',
    severity: 'warning',
    subject: node.id,
    message: `peerContext ${JSON.stringify(node.peerContext)} is unsupported in yarn-classic; flattening on emit`,
  })
}

function warnPatchDrop(
  node: Node,
  warned: Set<string>,
  emitDiagnostic: (diagnostic: Diagnostic) => void,
): void {
  if (node.patch === undefined || warned.has(node.id)) return
  warned.add(node.id)
  patchEmitDropped(
    node.id,
    'patch',
    `yarn-classic has no patch: protocol; ${JSON.stringify(node.patch)} dropped`,
    emitDiagnostic,
  )
}

// Mined from legacy/main/ts/formats/yarn-classic.ts:188-212. The graph stores
// the resolution as an opaque string; these helpers keep yarn-classic-specific
// `resolved` shapes validated at the adapter boundary.
//
// Two accepted shape families:
//  (1) scheme-based URLs + the scp-like `git@host:owner/repo` shorthand
//      (`isYarnClassicResolvableUrl`); and
//  (2) relative LOCAL specifiers `file:` / `link:` / `portal:` with no `//`
//      authority (`isYarnClassicLocalSpec`) — yarn 1 writes these as the
//      `resolved` value for `file:` / `link:` deps (and `portal:` on locks
//      migrated from yarn-berry): the writer emits `resolved: remote.resolved`
//      verbatim for copy/link references, so the `resolved` of a local dep IS
//      the bare specifier, not an http(s) URL. It must not abort the
//      whole-file parse (#83 finding 1).

// The acceptance predicate for a yarn-classic `resolved` URL: any scheme-based
// URL (https / http / git+ssh / git+https / git / ssh / file …) or the scp-like
// `git@host:owner/repo` shorthand. SHARED by parse and emit so the two stay
// symmetric — anything `parseResolution` accepts off disk must round-trip back
// out via `formatResolution` (else a git+ssh `resolved` line silently vanishes
// on emit, producing a lockfile `yarn install --immutable` rejects).
function isYarnClassicResolvableUrl(input: string): boolean {
  return /^[a-z][a-z0-9+.-]*:\/\//i.test(input) || input.startsWith('git@')
}

// A relative LOCAL specifier `file:` / `link:` / `portal:` whose body is NOT a
// `//`-authority URL (those are handled by `isYarnClassicResolvableUrl`). The
// body must be non-empty — `file:` / `link:` with nothing after the colon is
// not a usable specifier and falls through to the unsupported-shape throw.
const YARN_CLASSIC_LOCAL_SPEC_RE = /^(?:file|link|portal):(?!\/\/)\S/

function isYarnClassicLocalSpec(input: string): boolean {
  return YARN_CLASSIC_LOCAL_SPEC_RE.test(input)
}

// `<file|link|portal>:<path>` → { protocol, path }. Returns undefined for
// non-local shapes (URLs). `path` keeps the body verbatim (leading `./` / `../`
// preserved) so the directory canonical mirrors the on-disk specifier.
function parseLocalSpec(
  resolved: string,
): { protocol: 'file' | 'link' | 'portal'; path: string } | undefined {
  if (!isYarnClassicLocalSpec(resolved)) return undefined
  const colon = resolved.indexOf(':')
  return {
    protocol: resolved.slice(0, colon) as 'file' | 'link' | 'portal',
    path: resolved.slice(colon + 1),
  }
}

// Canonical resolution for a yarn-classic `resolved` value. Local specifiers
// (`file:` / `link:` / `portal:`) canonicalise to a `directory` resolution
// adapter-side: the shared recipe deliberately routes bare `link:` to `unknown`
// (recipe/resolution.ts) because in pnpm `link:` is a WORKSPACE shape — a
// different meaning — so yarn-classic must NOT lean on the recipe for `link:` /
// `portal:` or it would raise a spurious RECIPE_RESOLUTION_UNKNOWN. `file:`
// already maps to `directory` in the recipe, but is handled here too for a
// single code path. Everything else delegates to the recipe (git / tarball /
// codeload / …).
function canonicalResolutionOfResolved(
  resolved: string,
): import('../recipe/resolution.ts').ResolutionCanonical {
  const local = parseLocalSpec(resolved)
  if (local !== undefined) {
    return { type: 'directory', path: local.path }
  }
  return parseResolutionRecipe(resolved, { sourceKind: 'yarn-classic-resolved' })
}

function parseResolution(input: string): string {
  // git deps are first-class in yarn-classic; a single git entry must not abort
  // the parse. Relative `file:` / `link:` / `portal:` local specifiers are
  // equally genuine (#83 finding 1). The opaque string is stored VERBATIM on
  // Node.resolution and re-emitted byte-for-byte by `formatResolution`; the
  // canonical resolution is derived separately via `canonicalResolutionOfResolved`.
  if (isYarnClassicResolvableUrl(input) || isYarnClassicLocalSpec(input)) {
    return input
  }
  throw parseFailed(`unsupported resolved URL ${JSON.stringify(input)}`)
}

// ADR-0014 §4.F3: yarn-classic stringify round-trips any URL-shaped PM-native
// resolution — the same shapes `parseResolution` accepts (incl. git+ssh / git:
// / ssh: / scp-like `git@…`) — PLUS the relative `file:` / `link:` / `portal:`
// local specifiers (#83 finding 1). Re-emitting the local specifier VERBATIM
// preserves the file/link/portal distinction that a `directory` canonical would
// otherwise flatten to a single `file:` shape. PM-native strings from foreign
// sources (yarn-berry locators, pnpm workspace `link:` etc.) are neither shape
// → return undefined to delegate to the canonical-derived fallback instead of
// throwing.
function formatResolution(input: string | undefined): string | undefined {
  if (input === undefined) return undefined
  return isYarnClassicResolvableUrl(input) || isYarnClassicLocalSpec(input) ? input : undefined
}

// ADR-0014 §4.F3 cross-format fallback: project canonical → yarn-classic
// `resolved` URL when PM-native sidecar is absent. Workspace canonical
// returns undefined (yarn-classic encodes workspaces as sentinel-version
// entries, not via `resolved`).
function deriveResolvedFromCanonical(
  canonical: import('../recipe/resolution.ts').ResolutionCanonical | undefined,
): string | undefined {
  if (canonical === undefined) return undefined
  const candidate = stringifyForYarnClassic(canonical)
  // `unknown` canonical returns its raw verbatim — for yarn-berry locators
  // (`<n>@patch:...`, `<n>@npm:<ver>`, etc.) this is NOT a re-parseable
  // yarn-classic `resolved` shape and the parse rejects on reparse. Filter the
  // emit to re-parseable shapes only: URLs PLUS the `file:` / `link:` /
  // `portal:` local specifiers (a `directory` canonical projects to
  // `file:./<path>`, #83 finding 1). The underlying loss is already attributed
  // by `warnPatchDrop` / `RECIPE_FEATURE_DROPPED` upstream when relevant.
  if (
    candidate !== undefined
    && !isYarnClassicResolvableUrl(candidate)
    && !isYarnClassicLocalSpec(candidate)
  ) {
    return undefined
  }
  return candidate
}

function parseFailed(message: string): LockfileError {
  return new LockfileError({ code: 'PARSE_FAILED', message })
}
