// yarn-berry-v7 — transitional `__metadata.version: 7` lockfile shape emitted
// by Yarn 4 RC releases between the v6 (yarn 3.x) and v8 (yarn 4.x stable)
// generations. Empirically present in real-world snapshots;
// no synthetic fixture is generated by `_gen.mjs` since the producing
// yarn-bundle is no longer reachable.
//
// Per-version deltas vs ADR-0018 (yarn-berry pre-v9 family):
//   - rangeEmit:      'quoted-protocol' — matches v8/v9 (`"npm:^1.2.3"` inner
//                     blocks); v7 lockfiles use the protocol-prefixed quoted
//                     form, NOT the v4/v5/v6 bare-range shape.
//   - checksumPrefix: false           — matches v4/v5/v6 (raw sha512 hex);
//                     v7 has NOT yet adopted the `<cacheKey>/<hex>` prefix
//                     introduced with v8.
//   - conditionsAllowed: true         — `conditions:` block is supported
//                     (v5+ inheritance per ADR-0018 §A.delta).
//
// ADR-0018 does not list v7 in its concrete-deltas table. QUEUE.md tracks the
// required specification amendment; this adapter strictly composes existing
// `_yarn-berry-core` capabilities.

import type { Diagnostic, Graph } from '../graph.ts'
import {
  checkFamily,
  enrichFamily,
  optimizeFamily,
  parseFamily,
  stringifyFamily,
  type YarnBerryFamilyEnrichOptions,
  type YarnBerryFamilyOptimizeOptions,
  type YarnBerryFamilyParseOptions,
  type YarnBerryFamilyStringifyOptions,
} from './_yarn-berry-core.ts'

const CONFIG = {
  lockfileVersion: 7,
  codePrefix: 'YARN_BERRY_V7',
  rangeEmit: 'quoted-protocol',
  checksumPrefix: false,
  conditionsAllowed: true,
} as const

export type YarnBerryParseOptions = YarnBerryFamilyParseOptions
export type YarnBerryStringifyOptions = YarnBerryFamilyStringifyOptions
export type YarnBerryEnrichOptions = YarnBerryFamilyEnrichOptions
export type YarnBerryOptimizeOptions = YarnBerryFamilyOptimizeOptions

export function check(input: string): boolean {
  return checkFamily(input, CONFIG)
}

export function parse(input: string, options: YarnBerryParseOptions = {}): Graph {
  return parseFamily(input, options, CONFIG).graph
}

export function stringify(graph: Graph, options: YarnBerryStringifyOptions = {}): string {
  return stringifyFamily(graph, CONFIG, options).lockfile
}

export function enrich(
  graph: Graph,
  options: YarnBerryEnrichOptions = {},
): { graph: Graph; diagnostics: Diagnostic[] } {
  return enrichFamily(graph, CONFIG, options)
}

export function optimize(
  graph: Graph,
  options: YarnBerryOptimizeOptions = {},
): { graph: Graph; diagnostics: Diagnostic[] } {
  return optimizeFamily(graph, options)
}
