import {
  GraphError,
  newBuilder,
  type Diagnostic,
  type Graph,
  type Node,
} from '../graph.ts'
import { LockfileError } from '../errors.ts'

const HEADER =
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n' +
  '# yarn lockfile v1\n\n\n'
const HEADER_LINE_1 = '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.'
const HEADER_LINE_2 = '# yarn lockfile v1'
const cmpUtf16 = (a: string, b: string): number => a < b ? -1 : a > b ? 1 : 0

const QUOTED_PAIR_RE = /^("(?:\\.|[^"])*"|[^\s"].*) "(?:\\.|[^"])*"$/
const BARE_DEP_NAME_RE = /^[A-Za-z0-9._-]+$/
const ENTRY_KEY_SPECIAL_RE = /[\s:",#?*&!|>'`[\]{}]/
const BERRY_HEADER_RE = /^__metadata:\s*(?:\r?\n|$)/m

interface YarnClassicSidecar {
  entrySpecs: Map<string, string[]>
}

interface YarnClassicEntry {
  key: string
  version?: string
  resolved?: string
  integrity?: string
  dependencies: Map<string, string>
  optionalDependencies: Map<string, string>
}

export interface YarnClassicStringifyOptions {
  lineEnding?: 'lf' | 'crlf'
}

const sidecarByGraph = new WeakMap<Graph, YarnClassicSidecar>()

// Mined from legacy/main/ts/formats/yarn-classic.ts:30, but tightened to the
// exact §A header shape rather than a loose substring probe.
export function check(input: string): boolean {
  return normalizeLineEndings(input).startsWith(HEADER)
}

export function parse(input: string): Graph {
  const normalized = normalizeLineEndings(input)
  ensureClassicHeader(normalized)

  const builder = newBuilder()
  const diagnostics: Diagnostic[] = []
  const entries = parseEntries(normalized)
  const specIndex = new Map<string, string>()
  const sidecar = new Map<string, string[]>()
  const entryNodes: Array<{ node: Node; entry: YarnClassicEntry }> = []
  const seenIds = new Set<string>()

  for (const entry of entries) {
    const specs = splitEntryKey(entry.key)
    if (specs.length === 0) {
      throw parseFailed(`entry ${JSON.stringify(entry.key)} has empty spec list`)
    }
    if (entry.version === undefined) {
      throw parseFailed(`entry ${JSON.stringify(entry.key)} missing version`)
    }

    const specsByName = new Map<string, string[]>()
    for (const spec of specs) {
      const part = parseSpec(spec)
      const current = specsByName.get(part.name)
      if (current === undefined) specsByName.set(part.name, [part.spec])
      else current.push(part.spec)
    }

    for (const [name, rawRanges] of specsByName) {
      const ranges = Array.from(new Set(rawRanges)).sort(cmpUtf16)
      const id = `${name}@${entry.version}`
      if (seenIds.has(id)) {
        throw new LockfileError({
          code: 'IRREDUCIBLE_LOSS',
          message: `two entries collapse onto NodeId ${id}`,
        })
      }
      seenIds.add(id)

      const node: Node = {
        id,
        name,
        version: entry.version,
        peerContext: [],
      }
      if (entry.resolved !== undefined) {
        node.resolution = parseResolution(entry.resolved)
      }
      builder.addNode(node)
      if (entry.integrity !== undefined) {
        builder.setTarball({ name, version: entry.version }, { integrity: entry.integrity })
      }

      sidecar.set(id, ranges.map(range => `${name}@${range}`))
      entryNodes.push({ node, entry })
      for (const range of ranges) {
        specIndex.set(`${name}@${range}`, id)
      }
    }
  }

  for (const { node, entry } of entryNodes) {
    addEdgesFromMap(builder, diagnostics, node.id, entry.dependencies, 'dep', specIndex)
    addEdgesFromMap(builder, diagnostics, node.id, entry.optionalDependencies, 'optional', specIndex)
  }

  for (const diagnostic of diagnostics) {
    builder.diagnostic(diagnostic)
  }

  try {
    const graph = builder.seal()
    rememberSidecar(graph, { entrySpecs: sidecar })
    return graph
  } catch (error) {
    if (error instanceof GraphError) {
      throw new LockfileError({
        code: 'PARSE_FAILED',
        message: `seal failed: ${error.message}`,
      })
    }
    throw error
  }
}

export function stringify(graph: Graph, options: YarnClassicStringifyOptions = {}): string {
  const entries = Array.from(graph.nodes(), node => {
    const key = stringifyEntryKey(entrySpecsOfNode(graph, node))
    const lines = [
      `${key}:`,
      `  version "${escapeQuoted(node.version)}"`,
    ]

    const resolved = formatResolution(node.resolution)
    if (resolved !== undefined) {
      lines.push(`  resolved "${escapeQuoted(resolved)}"`)
    }

    const integrity = graph.tarballOf(node.id)?.integrity
    if (integrity !== undefined) {
      lines.push(`  integrity ${integrity}`)
    }

    const dependencies = collectBlockEntries(graph, node.id, 'dep')
    if (dependencies.length > 0) {
      lines.push('  dependencies:')
      for (const [name, range] of dependencies) {
        lines.push(`    ${quoteDepName(name)} "${escapeQuoted(range)}"`)
      }
    }

    const optionalDependencies = collectBlockEntries(graph, node.id, 'optional')
    if (optionalDependencies.length > 0) {
      lines.push('  optionalDependencies:')
      for (const [name, range] of optionalDependencies) {
        lines.push(`    ${quoteDepName(name)} "${escapeQuoted(range)}"`)
      }
    }

    return { key, text: lines.join('\n') }
  }).sort((a, b) => cmpUtf16(a.key, b.key))

  let output = HEADER + entries.map(entry => entry.text).join('\n\n')
  if (entries.length === 0) output = HEADER.trimEnd()
  output += '\n'

  if (options.lineEnding === 'crlf') {
    return output.replace(/\n/g, '\r\n')
  }

  return output
}

function rememberSidecar(graph: Graph, sidecar: YarnClassicSidecar): void {
  if (sidecar.entrySpecs.size === 0) return
  sidecarByGraph.set(graph, sidecar)
}

function ensureClassicHeader(input: string): void {
  if (check(input)) return
  if (BERRY_HEADER_RE.test(input)) {
    throw new LockfileError({
      code: 'FORMAT_MISMATCH',
      message: 'expected yarn-classic lockfile header, got yarn-berry metadata header',
    })
  }
  const lines = input.split('\n')
  if (lines[0] !== HEADER_LINE_1 || lines[1] !== HEADER_LINE_2) {
    throw new LockfileError({
      code: 'FORMAT_MISMATCH',
      message: 'expected yarn-classic lockfile v1 header',
    })
  }
  throw new LockfileError({
    code: 'PARSE_FAILED',
    message: 'yarn-classic header is malformed',
  })
}

function normalizeLineEndings(input: string): string {
  return input.replace(/\r\n/g, '\n')
}

function parseEntries(input: string): YarnClassicEntry[] {
  const entries: YarnClassicEntry[] = []
  const lines = input.split('\n')
  let current: YarnClassicEntry | undefined
  let block: 'dependencies' | 'optionalDependencies' | undefined

  for (let i = 4; i < lines.length; i++) {
    const line = lines[i] ?? ''
    if (line.length === 0) {
      block = undefined
      continue
    }
    if (line.startsWith('#')) continue

    if (!line.startsWith(' ')) {
      if (!line.endsWith(':')) {
        throw parseFailed(`top-level entry line must end with ':' (${JSON.stringify(line)})`)
      }
      current = {
        key: parseEntryKeyToken(line.slice(0, -1)),
        dependencies: new Map(),
        optionalDependencies: new Map(),
      }
      entries.push(current)
      block = undefined
      continue
    }

    if (current === undefined) {
      throw parseFailed(`body line without entry header (${JSON.stringify(line)})`)
    }

    if (line.startsWith('    ')) {
      if (block === undefined) {
        throw parseFailed(`dependency line outside dependency block (${JSON.stringify(line)})`)
      }
      const [name, range] = parseDependencyLine(line)
      current[block].set(name, range)
      continue
    }

    if (!line.startsWith('  ')) {
      throw parseFailed(`unexpected indent (${JSON.stringify(line)})`)
    }

    if (line === '  dependencies:') {
      block = 'dependencies'
      continue
    }
    if (line === '  optionalDependencies:') {
      block = 'optionalDependencies'
      continue
    }

    block = undefined
    if (line.startsWith('  version ')) {
      current.version = parseQuotedToken(line.slice('  version '.length))
      continue
    }
    if (line.startsWith('  resolved ')) {
      current.resolved = parseQuotedToken(line.slice('  resolved '.length))
      continue
    }
    if (line.startsWith('  integrity ')) {
      current.integrity = line.slice('  integrity '.length)
      continue
    }

    throw parseFailed(`unsupported entry field (${JSON.stringify(line)})`)
  }

  return entries
}

function parseEntryKeyToken(token: string): string {
  return token.startsWith('"') ? parseQuotedToken(token) : token
}

function parseDependencyLine(line: string): [string, string] {
  const raw = line.slice(4)
  if (!QUOTED_PAIR_RE.test(raw)) {
    throw parseFailed(`malformed dependency line (${JSON.stringify(line)})`)
  }

  const splitAt = splitDependencyPair(raw)
  const nameToken = raw.slice(0, splitAt)
  const rangeToken = raw.slice(splitAt + 1)
  return [
    nameToken.startsWith('"') ? parseQuotedToken(nameToken) : nameToken,
    parseQuotedToken(rangeToken),
  ]
}

function splitDependencyPair(raw: string): number {
  let escaped = false
  let quoted = false
  for (let i = 0; i < raw.length; i++) {
    const char = raw[i]
    if (escaped) {
      escaped = false
      continue
    }
    if (char === '\\') {
      escaped = true
      continue
    }
    if (char === '"') {
      quoted = !quoted
      continue
    }
    if (char === ' ' && !quoted) {
      return i
    }
  }
  throw parseFailed(`malformed dependency pair (${JSON.stringify(raw)})`)
}

function parseQuotedToken(token: string): string {
  if (!token.startsWith('"') || !token.endsWith('"')) {
    throw parseFailed(`expected quoted token, got ${JSON.stringify(token)}`)
  }

  let value = ''
  for (let i = 1; i < token.length - 1; i++) {
    const char = token[i]
    if (char !== '\\') {
      value += char
      continue
    }

    const next = token[++i]
    if (next === '\\' || next === '"') {
      value += next
      continue
    }
    throw parseFailed(`unsupported escape sequence in ${JSON.stringify(token)}`)
  }
  return value
}

// Mined from legacy/main/ts/formats/yarn-classic.ts:69-74 — same split on ', '
// after stripping the top-level entry quotes.
function splitEntryKey(key: string): string[] {
  return key.split(', ').filter(Boolean)
}

function parseSpec(spec: string): { name: string; spec: string } {
  const idx = spec.indexOf('@', spec.startsWith('@') ? 1 : 0)
  if (idx <= 0 || idx === spec.length - 1) {
    throw parseFailed(`bad entry-spec ${JSON.stringify(spec)}`)
  }
  return {
    name: spec.slice(0, idx),
    spec: spec.slice(idx + 1),
  }
}

function addEdgesFromMap(
  builder: ReturnType<typeof newBuilder>,
  diagnostics: Diagnostic[],
  srcId: string,
  deps: Map<string, string>,
  kind: 'dep' | 'optional',
  specIndex: Map<string, string>,
): void {
  for (const [name, range] of Array.from(deps.entries()).sort((a, b) => cmpUtf16(a[0], b[0]))) {
    const dstId = specIndex.get(`${name}@${range}`)
    if (dstId === undefined) {
      diagnostics.push({
        code: 'YARN_CLASSIC_MISSING_ENTRY',
        severity: 'warning',
        subject: srcId,
        message: `missing lockfile entry for ${name}@${range}`,
      })
      continue
    }
    builder.addEdge(srcId, dstId, kind, { range })
  }
}

function entrySpecsOfNode(graph: Graph, node: Node): string[] {
  const liveSpecs = Array.from(graph.in(node.id))
    .filter(edge => edge.kind === 'dep' || edge.kind === 'dev' || edge.kind === 'optional')
    .map(edge => edge.attrs?.range)
    .filter((range): range is string => range !== undefined)
    .map(range => `${node.name}@${range}`)
  if (liveSpecs.length > 0) {
    return Array.from(new Set(liveSpecs)).sort(cmpUtf16)
  }

  const sidecarSpecs = sidecarByGraph.get(graph)?.entrySpecs.get(node.id)
  if (sidecarSpecs !== undefined && sidecarSpecs.length > 0) {
    return sidecarSpecs.slice().sort(cmpUtf16)
  }

  return [`${node.name}@${node.version}`]
}

function stringifyEntryKey(specs: string[]): string {
  const key = specs.join(', ')
  return mustQuoteEntryKey(specs) ? `"${escapeQuoted(key)}"` : key
}

function mustQuoteEntryKey(specs: string[]): boolean {
  if (specs.length > 1) return true
  return specs.some(spec =>
    spec.startsWith('@')
      || spec.includes('||')
      || ENTRY_KEY_SPECIAL_RE.test(spec)
      || hasNonAscii(spec),
  )
}

function quoteDepName(name: string): string {
  return name.startsWith('@') || !BARE_DEP_NAME_RE.test(name)
    ? `"${escapeQuoted(name)}"`
    : name
}

function escapeQuoted(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

function hasNonAscii(value: string): boolean {
  for (let i = 0; i < value.length; i++) {
    if (value.charCodeAt(i) > 0x7f) return true
  }
  return false
}

function collectBlockEntries(graph: Graph, srcId: string, kind: 'dep' | 'optional'): Array<[string, string]> {
  return graph.out(srcId, kind)
    .map(edge => {
      const dst = graph.getNode(edge.dst)
      if (dst === undefined || edge.attrs?.range === undefined) return undefined
      return [dst.name, edge.attrs.range] as [string, string]
    })
    .filter((entry): entry is [string, string] => entry !== undefined)
    .sort((a, b) => cmpUtf16(a[0], b[0]))
}

// Mined from legacy/main/ts/formats/yarn-classic.ts:188-212. The graph stores
// the resolution as an opaque string; these helpers keep yarn-classic-specific
// URL shapes validated at the adapter boundary.
function parseResolution(input: string): string {
  if (
    input.startsWith('https://codeload.github.com/')
    || input.startsWith('git+https://')
    || input.startsWith('http://')
    || input.startsWith('https://')
  ) {
    return input
  }
  throw parseFailed(`unsupported resolved URL ${JSON.stringify(input)}`)
}

function formatResolution(input: string | undefined): string | undefined {
  if (input === undefined) return undefined
  return parseResolution(input)
}

function parseFailed(message: string): LockfileError {
  return new LockfileError({ code: 'PARSE_FAILED', message })
}
