// yarn-berry-v9 (`__metadata.version: 9`) — parse + stringify adapter.
//
// See spec/formats/yarn-berry-v9.md, ADR-0010, and ADR-0011 for the
// model contract.
//
// Phase 2 v2 — open caveats, deliberately unhandled here:
// - Read-side peer enrichment is still partial. Stringify synthesizes
//   `peerDependencies` from graph peer edges, but parse does not yet
//   rehydrate semver-ranged peer blocks into peer edges + peerContext.
//   yarn-berry-v9 emits flat lockfiles (no `virtual:` keys), so
//   peer-virtualized nodes stringify with a warning and collapse to
//   their underlying resolution on the next parse.
// - `npm:` alias collisions still throw `IRREDUCIBLE_LOSS` when two
//   entries collapse onto one NodeId.
// - Unknown per-entry fields (`linkType`, `languageName`, etc.) are
//   re-derivable on emit; ignored on parse.

import { createHash } from 'node:crypto'
import path from 'node:path'
import {
  newBuilder,
  GraphError,
  type Graph,
  type Node,
  type EdgeKind,
  type TarballPayload,
  type Diagnostic,
} from '../graph.ts'
import { LockfileError } from '../errors.ts'
import { readWorkspaceFileBytes } from './_path.ts'
import {
  parse as parseSyml,
  stringify as stringifySyml,
  type SymlMap,
  type SymlValue,
} from './_yarn-syml.ts'

const PREAMBLE =
  '# This file is generated by running "yarn install" inside your project.\n' +
  '# Manual changes might be lost - proceed with caution!'
const cmpStr = (a: string, b: string): number => a < b ? -1 : a > b ? 1 : 0

export class YarnBerryParseError extends Error {
  readonly code: 'PARSE_FAILED' | 'FORMAT_MISMATCH' | 'IRREDUCIBLE_LOSS'
  constructor(code: 'PARSE_FAILED' | 'FORMAT_MISMATCH' | 'IRREDUCIBLE_LOSS', message: string) {
    super(message)
    this.name = 'YarnBerryParseError'
    this.code = code
  }
}

export interface YarnBerryParseOptions {
  workspaceRoot?: string
}

export interface YarnBerryStringifyOptions {
  lineEnding?: 'lf' | 'crlf'
  cacheKey?: string
  onDiagnostic?: (diagnostic: Diagnostic) => void
}

/** Sniffer: matches yarn-berry-v9's discriminant (`__metadata.version: 9`). */
export function check(input: string): boolean {
  // Match the version line within the first kilobyte to keep this cheap.
  const head = input.slice(0, 4096)
  return /^__metadata:\s*[\r\n]+(?:[ \t]+[^\n]*[\r\n]+)*?[ \t]+version:\s*9\s*(?:[\r\n]|$)/m.test(head)
}

interface SpecPart {
  name:     string
  protocol: string
  spec:     string
}

/** Parses one entry-key spec, e.g. `"foo@npm:^1.0.0"` → `{name:'foo', protocol:'npm', spec:'^1.0.0'}`. Scoped names keep the leading `@`. */
function parseSpec(raw: string): SpecPart {
  // First-`@`-after-scope-prefix introduces the protocol. Patch refs like
  // `name@patch:foo@npm:1#path` contain extra `@`s in the spec part — taking
  // the *first* separator (skipping a leading `@scope/` `@`) is the correct rule.
  const startFrom = raw[0] === '@' ? 1 : 0
  let sepIdx = -1
  for (let i = startFrom; i < raw.length; i++) {
    if (raw[i] === '@') { sepIdx = i; break }
  }
  if (sepIdx <= 0) {
    throw new YarnBerryParseError('PARSE_FAILED', `bad entry-spec, no protocol separator: ${raw}`)
  }
  const name = raw.slice(0, sepIdx)
  const rest = raw.slice(sepIdx + 1)
  const colon = rest.indexOf(':')
  if (colon < 0) {
    throw new YarnBerryParseError('PARSE_FAILED', `bad entry-spec, no protocol colon: ${raw}`)
  }
  return { name, protocol: rest.slice(0, colon), spec: rest.slice(colon + 1) }
}

/** Splits a multi-spec entry-key on `, ` (yarn's separator) and parses each part. */
function parseEntryKey(key: string): SpecPart[] {
  return key.split(', ').map(s => parseSpec(s.trim()))
}

/** Strips `workspace:` prefix and normalises the path: `.` → '' (root project), `./pkg` → 'pkg'. */
function workspacePathOf(spec: string): string {
  if (spec === '.') return ''
  if (spec.startsWith('./')) return spec.slice(2)
  return spec
}

function asMap(v: SymlValue | undefined): SymlMap | undefined {
  return v && typeof v === 'object' ? v : undefined
}

function asString(v: SymlValue | undefined): string | undefined {
  return typeof v === 'string' ? v : undefined
}

/** Validates `__metadata.version: 9` and rejects unsupported resolution protocols. */
function validateMetadata(ast: SymlMap): void {
  const meta = asMap(ast['__metadata'])
  if (!meta) {
    throw new YarnBerryParseError('FORMAT_MISMATCH', `missing __metadata block`)
  }
  if (asString(meta['version']) !== '9') {
    throw new YarnBerryParseError(
      'FORMAT_MISMATCH',
      `expected __metadata.version: 9, got ${JSON.stringify(meta['version'])}`,
    )
  }
}

export function parse(input: string, options: YarnBerryParseOptions = {}): Graph {
  const ast = parseSyml(input)
  validateMetadata(ast)

  const builder = newBuilder()
  const diagnostics: Diagnostic[] = []

  // Collect entries (everything except __metadata).
  const entries: Array<{ key: string; value: SymlMap; specs: SpecPart[] }> = []
  for (const [key, value] of Object.entries(ast)) {
    if (key === '__metadata') continue
    const valueMap = asMap(value)
    if (!valueMap) {
      diagnostics.push({
        code:    'YARN_BERRY_BAD_ENTRY',
        severity: 'warning',
        message: `entry ${JSON.stringify(key)} is not a block; skipping`,
      })
      continue
    }
    const specs = parseEntryKey(key)
    entries.push({ key, value: valueMap, specs })
  }

  // First pass: add nodes. Build a spec-string → NodeId index for edge resolution.
  const specIndex = new Map<string, string>()
  const seenIds = new Set<string>()

  for (const { key, value, specs } of entries) {
    const first = specs[0]
    if (!first) {
      throw new YarnBerryParseError('PARSE_FAILED', `entry ${JSON.stringify(key)} has empty spec`)
    }
    const version = asString(value['version'])
    if (version === undefined) {
      throw new YarnBerryParseError('PARSE_FAILED', `entry ${JSON.stringify(key)} missing 'version'`)
    }
    const id = `${first.name}@${version}`

    if (seenIds.has(id)) {
      throw new YarnBerryParseError(
        'IRREDUCIBLE_LOSS',
        `two entries collapse onto NodeId ${id} — likely npm: alias or patch: collision`,
      )
    }
    seenIds.add(id)

    const resolution = asString(value['resolution'])
    const patchResult = resolution !== undefined
      ? extractPatchFingerprint(id, resolution, options.workspaceRoot)
      : undefined

    const node: Node = {
      id,
      name:        first.name,
      version,
      peerContext: [],
    }
    if (resolution !== undefined) node.resolution = resolution
    if (patchResult?.patch !== undefined) node.patch = patchResult.patch
    if (first.protocol === 'workspace') {
      node.workspacePath = workspacePathOf(first.spec)
    }
    builder.addNode(node)
    if (patchResult?.diagnostic) diagnostics.push(patchResult.diagnostic)

    // Tarball payload — checksum + bin for now; engines/license aren't in v9 lockfiles per fixture probe.
    const payload: TarballPayload = {}
    const checksum = asString(value['checksum'])
    if (checksum !== undefined) payload.integrity = checksum
    const binMap = asMap(value['bin'])
    if (binMap) {
      const bin: Record<string, string> = {}
      for (const [n, p] of Object.entries(binMap)) {
        if (typeof p === 'string') bin[n] = p
      }
      if (Object.keys(bin).length > 0) payload.bin = bin
    }
    if (Object.keys(payload).length > 0) {
      builder.setTarball({ name: first.name, version, patch: patchResult?.patch }, payload)
    }

    // Index every spec in this entry's key so dep-resolution can hit them.
    for (const s of specs) {
      const lookup = `${s.name}@${s.protocol}:${s.spec}`
      specIndex.set(lookup, id)
    }
  }

  // Second pass: edges from `dependencies` and `optionalDependencies`.
  for (const { value, specs } of entries) {
    const first = specs[0]
    if (!first) continue
    const version = asString(value['version'])
    if (version === undefined) continue
    const srcId = `${first.name}@${version}`

    addEdgesFromBlock(builder, srcId, asMap(value['dependencies']), 'dep', specIndex, diagnostics)
    addEdgesFromBlock(builder, srcId, asMap(value['optionalDependencies']), 'optional', specIndex, diagnostics)
    // peerDependencies → not yet (Phase 2 v1 limitation; see file header).
  }

  for (const d of diagnostics) builder.diagnostic(d)

  try {
    return builder.seal()
  } catch (e) {
    if (e instanceof GraphError) {
      throw new YarnBerryParseError('PARSE_FAILED', `seal failed: ${e.message}`)
    }
    throw e
  }
}

export function stringify(graph: Graph, options: YarnBerryStringifyOptions = {}): string {
  const metadata: SymlMap = { version: '9' }
  if (options.cacheKey !== undefined) {
    metadata['cacheKey'] = options.cacheKey
  }

  const root: SymlMap = { __metadata: metadata }
  const entries = Array.from(graph.nodes(), node => ({
    nodeId: node.id,
    key: entryKeyOfNode(graph, node),
    value: entryOfNode(graph, node, options),
  })).sort((a, b) => cmpStr(a.key, b.key))

  const seenIds = new Map<string, string>()
  for (const entry of entries) {
    const emitId = `${graph.getNode(entry.nodeId)?.name}@${graph.getNode(entry.nodeId)?.version}`
    const prevNodeId = seenIds.get(emitId)
    if (prevNodeId !== undefined) {
      throw new LockfileError({
        code: 'IRREDUCIBLE_LOSS',
        message: `duplicate node id collides on emit: ${emitId} from ${prevNodeId}, ${entry.nodeId}`,
      })
    }
    seenIds.set(emitId, entry.nodeId)
    root[entry.key] = entry.value
  }

  let output = `${PREAMBLE}\n\n${stringifySyml(root)}`
  output = output.replace(/^__metadata:\n  version: "9"\n/m, '__metadata:\n  version: 9\n')
  if (options.lineEnding === 'crlf') {
    output = output.replace(/\n/g, '\r\n')
  }
  return output
}

function emitStringifyDiagnostic(options: YarnBerryStringifyOptions, diagnostic: Diagnostic): void {
  options.onDiagnostic?.(diagnostic)
}

function entryKeyOfNode(graph: Graph, node: Node): string {
  const primary = primarySpecOfNode(node)
  const specs = new Set<string>([primary])

  for (const edge of graph.in(node.id)) {
    if (edge.kind === 'peer') continue
    if (edge.attrs?.range !== undefined) {
      specs.add(`${node.name}@${edge.attrs.range}`)
    }
  }

  const rest = Array.from(specs).filter(spec => spec !== primary).sort(cmpStr)
  return [primary, ...rest].join(', ')
}

function primarySpecOfNode(node: Node): string {
  if (node.workspacePath !== undefined) {
    return `${node.name}@workspace:${node.workspacePath === '' ? '.' : node.workspacePath}`
  }

  const exact = exactSpecOfResolution(node)
  return exact ?? `${node.name}@npm:${node.version}`
}

function exactSpecOfResolution(node: Node): string | undefined {
  if (node.resolution === undefined) return undefined
  if (node.resolution.startsWith(`${node.name}@patch:`)) {
    const locator = patchLocatorOfResolution(node.resolution)
    if (locator === undefined) return undefined
    return baseSpecOfPatchLocator(locator)
  }
  return node.resolution.startsWith(`${node.name}@`) ? node.resolution : undefined
}

function baseSpecOfPatchLocator(locator: string): string | undefined {
  if (!locator.startsWith('patch:')) return undefined
  const hashIdx = locator.indexOf('#')
  const encoded = hashIdx >= 0
    ? locator.slice('patch:'.length, hashIdx)
    : locator.slice('patch:'.length)
  try {
    return decodeURIComponent(encoded)
  } catch {
    return undefined
  }
}

function entryOfNode(graph: Graph, node: Node, options: YarnBerryStringifyOptions = {}): SymlMap {
  const payload = graph.tarballOf(node.id)
  const resolution = resolutionOfNode(node)
  const entry: SymlMap = {
    version: node.version,
    resolution,
  }

  const dependencies = edgeBlockOfKind(graph, node, 'dep')
  if (dependencies !== undefined) entry['dependencies'] = dependencies

  const optionalDependencies = edgeBlockOfKind(graph, node, 'optional')
  if (optionalDependencies !== undefined) entry['optionalDependencies'] = optionalDependencies

  const peerDependencies = extraBlockOfNode(node, 'peerDependencies')
    ?? edgeBlockOfKind(graph, node, 'peer', { skipMissingRange: true })
  if (peerDependencies !== undefined) entry['peerDependencies'] = peerDependencies

  const peerDependenciesMeta = extraBlockOfNode(node, 'peerDependenciesMeta')
  if (peerDependenciesMeta !== undefined) entry['peerDependenciesMeta'] = peerDependenciesMeta

  const dependenciesMeta = extraBlockOfNode(node, 'dependenciesMeta')
  if (dependenciesMeta !== undefined) entry['dependenciesMeta'] = dependenciesMeta

  const bin = binBlockOfNode(node, payload)
  if (bin !== undefined) entry['bin'] = bin

  entry['linkType'] = node.workspacePath !== undefined ? 'soft' : 'hard'
  entry['languageName'] = node.workspacePath !== undefined ? 'unknown' : 'node'

  const conditions = extraBlockOfNode(node, 'conditions')
  if (conditions !== undefined) entry['conditions'] = conditions

  if (payload?.integrity !== undefined) entry['checksum'] = payload.integrity
  if (node.peerContext.length > 0) {
    emitStringifyDiagnostic(options, {
      code: 'YARN_BERRY_V9_PEER_VIRT_FLATTENED',
      subject: node.id,
      severity: 'warning',
      message: `peerContext ${JSON.stringify(node.peerContext)} flattens to ${resolution}`,
    })
  }

  return entry
}

function resolutionOfNode(node: Node): string {
  if (node.patch?.startsWith('unresolved-')) {
    if (node.resolution === undefined || patchLocatorOfResolution(node.resolution) === undefined) {
      throw new LockfileError({
        code: 'MISSING_REQUIRED_FIELD',
        message: `sentinel patch node ${node.id} requires an original patch resolution to emit`,
      })
    }
    return node.resolution
  }

  if (node.resolution !== undefined) return node.resolution
  if (node.workspacePath !== undefined) {
    return `${node.name}@workspace:${node.workspacePath === '' ? '.' : node.workspacePath}`
  }
  return `${node.name}@npm:${node.version}`
}

function edgeBlockOfKind(
  graph: Graph,
  node: Node,
  kind: EdgeKind,
  options: { skipMissingRange?: boolean } = {},
): SymlMap | undefined {
  const edges = graph.out(node.id, kind)
  if (edges.length === 0) return undefined

  const blockEntries: Array<[string, string]> = []
  const seen = new Set<string>()

  for (const edge of edges) {
    const dst = graph.getNode(edge.dst)
    if (dst === undefined) {
      throw new LockfileError({
        code: 'INVARIANT_VIOLATION',
        message: `edge from ${node.id} points to missing node ${edge.dst}`,
      })
    }
    if (edge.attrs?.range === undefined) {
      if (options.skipMissingRange) {
        continue
      }
      throw new LockfileError({
        code: 'MISSING_REQUIRED_FIELD',
        message: `edge ${node.id} -> ${edge.dst} (${kind}) requires attrs.range for emit`,
      })
    }

    const depName = dst.name
    if (seen.has(depName)) {
      throw new LockfileError({
        code: 'INVARIANT_VIOLATION',
        message: `cannot emit duplicate ${kind} dependency key ${depName} from ${node.id}`,
      })
    }
    seen.add(depName)
    blockEntries.push([depName, edge.attrs.range])
  }

  if (blockEntries.length === 0) return undefined
  blockEntries.sort((a, b) => cmpStr(a[0]!, b[0]!))

  const block: SymlMap = {}
  for (const [name, range] of blockEntries) {
    block[name] = range
  }
  return block
}

function extraBlockOfNode(node: Node, field: string): SymlMap | undefined {
  return coerceSymlMap((node as unknown as Record<string, unknown>)[field])
}

function coerceSymlMap(value: unknown): SymlMap | undefined {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return undefined

  const raw = value as Record<string, unknown>
  const block: SymlMap = {}
  for (const key of Object.keys(raw).sort(cmpStr)) {
    const coerced = coerceSymlValue(raw[key])
    if (coerced !== undefined) {
      block[key] = coerced
    }
  }

  return Object.keys(block).length > 0 ? block : undefined
}

function coerceSymlValue(value: unknown): SymlValue | undefined {
  if (typeof value === 'string') return value
  if (typeof value === 'number' || typeof value === 'boolean') return String(value)
  return coerceSymlMap(value)
}

function binBlockOfNode(node: Node, payload: TarballPayload | undefined): SymlMap | undefined {
  if (payload?.bin === undefined) return undefined
  if (typeof payload.bin === 'string') {
    return { [node.name]: payload.bin }
  }

  const block: SymlMap = {}
  for (const name of Object.keys(payload.bin).sort(cmpStr)) {
    const target = payload.bin[name]
    if (target !== undefined) block[name] = target
  }
  return Object.keys(block).length > 0 ? block : undefined
}

function extractPatchFingerprint(
  nodeId: string,
  resolution: string,
  workspaceRoot: string | undefined,
): { patch: string; diagnostic?: Diagnostic } | undefined {
  const locator = patchLocatorOfResolution(resolution)
  if (locator === undefined) return undefined

  const source = patchSourceOfLocator(locator)
  if (source === undefined) {
    return unresolvedPatch(nodeId, locator, `patch locator has no source fragment`)
  }

  if (source.startsWith('~builtin<')) {
    const yarnMajor = yarnMajorOfBuiltinPatch(resolution)
    if (yarnMajor === undefined) {
      return unresolvedPatch(nodeId, locator, `builtin patch yarn-major is unavailable at parse time`)
    }
    return { patch: sha512Hex(`${yarnMajor}:${source}`) }
  }

  if (workspaceRoot === undefined) {
    return unresolvedPatch(nodeId, locator, `workspaceRoot is unavailable at parse time`)
  }

  const bytes = readWorkspaceFileBytes(workspaceRoot, source, locator)
  if (bytes === undefined) {
    return unresolvedPatch(nodeId, locator, `patch file is unavailable at parse time`)
  }

  return { patch: sha512Hex(bytes) }
}

function patchLocatorOfResolution(resolution: string): string | undefined {
  if (resolution.startsWith('patch:')) return resolution
  const idx = resolution.indexOf('@patch:')
  return idx >= 0 ? resolution.slice(idx + 1) : undefined
}

function patchSourceOfLocator(locator: string): string | undefined {
  const hashIdx = locator.indexOf('#')
  if (hashIdx < 0) return undefined
  const paramsIdx = locator.indexOf('::', hashIdx + 1)
  const source = paramsIdx < 0
    ? locator.slice(hashIdx + 1)
    : locator.slice(hashIdx + 1, paramsIdx)
  return isDegeneratePatchSource(source) ? undefined : source
}

function isDegeneratePatchSource(source: string): boolean {
  let decoded: string
  try {
    decoded = decodeURIComponent(source)
  } catch {
    return false
  }

  const trimmed = decoded.trim()
  if (trimmed === '') return true
  if (path.posix.isAbsolute(trimmed)) return false

  const segments = path.posix.normalize(trimmed).split('/').filter(segment => segment !== '' && segment !== '.')
  return segments.length === 0
}

function yarnMajorOfBuiltinPatch(_resolution: string): string | undefined {
  return undefined
}

function unresolvedPatch(nodeId: string, locator: string, reason: string): { patch: string; diagnostic: Diagnostic } {
  return {
    patch: `unresolved-${sha256Hex(locator)}`,
    diagnostic: {
      code: 'YARN_BERRY_PATCH_UNRESOLVED',
      subject: nodeId,
      severity: 'warning',
      message: `${reason}; using sentinel for ${locator}`,
    },
  }
}

function sha512Hex(value: string | Uint8Array): string {
  return createHash('sha512').update(value).digest('hex')
}

function sha256Hex(value: string): string {
  return createHash('sha256').update(value, 'utf8').digest('hex')
}

function addEdgesFromBlock(
  builder: ReturnType<typeof newBuilder>,
  srcId:   string,
  block:   SymlMap | undefined,
  kind:    EdgeKind,
  index:   Map<string, string>,
  diag:    Diagnostic[],
): void {
  if (!block) return
  for (const [depName, depRange] of Object.entries(block)) {
    if (typeof depRange !== 'string') continue
    const lookup = `${depName}@${depRange}`
    const dstId  = index.get(lookup)
    if (!dstId) {
      diag.push({
        code:    'YARN_BERRY_UNRESOLVED_DEP',
        subject: srcId,
        severity: 'warning',
        message: `dependency ${depName}=${depRange} from ${srcId} has no matching lockfile entry`,
      })
      continue
    }
    builder.addEdge(srcId, dstId, kind, { range: depRange })
  }
}
